<%--

    TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.
    Copyright (C) 2007 Autentia Real Bussiness Solution S.L.

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

--%>

<%@page language="java" contentType="text/html; charset=UTF-8"%>

<%@include file="/inc/tlibs.jsp" %>

<html>
  <head>
    <%@include file="/inc/uiCore.jsp" %>
  </head>	
  <body>
    
    <!-- editPublication.jsp: generated by stajanov code generator -->
    <f:loadBundle basename="com.autentia.tnt.resources.messages" var="msg" />
    <i:location place="editPublication" msg="${msg}"/> 
    
    <f:view>
        <%@include file="/inc/header.jsp" %>
      <h:form id="publication" enctype="multipart/form-data">
        
        <%-- Header --%>
        <i:titleBar name="${publicationBean.name}" msg="${msg}">
          <h:commandLink action="#{publicationBean.save}">
            <h:graphicImage value="/img/save.gif" styleClass="titleImg" />
          </h:commandLink>
          <h:commandLink action="#{publicationBean.delete}" onclick="if( !confirm('#{msg['question.confirmDelete']}') ) return false;">
            <h:graphicImage value="/img/delete.gif" styleClass="titleImg" />
          </h:commandLink>
          <h:commandLink action="#{publicationBean.list}" immediate="true">
            <h:graphicImage value="/img/back.gif" styleClass="titleImg" />
          </h:commandLink>
        </i:titleBar>
        
        <%-- Edition form --%>
        <table class="editTable" cellpadding="0" cellspacing="0">

<%-- publication - generated by stajanov (do not edit/delete) --%>








                  
  
      <%-- Ignored field: id --%>
  
                                  
    
      <%-- Field: name --%>
    <tr>
    	    		<td class="editLabelRW">*${msg['publication.name']}:</td>
    	      
      <td class="editFieldCell">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="name" />
                		<h:inputText id="name" value="#{publicationBean.name}" size="70" maxlength="128" required="true" styleClass="requiredFieldClass"/>
    	              </h:panelGroup>

              </td>
    </tr>
                                  
    
      <%-- Field: magazineDeliveryDate --%>
    <tr>
    	    		<td class="editLabelRW">*${msg['publication.magazineDeliveryDate']}:</td>
    	      
      <td class="editFieldCell">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="magazineDeliveryDate" />
            <t:inputCalendar id="magazineDeliveryDate" value="#{publicationBean.magazineDeliveryDate}"  required="true" styleClass="requiredFieldClass"
                             renderAsPopup="true" popupDateFormat="d/MM/yyyy" renderPopupButtonAsImage="true" 
                             popupTodayString="#{msg['calendar.today']}" popupWeekString="#{msg['calendar.week']}"
                             />
          </h:panelGroup>

              </td>
    </tr>
                                  
  
      <%-- Field: magazinePublicationDate --%>
    <tr>
    	    		<td class="editLabelRW">${msg['publication.magazinePublicationDate']}:</td>
    	      
      <td class="editFieldCell">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="magazinePublicationDate" />
            <t:inputCalendar id="magazinePublicationDate" value="#{publicationBean.magazinePublicationDate}" 
                             renderAsPopup="true" popupDateFormat="d/MM/yyyy" renderPopupButtonAsImage="true" 
                             popupTodayString="#{msg['calendar.today']}" popupWeekString="#{msg['calendar.week']}"
                             />
          </h:panelGroup>

              </td>
    </tr>
                                  
  
      <%-- Field: ownPublicationDate --%>
    <tr>
    	    		<td class="editLabelRW">${msg['publication.ownPublicationDate']}:</td>
    	      
      <td class="editFieldCell">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="ownPublicationDate" />
            <t:inputCalendar id="ownPublicationDate" value="#{publicationBean.ownPublicationDate}" 
                             renderAsPopup="true" popupDateFormat="d/MM/yyyy" renderPopupButtonAsImage="true" 
                             popupTodayString="#{msg['calendar.today']}" popupWeekString="#{msg['calendar.week']}"
                             />
          </h:panelGroup>

              </td>
    </tr>
                                  
  
      <%-- Field: accepted --%>
    <tr>
    	    		<td class="editLabelRW">${msg['publication.accepted']}:</td>
    	      
      <td class="editFieldCell">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="accepted" />
                		<h:inputText id="accepted" value="#{publicationBean.accepted}" />
    	              </h:panelGroup>

              </td>
    </tr>
                                  
  
      <%-- Ignored field: ownerId --%>
  
                                  
  
      <%-- Ignored field: departmentId --%>
  
                                  
  
      <%-- Ignored field: insertDate --%>
  
                                  
  
      <%-- Ignored field: updateDate --%>
  
                                              
    
      <%-- Field: magazine --%>
    <tr>
    	    		<td class="editLabelRW">*${msg['publication.magazine']}:</td>
    	      
      <td class="editFieldCell">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="magazine" />
            <h:selectOneMenu id="magazine" value="#{publicationBean.magazine}"  required="true" styleClass="requiredFieldClass">
              <f:selectItems value="#{publicationBean.magazines}" />
              <f:converter converterId="autentia.EntityConverter"/>
            </h:selectOneMenu>
          </h:panelGroup>

              </td>
    </tr>
                                      


<%-- publication - generated by stajanov (do not edit/delete) --%>

        </table>
        
      </h:form>
    </f:view>
    
  </body>
</html>  		

