<%--

    TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.
    Copyright (C) 2007 Autentia Real Bussiness Solution S.L.

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

--%>

<%@page language="java" contentType="text/html; charset=UTF-8"%>

<%@include file="/inc/tlibs.jsp" %>

<html>
  <head>
    <%@include file="/inc/uiCore.jsp" %>
  </head>	
  <body>
    
    <!-- editSetting.jsp: generated by stajanov code generator -->
    <f:loadBundle basename="com.autentia.tnt.resources.messages" var="msg" />
    <i:location place="editSetting" msg="${msg}"/> 
    
    <f:view>
       <%@include file="/inc/header.jsp" %>
      <h:form id="setting" enctype="multipart/form-data">
        
        <%-- Header --%>
        <i:titleBar name="${settingBean.name}" msg="${msg}">
          <h:commandLink action="#{settingBean.save}" onclick="if(!askSave('#{settingBean.id}','#{msg['question.confirmSave']}')) return false;">
            <h:graphicImage title="#{msg.entityActions_save}"  value="/img/save.gif" styleClass="titleImg" />
          </h:commandLink>
          <h:commandLink action="#{settingBean.delete}" onclick="if( !confirm('#{msg['question.confirmDelete']}') ) return false;">
            <h:graphicImage title="#{msg.entityActions_delete}"  value="/img/delete.gif" styleClass="titleImg" />
          </h:commandLink>
          <h:commandLink action="#{settingBean.list}" immediate="true">
            <h:graphicImage title="#{msg.entityActions_back}"  value="/img/back.gif" styleClass="titleImg" />
          </h:commandLink>
        </i:titleBar>        
        
        <%-- Edition form --%>
        <table class="editTable" cellpadding="0" cellspacing="0">
		
<%-- generated by stajanov (do not edit/delete) --%>








                  
  
      <%-- Ignored field: id --%>
  
                                  
    
      <%-- Field: name --%>
    <tr>
    	    		<td class="editLabelRW">*${msg['setting.name']}:</td>
    	      
      <td class="editFieldCell">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="name" />
                		<h:inputText id="name" value="#{settingBean.name}" size="70" maxlength="200" required="true" styleClass="requiredFieldClass"/>
    	              </h:panelGroup>

              </td>
    </tr>
                                  
  
      <%-- Field: value --%>
    <tr>
    	    		<td class="editLabelRW">${msg['setting.value']}:</td>
    	      
      <td class="editFieldCell">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="value" />
                		<h:inputText id="value" value="#{settingBean.value}" size="70" maxlength="200"/>
    	              </h:panelGroup>

              </td>
    </tr>
                                  
  
      <%-- Field: type --%>
    <tr>
    	    		<td class="editLabelRW">${msg['setting.type']}:</td>
    	      
      <td class="editFieldCell">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="type" />
            <h:selectOneMenu id="type" value="#{settingBean.type}" >
              <f:converter converterId="autentia.EnumConverter"/>
              <f:selectItems value="#{settingBean.types}" />
            </h:selectOneMenu>
          </h:panelGroup>

              </td>
    </tr>
                                  
  
      <%-- Ignored field: ownerId --%>
  
                                  
  
      <%-- Ignored field: departmentId --%>
  
                                  
  
      <%-- Ignored field: insertDate --%>
  
                                  
  
      <%-- Ignored field: updateDate --%>
  
                                                  


<%-- generated by stajanov (do not edit/delete) --%>
    </table>
        
      </h:form>
    </f:view>
    
  </body>
</html>  		

