<%--

    TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.
    Copyright (C) 2007 Autentia Real Bussiness Solution S.L.

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

--%>

<%@page language="java" contentType="text/html; charset=UTF-8"%>

<%@include file="/inc/tlibs.jsp" %>

<html>
  <head>
    <%@include file="/inc/uiCore.jsp" %>
  </head>	
  <body>
    
   
    <f:loadBundle basename="com.autentia.tnt.resources.messages" var="msg" />
    <i:location place="editContractType" msg="${msg}"/> 
    
    <f:view>
       <%@include file="/inc/header.jsp" %>
      <h:form id="contractType" enctype="multipart/form-data">
        
        <%-- Header --%>
        <i:titleBar name="${contractTypeBean.name}" msg="${msg}">
          <h:commandLink action="#{contractTypeBean.save}">
            <h:graphicImage value="/img/save.gif" styleClass="titleImg" />
          </h:commandLink>
          <h:commandLink action="#{contractTypeBean.delete}" onclick="if( !confirm('#{msg['question.confirmDelete']}') ) return false;">
            <h:graphicImage value="/img/delete.gif" styleClass="titleImg" />
          </h:commandLink>
          <h:commandLink action="#{contractTypeBean.list}" immediate="true">
            <h:graphicImage value="/img/back.gif" styleClass="titleImg" />
          </h:commandLink>
        </i:titleBar>
        
        <%-- Edition form --%>
        <table class="editContractType" cellpadding="0" cellspacing="0">




<%-- ContractType - generated by stajanov (do not edit/delete) --%>








                  
  
      <%-- Ignored field: id --%>
  
                                  
    
      <%-- Field: name --%>
    <tr>
    	    		<td class="editLabelRW">*${msg['contractType.name']}:</td>
    	      
      <td class="editFieldCell">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="name" />
                		<h:inputText id="name" value="#{contractTypeBean.name}" size="70" maxlength="128" required="true" styleClass="requiredFieldClass"/>
    	              </h:panelGroup>

              </td>
    </tr>
                                  
  
      <%-- Field: description --%>
    <tr>
    	    		<td class="editLabelRW">${msg['contractType.description']}:</td>
    	      
      <td class="editFieldCell">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="description" />
            <h:inputTextarea id="description" value="#{contractTypeBean.description}" rows="5" cols="68"/>
          </h:panelGroup>

              </td>
    </tr>
                                  
  
      <%-- Ignored field: ownerId --%>
  
                                  
  
      <%-- Ignored field: departmentId --%>
  
                                  
  
      <%-- Ignored field: insertDate --%>
  
                                  
  
      <%-- Ignored field: updateDate --%>
  
                                                  


<%-- ContractType - generated by stajanov (do not edit/delete) --%>



</table>
        
      </h:form>
    </f:view>
    
  </body>
</html>  	
