<%--

    TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.
    Copyright (C) 2007 Autentia Real Bussiness Solution S.L.

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

--%>

<%-- 
 * TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.  
 *	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.					   
 *	
 * 	This program is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU General Public License
 * 	as published by the Free Software Foundation; either version 2
 * 	of the License, or (at your option) any later version.
 *
 * 	This program is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *
 * 	You should have received a copy of the GNU General Public License
 * 	along with this program; if not, write to the Free Software
 * 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 	Autentia Real Bussiness Solution S.L.
 * 	Tlf: +34 91 675 33 06, +34 655 99 11 72
 * 	Fax: +34 91 656 65 04
 * 	info@autentia.com																
 *
 --%>
<%@page language="java" contentType="text/html; charset=UTF-8"%>

<%@include file="/inc/tlibs.jsp" %>

<html>
  <head>
    <%@include file="/inc/uiCore.jsp" %>
  </head>	
  <body>
    
    <!-- searchProject.jsp: generated by stajanov code generator -->
    <f:loadBundle basename="com.autentia.tnt.resources.messages" var="msg" />
    <i:location place="searchProject" msg="${msg}"/> 
    
    <f:view>
      <%@include file="/inc/header.jsp" %>
      <h:form id="search" enctype="multipart/form-data">
        
        <%-- Header --%>
        <i:titleBar msg="${msg}">
          <h:commandLink action="#{projectBean.list}">
            <h:graphicImage title="#{msg.entityActions_run}"  value="/img/run.png" styleClass="titleImg" />
          </h:commandLink>
        </i:titleBar>
        
        <%-- Search form --%>
        <table class="searchTable" cellpadding="0" cellspacing="0">

          
      <%-- Ignored field: id --%>

                        
      <%-- Field: startDate --%>
    <tr>
      <td class="searchLabel">${msg['project.startDate']}:</td>
      <td class="searchFieldCell">

        
                    
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="startStartDate" />
            <h:selectBooleanCheckbox id="startStartDateValid" value="#{projectBean.searchStartStartDateValid}" 
                                      onclick="setEnabled('search:startStartDate',this.checked)"/>
            <t:inputCalendar id="startStartDate" value="#{projectBean.searchStartStartDate}"
                             renderAsPopup="true" popupDateFormat="d/MM/yyyy" renderPopupButtonAsImage="true" 
                             popupTodayString="#{msg['calendar.today']}" popupWeekString="#{msg['calendar.week']}"
                             onchange="setEnabled('search:startStartDate',true);setChecked('search:startStartDateValid',true);"
                             >
				<f:validator validatorId="autentia.dateValidator"/>
			</t:inputCalendar>
          </h:panelGroup>
          -
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="endStartDate" />
            <h:selectBooleanCheckbox id="endStartDateValid" value="#{projectBean.searchEndStartDateValid}" 
                                      onclick="setEnabled('search:endStartDate',this.checked)"/>
            <t:inputCalendar id="endStartDate" value="#{projectBean.searchEndStartDate}"
                             renderAsPopup="true" popupDateFormat="d/MM/yyyy" renderPopupButtonAsImage="true" 
                             popupTodayString="#{msg['calendar.today']}" popupWeekString="#{msg['calendar.week']}"
                             onchange="setEnabled('search:endStartDate',true);setChecked('search:endStartDateValid',true);"
                             >
				<f:validator validatorId="autentia.dateValidator"/>
			</t:inputCalendar>
          </h:panelGroup>
          <script>
            setEnabled( 'search:startStartDate', ${projectBean.searchStartStartDateValid} )
            setEnabled( 'search:endStartDate', ${projectBean.searchEndStartDateValid} )
          </script>

        
      </td>
    </tr>
                        
      <%-- Field: endDate --%>
    <tr>
      <td class="searchLabel">${msg['project.endDate']}:</td>
      <td class="searchFieldCell">

        
                    
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="startEndDate" />
            <h:selectBooleanCheckbox id="startEndDateValid" value="#{projectBean.searchStartEndDateValid}" 
                                      onclick="setEnabled('search:startEndDate',this.checked)"/>
            <t:inputCalendar id="startEndDate" value="#{projectBean.searchStartEndDate}"
                             renderAsPopup="true" popupDateFormat="d/MM/yyyy" renderPopupButtonAsImage="true" 
                             popupTodayString="#{msg['calendar.today']}" popupWeekString="#{msg['calendar.week']}"
                             onchange="setEnabled('search:startEndDate',true);setChecked('search:startEndDateValid',true);"
                             >
				<f:validator validatorId="autentia.dateValidator"/>
			</t:inputCalendar>
          </h:panelGroup>
          -
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="endEndDate" />
            <h:selectBooleanCheckbox id="endEndDateValid" value="#{projectBean.searchEndEndDateValid}" 
                                      onclick="setEnabled('search:endEndDate',this.checked)"/>
            <t:inputCalendar id="endEndDate" value="#{projectBean.searchEndEndDate}"
                             renderAsPopup="true" popupDateFormat="d/MM/yyyy" renderPopupButtonAsImage="true" 
                             popupTodayString="#{msg['calendar.today']}" popupWeekString="#{msg['calendar.week']}"
                             onchange="setEnabled('search:endEndDate',true);setChecked('search:endEndDateValid',true);"
                             >
				<f:validator validatorId="autentia.dateValidator"/>
			</t:inputCalendar>
          </h:panelGroup>
          <script>
            setEnabled( 'search:startEndDate', ${projectBean.searchStartEndDateValid} )
            setEnabled( 'search:endEndDate', ${projectBean.searchEndEndDateValid} )
          </script>

        
      </td>
    </tr>
                        
      <%-- Field: open --%>
    <tr>
      <td class="searchLabel">${msg['project.open']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="open" />
            <h:selectBooleanCheckbox id="openValid" value="#{projectBean.searchOpenValid}" 
                                      onclick="setEnabled('search:open',this.checked)"/>
                                      
            <h:outputLabel for="open" value="#{msg['msg.yesno']}"></h:outputLabel>
            <h:selectBooleanCheckbox id="open" value="#{projectBean.searchOpen}"/>                          
           
          </h:panelGroup>
          <script>
            setEnabled( 'search:open', ${projectBean.searchOpenValid} )
          </script>
			
			
			
        
      </td>
    </tr>
                        
      <%-- Field: name --%>
    <tr>
      <td class="searchLabel">${msg['project.name']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="name" />
            <h:selectBooleanCheckbox id="nameValid" value="#{projectBean.searchNameValid}" 
                                      onclick="setEnabled('search:name',this.checked)"/>
            <h:inputText id="name" value="#{projectBean.searchName}" size="70"/>
          </h:panelGroup>
          <script>
            setEnabled( 'search:name', ${projectBean.searchNameValid} )
          </script>

        
      </td>
    </tr>
                        
      <%-- Field: description --%>
    <tr>
      <td class="searchLabel">${msg['project.description']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="description" />
            <h:selectBooleanCheckbox id="descriptionValid" value="#{projectBean.searchDescriptionValid}" 
                                      onclick="setEnabled('search:description',this.checked)"/>
            <h:inputText id="description" value="#{projectBean.searchDescription}" size="70"/>
          </h:panelGroup>
          <script>
            setEnabled( 'search:description', ${projectBean.searchDescriptionValid} )
          </script>

        
      </td>
    </tr>
                        
      <%-- Field: billable --%>
    <tr>
      <td class="searchLabel">${msg['project.billable']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="billable" />
            <h:selectBooleanCheckbox id="billableValid" value="#{projectBean.searchBillableValid}" 
                                      onclick="setEnabled('search:billable',this.checked)"/>
            
            <h:outputLabel for="billable" value="#{msg['msg.yesno']}"></h:outputLabel>
            <h:selectBooleanCheckbox id="billable" value="#{projectBean.searchBillable}"/>
            
            
          </h:panelGroup>
          <script>
            setEnabled( 'search:billable', ${projectBean.searchBillableValid} )
          </script>

        
      </td>
    </tr>
                        
      <%-- Ignored field: ownerId --%>

                        
      <%-- Ignored field: departmentId --%>

                        
      <%-- Ignored field: insertDate --%>

                        
      <%-- Ignored field: updateDate --%>

                                  
      <%-- Field: client --%>
    <tr>
      <td class="searchLabel">${msg['project.client']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="client" />
            <h:selectBooleanCheckbox id="clientValid" value="#{projectBean.searchClientValid}" 
                                      onclick="setEnabled('search:client',this.checked)"/>
            <h:selectOneMenu id="client" value="#{projectBean.searchClient}" onclick="setEnabled('search:client',true)">
              <f:selectItems value="#{projectBean.clients}" />
              <f:converter converterId="autentia.EntityConverter"/>
            </h:selectOneMenu>
          </h:panelGroup>
          <script>
            setEnabled( 'search:client', ${projectBean.searchClientValid} )
          </script>

        
      </td>
    </tr>
                                            
      <%-- Ignored field: roles --%>

                        
      <%-- Ignored field: costs --%>

            
        </table>
        
      </h:form>
    </f:view>
    
  </body>
</html>  		
