<%--

    TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.
    Copyright (C) 2007 Autentia Real Bussiness Solution S.L.

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

--%>

<%-- 
 * TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.  
 *	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.					   
 *	
 * 	This program is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU General Public License
 * 	as published by the Free Software Foundation; either version 2
 * 	of the License, or (at your option) any later version.
 *
 * 	This program is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *
 * 	You should have received a copy of the GNU General Public License
 * 	along with this program; if not, write to the Free Software
 * 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 	Autentia Real Bussiness Solution S.L.
 * 	Tlf: +34 91 675 33 06, +34 655 99 11 72
 * 	Fax: +34 91 656 65 04
 * 	info@autentia.com																
 *
 --%>
<%@page language="java" contentType="text/html; charset=UTF-8"%>

<%@include file="/inc/tlibs.jsp" %>

<html>
  <head>
    <%@include file="/inc/uiCore.jsp" %>
  </head>	
  <body>
    
    <!-- searchIdea.jsp: generated by stajanov code generator -->
    <f:loadBundle basename="com.autentia.tnt.resources.messages" var="msg" />
    <i:location place="searchIdea" msg="${msg}"/> 
    
    <f:view>
      <%@include file="/inc/header.jsp" %>
      <h:form id="search" enctype="multipart/form-data">
        
        <%-- Header --%>
        <i:titleBar msg="${msg}">
          <h:commandLink action="#{ideaBean.list}">
            <h:graphicImage title="#{msg.entityActions_run}"  value="/img/run.png" styleClass="titleImg" />
          </h:commandLink>
        </i:titleBar>
        
        <%-- Search form --%>
        <table class="searchTable" cellpadding="0" cellspacing="0">

          
      <%-- Ignored field: id --%>

                        
      <%-- Field: creationDate --%>
    <tr>
      <td class="searchLabel">${msg['idea.creationDate']}:</td>
      <td class="searchFieldCell">

        
                    
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="startCreationDate" />
            <h:selectBooleanCheckbox id="startCreationDateValid" value="#{ideaBean.searchStartCreationDateValid}" 
                                      onclick="setEnabled('search:startCreationDate',this.checked)"/>
            <t:inputCalendar id="startCreationDate" value="#{ideaBean.searchStartCreationDate}"
                             renderAsPopup="true" popupDateFormat="d/MM/yyyy" renderPopupButtonAsImage="true" 
                             popupTodayString="#{msg['calendar.today']}" popupWeekString="#{msg['calendar.week']}"
                             onchange="setEnabled('search:startCreationDate',true);setChecked('search:startCreationDateValid',true);"
                             />
          </h:panelGroup>
          -
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="endCreationDate" />
            <h:selectBooleanCheckbox id="endCreationDateValid" value="#{ideaBean.searchEndCreationDateValid}" 
                                      onclick="setEnabled('search:endCreationDate',this.checked)"/>
            <t:inputCalendar id="endCreationDate" value="#{ideaBean.searchEndCreationDate}"
                             renderAsPopup="true" popupDateFormat="d/MM/yyyy" renderPopupButtonAsImage="true" 
                             popupTodayString="#{msg['calendar.today']}" popupWeekString="#{msg['calendar.week']}"
                             onchange="setEnabled('search:endCreationDate',true);setChecked('search:endCreationDateValid',true);"
                             />
          </h:panelGroup>
          <script>
            setEnabled( 'search:startCreationDate', ${ideaBean.searchStartCreationDateValid} )
            setEnabled( 'search:endCreationDate', ${ideaBean.searchEndCreationDateValid} )
          </script>

        
      </td>
    </tr>
                        
      <%-- Field: name --%>
    <tr>
      <td class="searchLabel">${msg['idea.name']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="name" />
            <h:selectBooleanCheckbox id="nameValid" value="#{ideaBean.searchNameValid}" 
                                      onclick="setEnabled('search:name',this.checked)"/>
            <h:inputText id="name" value="#{ideaBean.searchName}" size="70"/>
          </h:panelGroup>
          <script>
            setEnabled( 'search:name', ${ideaBean.searchNameValid} )
          </script>

        
      </td>
    </tr>
                        
      <%-- Field: description --%>
    <tr>
      <td class="searchLabel">${msg['idea.description']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="description" />
            <h:selectBooleanCheckbox id="descriptionValid" value="#{ideaBean.searchDescriptionValid}" 
                                      onclick="setEnabled('search:description',this.checked)"/>
            <h:inputText id="description" value="#{ideaBean.searchDescription}" size="70"/>
          </h:panelGroup>
          <script>
            setEnabled( 'search:description', ${ideaBean.searchDescriptionValid} )
          </script>

        
      </td>
    </tr>
                        
      <%-- Field: benefits --%>
    <tr>
      <td class="searchLabel">${msg['idea.benefits']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="benefits" />
            <h:selectBooleanCheckbox id="benefitsValid" value="#{ideaBean.searchBenefitsValid}" 
                                      onclick="setEnabled('search:benefits',this.checked)"/>
            <h:inputText id="benefits" value="#{ideaBean.searchBenefits}" size="70"/>
          </h:panelGroup>
          <script>
            setEnabled( 'search:benefits', ${ideaBean.searchBenefitsValid} )
          </script>

        
      </td>
    </tr>
                        
      <%-- Field: cost --%>
    <tr>
      <td class="searchLabel">${msg['idea.cost']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="cost" />
            <h:selectBooleanCheckbox id="costValid" value="#{ideaBean.searchCostValid}" 
                                      onclick="setEnabled('search:cost',this.checked)"/>
            <h:inputText id="cost" value="#{ideaBean.searchCost}" size="70"/>
          </h:panelGroup>
          <script>
            setEnabled( 'search:cost', ${ideaBean.searchCostValid} )
          </script>

        
      </td>
    </tr>
                        
      <%-- Ignored field: departmentId --%>

                        
      <%-- Ignored field: insertDate --%>

                        
      <%-- Ignored field: updateDate --%>

                                  
      <%-- Field: user --%>
    <tr>
      <td class="searchLabel">${msg['idea.user']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="user" />
            <h:selectBooleanCheckbox id="userValid" value="#{ideaBean.searchUserValid}" 
                                      onclick="setEnabled('search:user',this.checked)"/>
            <h:selectOneMenu id="user" value="#{ideaBean.searchUser}" onclick="setEnabled('search:user',true)">
              <f:selectItems value="#{ideaBean.users}" />
              <f:converter converterId="autentia.EntityConverter"/>
            </h:selectOneMenu>
          </h:panelGroup>
          <script>
            setEnabled( 'search:user', ${ideaBean.searchUserValid} )
          </script>

        
      </td>
    </tr>
                                
        </table>
        
      </h:form>
    </f:view>
    
  </body>
</html>  		
