<%--

    TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.
    Copyright (C) 2007 Autentia Real Bussiness Solution S.L.

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

--%>

<%-- 
 * TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.  
 *	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.					   
 *	
 * 	This program is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU General Public License
 * 	as published by the Free Software Foundation; either version 2
 * 	of the License, or (at your option) any later version.
 *
 * 	This program is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *
 * 	You should have received a copy of the GNU General Public License
 * 	along with this program; if not, write to the Free Software
 * 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 	Autentia Real Bussiness Solution S.L.
 * 	Tlf: +34 91 675 33 06, +34 655 99 11 72
 * 	Fax: +34 91 656 65 04
 * 	info@autentia.com																
 *
 --%>
<%@page language="java" contentType="text/html; charset=UTF-8"%>

<%@include file="/inc/tlibs.jsp" %>

<html>
  <head>
    <%@include file="/inc/uiCore.jsp" %>
  </head>	
  <body>
    
    <!-- searchUser.jsp: generated by stajanov code generator -->
    <f:loadBundle basename="com.autentia.tnt.resources.messages" var="msg" />
    <i:location place="searchUser" msg="${msg}"/> 
    
    <f:view>
      <%@include file="/inc/header.jsp" %>
      <h:form id="search" enctype="multipart/form-data">
        
        <%-- Header --%>
        <i:titleBar msg="${msg}">
          <h:commandLink action="#{userBean.list}">
            <h:graphicImage title="#{msg.entityActions_run}"  value="/img/run.png" styleClass="titleImg" />
          </h:commandLink>
        </i:titleBar>
        
        <%-- Search form --%>
        <table class="searchTable" cellpadding="0" cellspacing="0">

          
      <%-- Ignored field: id --%>

                        
      <%-- Field: active --%>
    <tr>
      <td class="searchLabel">${msg['user.active']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="active" />
            <h:selectBooleanCheckbox id="activeValid" value="#{userBean.searchActiveValid}" 
                                      onclick="setEnabledByName('search:active',this.checked)"/>
            
            <h:outputLabel for="active" value="#{msg['msg.yesno']}"></h:outputLabel>
            <h:selectBooleanCheckbox id="active" value="#{userBean.searchActive}"/>            
            
            
          </h:panelGroup>
          <script>
            setEnabledByName( 'search:active', ${userBean.searchActiveValid} )
          </script>

        
      </td>
    </tr>
                        
      <%-- Field: login --%>
    <tr>
      <td class="searchLabel">${msg['user.login']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="login" />
            <h:selectBooleanCheckbox id="loginValid" value="#{userBean.searchLoginValid}" 
                                      onclick="setEnabled('search:login',this.checked)"/>
            <h:inputText id="login" value="#{userBean.searchLogin}" size="70"/>
          </h:panelGroup>
          <script>
            setEnabled( 'search:login', ${userBean.searchLoginValid} )
          </script>

        
      </td>
    </tr>
                        
      <%-- Ignored field: password --%>

                        
      <%-- Field: name --%>
    <tr>
      <td class="searchLabel">${msg['user.name']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="name" />
            <h:selectBooleanCheckbox id="nameValid" value="#{userBean.searchNameValid}" 
                                      onclick="setEnabled('search:name',this.checked)"/>
            <h:inputText id="name" value="#{userBean.searchName}" size="70"/>
          </h:panelGroup>
          <script>
            setEnabled( 'search:name', ${userBean.searchNameValid} )
          </script>

        
      </td>
    </tr>
                        
      <%-- Ignored field: startDate --%>

                        
      <%-- Field: nif --%>
    <tr>
      <td class="searchLabel">${msg['user.nif']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="nif" />
            <h:selectBooleanCheckbox id="nifValid" value="#{userBean.searchNifValid}" 
                                      onclick="setEnabled('search:nif',this.checked)"/>
            <h:inputText id="nif" value="#{userBean.searchNif}" size="70"/>
          </h:panelGroup>
          <script>
            setEnabled( 'search:nif', ${userBean.searchNifValid} )
          </script>

        
      </td>
    </tr>
                        
      <%-- Field: genre --%>
    <tr>
      <td class="searchLabel">${msg['user.genre']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="genre" />
            <h:selectBooleanCheckbox id="genreValid" value="#{userBean.searchGenreValid}" 
                                      onclick="setEnabled('search:genre',this.checked)"/>
            <h:selectOneMenu id="genre" value="#{userBean.searchGenre}" onclick="setEnabled('search:genre',true)">
              <f:converter converterId="autentia.EnumConverter"/>
              <f:selectItems value="#{userBean.genres}" />
            </h:selectOneMenu>
          </h:panelGroup>
          <script>
            setEnabled( 'search:genre', ${userBean.searchGenreValid} )
          </script>

        
      </td>
    </tr>
                        
      <%-- Field: socialSecurityNumber --%>
    <tr>
      <td class="searchLabel">${msg['user.socialSecurityNumber']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="socialSecurityNumber" />
            <h:selectBooleanCheckbox id="socialSecurityNumberValid" value="#{userBean.searchSocialSecurityNumberValid}" 
                                      onclick="setEnabled('search:socialSecurityNumber',this.checked)"/>
            <h:inputText id="socialSecurityNumber" value="#{userBean.searchSocialSecurityNumber}" size="70"/>
          </h:panelGroup>
          <script>
            setEnabled( 'search:socialSecurityNumber', ${userBean.searchSocialSecurityNumberValid} )
          </script>

        
      </td>
    </tr>
                        
      <%-- Field: workingInClient --%>
    <tr>
      <td class="searchLabel">${msg['user.workingInClient']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="workingInClient" />
            <h:selectBooleanCheckbox id="workingInClientValid" value="#{userBean.searchWorkingInClientValid}" 
                                      onclick="setEnabledByName('search:workingInClient',this.checked)"/>
            
            <h:outputLabel for="workingInClient" value="#{msg['msg.yesno']}"></h:outputLabel>
            <h:selectBooleanCheckbox id="workingInClient" value="#{userBean.searchWorkingInClient}"/>            
            
            
          </h:panelGroup>
          <script>
            setEnabledByName( 'search:workingInClient', ${userBean.searchWorkingInClientValid} )
          </script>

        
      </td>
    </tr>
                        
      <%-- Field: birthDate --%>
    <tr>
      <td class="searchLabel">${msg['user.birthDate']}:</td>
      <td class="searchFieldCell">

        
                    
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="startBirthDate" />
            <h:selectBooleanCheckbox id="startBirthDateValid" value="#{userBean.searchStartBirthDateValid}" 
                                      onclick="setEnabled('search:startBirthDate',this.checked)"/>
            <t:inputCalendar id="startBirthDate" value="#{userBean.searchStartBirthDate}"
                             renderAsPopup="true" popupDateFormat="d/MM/yyyy" renderPopupButtonAsImage="true" 
                             popupTodayString="#{msg['calendar.today']}" popupWeekString="#{msg['calendar.week']}"
                             onchange="setEnabled('search:startBirthDate',true);setChecked('search:startBirthDateValid',true);"
                             >
				<f:validator validatorId="autentia.dateValidator"/>
			</t:inputCalendar>
          </h:panelGroup>
          -
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="endBirthDate" />
            <h:selectBooleanCheckbox id="endBirthDateValid" value="#{userBean.searchEndBirthDateValid}" 
                                      onclick="setEnabled('search:endBirthDate',this.checked)"/>
            <t:inputCalendar id="endBirthDate" value="#{userBean.searchEndBirthDate}"
                             renderAsPopup="true" popupDateFormat="d/MM/yyyy" renderPopupButtonAsImage="true" 
                             popupTodayString="#{msg['calendar.today']}" popupWeekString="#{msg['calendar.week']}"
                             onchange="setEnabled('search:endBirthDate',true);setChecked('search:endBirthDateValid',true);"
                             >
				<f:validator validatorId="autentia.dateValidator"/>
			</t:inputCalendar>
          </h:panelGroup>
          <script>
            setEnabled( 'search:startBirthDate', ${userBean.searchStartBirthDateValid} )
            setEnabled( 'search:endBirthDate', ${userBean.searchEndBirthDateValid} )
          </script>

        
      </td>
    </tr>
                        
      <%-- Field: married --%>
    <tr>
      <td class="searchLabel">${msg['user.married']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="married" />
            <h:selectBooleanCheckbox id="marriedValid" value="#{userBean.searchMarriedValid}" 
                                      onclick="setEnabledByName('search:married',this.checked)"/>
            
            <h:outputLabel for="married" value="#{msg['msg.yesno']}"></h:outputLabel>
            <h:selectBooleanCheckbox id="married" value="#{userBean.searchMarried}"/>            
            
            
          </h:panelGroup>
          <script>
            setEnabledByName( 'search:married', ${userBean.searchMarriedValid} )
          </script>

        
      </td>
    </tr>
                        
      <%-- Field: childrenNumber --%>
    <tr>
      <td class="searchLabel">${msg['user.childrenNumber']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="childrenNumber" />
            <h:selectBooleanCheckbox id="childrenNumberValid" value="#{userBean.searchChildrenNumberValid}" 
                                      onclick="setEnabled('search:childrenNumber',this.checked)"/>
            <h:inputText id="childrenNumber" value="#{userBean.searchChildrenNumber}" size="70"/>
          </h:panelGroup>
          <script>
            setEnabled( 'search:childrenNumber', ${userBean.searchChildrenNumberValid} )
          </script>

        
      </td>
    </tr>
                        
      <%-- Ignored field: travelAvailability --%>

                        
      <%-- Ignored field: academicQualification --%>

                        
      <%-- Field: email --%>
    <tr>
      <td class="searchLabel">${msg['user.email']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="email" />
            <h:selectBooleanCheckbox id="emailValid" value="#{userBean.searchEmailValid}" 
                                      onclick="setEnabled('search:email',this.checked)"/>
            <h:inputText id="email" value="#{userBean.searchEmail}" size="70"/>
          </h:panelGroup>
          <script>
            setEnabled( 'search:email', ${userBean.searchEmailValid} )
          </script>

        
      </td>
    </tr>
                        
      <%-- Ignored field: phone --%>

                        
      <%-- Ignored field: mobile --%>

                        
      <%-- Ignored field: street --%>

                        
      <%-- Ignored field: postalCode --%>

                        
      <%-- Ignored field: city --%>

                        
      <%-- Ignored field: bank --%>

                        
      <%-- Ignored field: account --%>

                        
      <%-- Field: salary --%>
    <tr>
      <td class="searchLabel">${msg['user.salary']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="salary" />
            <h:selectBooleanCheckbox id="salaryValid" value="#{userBean.searchSalaryValid}" 
                                      onclick="setEnabled('search:salary',this.checked)"/>
            <h:inputText id="salary" value="#{userBean.searchSalary}" size="70"/>
          </h:panelGroup>
          <script>
            setEnabled( 'search:salary', ${userBean.searchSalaryValid} )
          </script>

        
      </td>
    </tr>
                        
      <%-- Field: salaryExtras --%>
    <tr>
      <td class="searchLabel">${msg['user.salaryExtras']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="salaryExtras" />
            <h:selectBooleanCheckbox id="salaryExtrasValid" value="#{userBean.searchSalaryExtrasValid}" 
                                      onclick="setEnabled('search:salaryExtras',this.checked)"/>
            <h:inputText id="salaryExtras" value="#{userBean.searchSalaryExtras}" size="70"/>
          </h:panelGroup>
          <script>
            setEnabled( 'search:salaryExtras', ${userBean.searchSalaryExtrasValid} )
          </script>

        
      </td>
    </tr>
                        
      <%-- Ignored field: drivenLicenseType --%>

                        
      <%-- Ignored field: vehicleType --%>

                        
      <%-- Ignored field: licensePlate --%>

                        
      <%-- Field: securityCard --%>
    <tr>
      <td class="searchLabel">${msg['user.securityCard']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="securityCard" />
            <h:selectBooleanCheckbox id="securityCardValid" value="#{userBean.searchSecurityCardValid}" 
                                      onclick="setEnabled('search:securityCard',this.checked)"/>
            <h:inputText id="securityCard" value="#{userBean.searchSecurityCard}" size="70"/>
          </h:panelGroup>
          <script>
            setEnabled( 'search:securityCard', ${userBean.searchSecurityCardValid} )
          </script>

        
      </td>
    </tr>
                        
      <%-- Field: healthInsurance --%>
    <tr>
      <td class="searchLabel">${msg['user.healthInsurance']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="healthInsurance" />
            <h:selectBooleanCheckbox id="healthInsuranceValid" value="#{userBean.searchHealthInsuranceValid}" 
                                      onclick="setEnabled('search:healthInsurance',this.checked)"/>
            <h:inputText id="healthInsurance" value="#{userBean.searchHealthInsurance}" size="70"/>
          </h:panelGroup>
          <script>
            setEnabled( 'search:healthInsurance', ${userBean.searchHealthInsuranceValid} )
          </script>

        
      </td>
    </tr>
                        
      <%-- Field: notes --%>
    <tr>
      <td class="searchLabel">${msg['user.notes']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="notes" />
            <h:selectBooleanCheckbox id="notesValid" value="#{userBean.searchNotesValid}" 
                                      onclick="setEnabled('search:notes',this.checked)"/>
            <h:inputText id="notes" value="#{userBean.searchNotes}" size="70"/>
          </h:panelGroup>
          <script>
            setEnabled( 'search:notes', ${userBean.searchNotesValid} )
          </script>

        
      </td>
    </tr>
                        
      <%-- Ignored field: photo --%>

                        
      <%-- Field: endTestPeriodDate --%>
    <tr>
      <td class="searchLabel">${msg['user.endTestPeriodDate']}:</td>
      <td class="searchFieldCell">

        
                    
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="startEndTestPeriodDate" />
            <h:selectBooleanCheckbox id="startEndTestPeriodDateValid" value="#{userBean.searchStartEndTestPeriodDateValid}" 
                                      onclick="setEnabled('search:startEndTestPeriodDate',this.checked)"/>
            <t:inputCalendar id="startEndTestPeriodDate" value="#{userBean.searchStartEndTestPeriodDate}"
                             renderAsPopup="true" popupDateFormat="d/MM/yyyy" renderPopupButtonAsImage="true" 
                             popupTodayString="#{msg['calendar.today']}" popupWeekString="#{msg['calendar.week']}"
                             onchange="setEnabled('search:startEndTestPeriodDate',true);setChecked('search:startEndTestPeriodDateValid',true);"
                             >
				<f:validator validatorId="autentia.dateValidator"/>
			</t:inputCalendar>
          </h:panelGroup>
          -
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="endEndTestPeriodDate" />
            <h:selectBooleanCheckbox id="endEndTestPeriodDateValid" value="#{userBean.searchEndEndTestPeriodDateValid}" 
                                      onclick="setEnabled('search:endEndTestPeriodDate',this.checked)"/>
            <t:inputCalendar id="endEndTestPeriodDate" value="#{userBean.searchEndEndTestPeriodDate}"
                             renderAsPopup="true" popupDateFormat="d/MM/yyyy" renderPopupButtonAsImage="true" 
                             popupTodayString="#{msg['calendar.today']}" popupWeekString="#{msg['calendar.week']}"
                             onchange="setEnabled('search:endEndTestPeriodDate',true);setChecked('search:endEndTestPeriodDateValid',true);"
                             >
				<f:validator validatorId="autentia.dateValidator"/>
			</t:inputCalendar>
          </h:panelGroup>
          <script>
            setEnabled( 'search:startEndTestPeriodDate', ${userBean.searchStartEndTestPeriodDateValid} )
            setEnabled( 'search:endEndTestPeriodDate', ${userBean.searchEndEndTestPeriodDateValid} )
          </script>

        
      </td>
    </tr>
                        
      <%-- Field: endContractDate --%>
    <tr>
      <td class="searchLabel">${msg['user.endContractDate']}:</td>
      <td class="searchFieldCell">

        
                    
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="startEndContractDate" />
            <h:selectBooleanCheckbox id="startEndContractDateValid" value="#{userBean.searchStartEndContractDateValid}" 
                                      onclick="setEnabled('search:startEndContractDate',this.checked)"/>
            <t:inputCalendar id="startEndContractDate" value="#{userBean.searchStartEndContractDate}"
                             renderAsPopup="true" popupDateFormat="d/MM/yyyy" renderPopupButtonAsImage="true" 
                             popupTodayString="#{msg['calendar.today']}" popupWeekString="#{msg['calendar.week']}"
                             onchange="setEnabled('search:startEndContractDate',true);setChecked('search:startEndContractDateValid',true);"
                             >
				<f:validator validatorId="autentia.dateValidator"/>
			</t:inputCalendar>
          </h:panelGroup>
          -
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="endEndContractDate" />
            <h:selectBooleanCheckbox id="endEndContractDateValid" value="#{userBean.searchEndEndContractDateValid}" 
                                      onclick="setEnabled('search:endEndContractDate',this.checked)"/>
            <t:inputCalendar id="endEndContractDate" value="#{userBean.searchEndEndContractDate}"
                             renderAsPopup="true" popupDateFormat="d/MM/yyyy" renderPopupButtonAsImage="true" 
                             popupTodayString="#{msg['calendar.today']}" popupWeekString="#{msg['calendar.week']}"
                             onchange="setEnabled('search:endEndContractDate',true);setChecked('search:endEndContractDateValid',true);"
                             >
				<f:validator validatorId="autentia.dateValidator"/>
			</t:inputCalendar>
          </h:panelGroup>
          <script>
            setEnabled( 'search:startEndContractDate', ${userBean.searchStartEndContractDateValid} )
            setEnabled( 'search:endEndContractDate', ${userBean.searchEndEndContractDateValid} )
          </script>

        
      </td>
    </tr>
                        
      <%-- Ignored field: dayDuration --%>

                        
      <%-- Ignored field: contractObservations --%>

                        
      <%-- Ignored field: insertDate --%>

                        
      <%-- Ignored field: updateDate --%>

                                  
      <%-- Field: role --%>
    <tr>
      <td class="searchLabel">${msg['user.role']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="role" />
            <h:selectBooleanCheckbox id="roleValid" value="#{userBean.searchRoleValid}" 
                                      onclick="setEnabled('search:role',this.checked)"/>
            <h:selectOneMenu id="role" value="#{userBean.searchRole}" onclick="setEnabled('search:role',true)">
              <f:selectItems value="#{userBean.roles}" />
              <f:converter converterId="autentia.EntityConverter"/>
            </h:selectOneMenu>
          </h:panelGroup>
          <script>
            setEnabled( 'search:role', ${userBean.searchRoleValid} )
          </script>

        
      </td>
    </tr>
                        
      <%-- Field: category --%>
    <tr>
      <td class="searchLabel">${msg['user.category']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="category" />
            <h:selectBooleanCheckbox id="categoryValid" value="#{userBean.searchCategoryValid}" 
                                      onclick="setEnabled('search:category',this.checked)"/>
            <h:selectOneMenu id="category" value="#{userBean.searchCategory}" onclick="setEnabled('search:category',true)">
              <f:selectItems value="#{userBean.categorys}" />
              <f:converter converterId="autentia.EntityConverter"/>
            </h:selectOneMenu>
          </h:panelGroup>
          <script>
            setEnabled( 'search:category', ${userBean.searchCategoryValid} )
          </script>

        
      </td>
    </tr>
                        
      <%-- Field: province --%>
    <tr>
      <td class="searchLabel">${msg['user.province']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="province" />
            <h:selectBooleanCheckbox id="provinceValid" value="#{userBean.searchProvinceValid}" 
                                      onclick="setEnabled('search:province',this.checked)"/>
            <h:selectOneMenu id="province" value="#{userBean.searchProvince}" onclick="setEnabled('search:province',true)">
              <f:selectItems value="#{userBean.provinces}" />
              <f:converter converterId="autentia.EntityConverter"/>
            </h:selectOneMenu>
          </h:panelGroup>
          <script>
            setEnabled( 'search:province', ${userBean.searchProvinceValid} )
          </script>

        
      </td>
    </tr>
                        
      <%-- Ignored field: documentCategory --%>

                        
      <%-- Field: department --%>
    <tr>
      <td class="searchLabel">${msg['user.department']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="department" />
            <h:selectBooleanCheckbox id="departmentValid" value="#{userBean.searchDepartmentValid}" 
                                      onclick="setEnabled('search:department',this.checked)"/>
            <h:selectOneMenu id="department" value="#{userBean.searchDepartment}" onclick="setEnabled('search:department',true)">
              <f:selectItems value="#{userBean.departments}" />
              <f:converter converterId="autentia.EntityConverter"/>
            </h:selectOneMenu>
          </h:panelGroup>
          <script>
            setEnabled( 'search:department', ${userBean.searchDepartmentValid} )
          </script>

        
      </td>
    </tr>
                        
      <%-- Field: contractType --%>
    <tr>
      <td class="searchLabel">${msg['user.contractType']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="contractType" />
            <h:selectBooleanCheckbox id="contractTypeValid" value="#{userBean.searchContractTypeValid}" 
                                      onclick="setEnabled('search:contractType',this.checked)"/>
            <h:selectOneMenu id="contractType" value="#{userBean.searchContractType}" onclick="setEnabled('search:contractType',true)">
              <f:selectItems value="#{userBean.contractTypes}" />
              <f:converter converterId="autentia.EntityConverter"/>
            </h:selectOneMenu>
          </h:panelGroup>
          <script>
            setEnabled( 'search:contractType', ${userBean.searchContractTypeValid} )
          </script>

        
      </td>
    </tr>
                        
      <%-- Field: agreement --%>
    <tr>
      <td class="searchLabel">${msg['user.agreement']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="agreement" />
            <h:selectBooleanCheckbox id="agreementValid" value="#{userBean.searchAgreementValid}" 
                                      onclick="setEnabled('search:agreement',this.checked)"/>
            <h:selectOneMenu id="agreement" value="#{userBean.searchAgreement}" onclick="setEnabled('search:agreement',true)">
              <f:selectItems value="#{userBean.agreements}" />
              <f:converter converterId="autentia.EntityConverter"/>
            </h:selectOneMenu>
          </h:panelGroup>
          <script>
            setEnabled( 'search:agreement', ${userBean.searchAgreementValid} )
          </script>

        
      </td>
    </tr>
                                
        </table>
        
      </h:form>
    </f:view>
    
  </body>
</html>  		
