<%--

    TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.
    Copyright (C) 2007 Autentia Real Bussiness Solution S.L.

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

--%>

<%@page language="java" contentType="text/html; charset=UTF-8"%>

<%@include file="/inc/tlibs.jsp" %>

<html>
  <head>
    <%@include file="/inc/uiCore.jsp" %>
  </head>	
  <body>
    
    <!-- editOffer.jsp: generated by stajanov code generator -->
    <f:loadBundle basename="com.autentia.tnt.resources.messages" var="msg" />
    <i:location place="detailOffer" msg="${msg}"/> 
    
    <f:view>
      <%@include file="/inc/header.jsp" %>
      <h:form id="offer" enctype="multipart/form-data">
        
        <%-- Header --%>
        <i:titleBar name="${offerBean.title}" msg="${msg}">
          <t:commandLink action="#{offerBean.edit}" immediate="true" rendered="#{offerBean.editAvailable}">
            <f:param name="rowid" value="#{offerBean.id}" />
            <h:graphicImage title="#{msg.entityActions_edit}"  value="/img/edit.gif" styleClass="cmdImg" />
          </t:commandLink>
          <h:commandLink action="#{offerBean.delete}" rendered="#{offerBean.deleteAvailable}" onclick="if( !confirm('#{msg['question.confirmDelete']}') ) return false;">
            <h:graphicImage title="#{msg.entityActions_delete}"  value="/img/delete.gif" styleClass="titleImg" />
          </h:commandLink>
          <h:commandLink action="#{offerBean.list}" immediate="true">
            <h:graphicImage title="#{msg.entityActions_back}"  value="/img/back.gif" styleClass="titleImg" />
          </h:commandLink>
        </i:titleBar>


        <%-- Detail form --%>
        <table class="detailTable" cellpadding="0" cellspacing="0">

            
    
  
  
      <%-- Ignored field: id --%>
  
                            
    
  
  
      <%-- Field: number --%>
    <tr>
	<td class="detailLabelRW">${msg['offer.number']}:</td>
	<td class="detailFieldCell">
         	       <h:outputText value="#{offerBean.number}" />
 	      </td>
    </tr>
                            
    
  
  
      <%-- Field: title --%>
    <tr>
	<td class="detailLabelRW">${msg['offer.title']}:</td>
	<td class="detailFieldCell">
         	       <h:outputText value="#{offerBean.title}" />
 	      </td>
    </tr>
                            
    
  
  
      <%-- Field: description --%>
    <tr>
	<td class="detailLabelRW">${msg['offer.description']}:</td>
	<td class="detailFieldCell">
         	       <h:outputText value="#{offerBean.description}" />
 	      </td>
    </tr>
                            
    
  
  
      <%-- Field: observations --%>
    <tr>
	<td class="detailLabelRW">${msg['offer.observations']}:</td>
	<td class="detailFieldCell">
         	       <h:outputText value="#{offerBean.observations}" />
 	      </td>
    </tr>
                            
    
  
  
      <%-- Field: creationDate --%>
    <tr>
	<td class="detailLabelRW">${msg['offer.creationDate']}:</td>
	<td class="detailFieldCell">
         	    	<h:outputText value="#{offerBean.creationDate}" converter="autentia.dateConverter" />
 	          </td>
    </tr>
                            
    
  
  
      <%-- Field: validityDate --%>
    <tr>
	<td class="detailLabelRW">${msg['offer.validityDate']}:</td>
	<td class="detailFieldCell">
         	    	<h:outputText value="#{offerBean.validityDate}" converter="autentia.dateConverter" />
 	          </td>
    </tr>
                            
    
  
  
      <%-- Field: maturityDate --%>
    <tr>
	<td class="detailLabelRW">${msg['offer.maturityDate']}:</td>
	<td class="detailFieldCell">
         	    	<h:outputText value="#{offerBean.maturityDate}" converter="autentia.dateConverter" />
 	          </td>
    </tr>
                            
    
  
  
      <%-- Field: offerState --%>
    <tr>
	<td class="detailLabelRW">${msg['offer.offerState']}:</td>
	<td class="detailFieldCell">
                	<h:outputText value="#{offerBean.offerStateFormatted}" />
              </td>
    </tr>
                            
    
  
  
      <%-- Field: offerPotential --%>
    <tr>
	<td class="detailLabelRW">${msg['offer.offerPotential']}:</td>
	<td class="detailFieldCell">
                	<h:outputText value="#{offerBean.offerPotentialFormatted}" />
              </td>
    </tr>
                            
    
  
  
      <%-- Field: totalRoles --%>
    <tr>
	<td class="detailLabelRW">${msg['offer.totalRoles']}:</td>
	<td class="detailFieldCell">
         	       <h:outputText value="#{offerBean.totalRoles}" />
 	      </td>
    </tr>
                            
    
  
  
      <%-- Field: totalCosts --%>
    <tr>
	<td class="detailLabelRW">${msg['offer.totalCosts']}:</td>
	<td class="detailFieldCell">
         	       <h:outputText value="#{offerBean.totalCosts}" />
 	      </td>
    </tr>
                            
    
  
  
      <%-- Field: total --%>
    <tr>
	<td class="detailLabelRW">${msg['offer.total']}:</td>
	<td class="detailFieldCell">
         	       <h:outputText value="#{offerBean.total}" />
 	      </td>
    </tr>
                            
    
  
  
      <%-- Ignored field: ownerId --%>
  
                            
    
  
  
      <%-- Ignored field: departmentId --%>
  
                            
    
  
  
      <%-- Ignored field: insertDate --%>
  
                            
    
  
  
      <%-- Ignored field: updateDate --%>
  
                                        
    
  
  
      <%-- Field: user --%>
    <tr>
	<td class="detailLabelRW">${msg['offer.user']}:</td>
	<td class="detailFieldCell">
         	    	<h:outputText value="#{offerBean.user.name}"/>
 	          </td>
    </tr>
                            
    
  
  
      <%-- Field: organization --%>
    <tr>
	<td class="detailLabelRW">${msg['offer.organization']}:</td>
	<td class="detailFieldCell">
         	    	<h:outputText value="#{offerBean.organization.name}"/>
 	          </td>
    </tr>
                            
    
  
  
      <%-- Field: contact --%>
    <tr>
	<td class="detailLabelRW">${msg['offer.contact']}:</td>
	<td class="detailFieldCell">
         	    	<h:outputText value="#{offerBean.contact.name}"/>
 	          </td>
    </tr>
                            
    
  
  
      <%-- Field: offerRejectReason --%>
    <tr>
	<td class="detailLabelRW">${msg['offer.offerRejectReason']}:</td>
	<td class="detailFieldCell">
         	    	<h:outputText value="#{offerBean.offerRejectReason.title}"/>
 	          </td>
    </tr>
                                                    
    
  
  
      <%-- Field: interactions --%>
    <tr>
	<td class="detailLabelRW">${msg['offer.interactions']}:</td>
	<td class="detailFieldCell">
                  			        <%@include file="inlineDetailInteraction.jsp"%>
          	 	          </td>
    </tr>
                            
    
  
  
      <%-- Field: roles --%>
    <tr>
	<td class="detailLabelRW">${msg['offer.roles']}:</td>
	<td class="detailFieldCell">
                  			        <%@include file="inlineDetailOfferRole.jsp"%>
          	 	          </td>
    </tr>
                            
    
  
  
      <%-- Field: costs --%>
    <tr>
	<td class="detailLabelRW">${msg['offer.costs']}:</td>
	<td class="detailFieldCell">
                  			        <%@include file="inlineDetailOfferCost.jsp"%>
          	 	          </td>
    </tr>
              
        </table>

      </h:form>
    </f:view>
    
  </body>
</html>  		

<%-- Offer - generated by stajanov (do not edit/delete) --%>
