<%--

    TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.
    Copyright (C) 2007 Autentia Real Bussiness Solution S.L.

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

--%>

<%@page language="java" contentType="text/html; charset=UTF-8"%>

<%@include file="/inc/tlibs.jsp" %>

<html>
  <head>
    <%@include file="/inc/uiCore.jsp" %>
     <script type="text/javascript">
     function openPDF(id,idOrg,showSubreportRole,showSubreportCost) {
         openReportParameters("document/oferta.pdf","?offerId="+id+"&idOrg="+idOrg+"&showSubreportRole="+showSubreportRole+"&showSubreportCost="+showSubreportCost+"&SUBREPORT_BILLHEADER=factura_subreport&SUBREPORT_BILLFOOTERINFO=footerInfo_subreport&SUBREPORT_OFFERCOST=subreport_offerCost&SUBREPORT_OFFERROLE=subreport_offerRole&SUBREPORT_OFFERHEADER=factura_subreport&SUBREPORT_IVAAPLICADO_OFERTA=iva_aplicado_oferta","");
     }
    </script>
  </head>	
  <body>
    
    <!-- editOfferRejectReason.jsp: generated by stajanov code generator -->
    <f:loadBundle basename="com.autentia.tnt.resources.messages" var="msg" />
    <i:location place="editOffer" msg="${msg}"/> 
    
    <f:view>
        <%@include file="/inc/header.jsp" %>
      <h:form id="offer" enctype="multipart/form-data">
        
        <%-- Header --%>
        <i:titleBar name="${offerBean.title}" msg="${msg}">
          <h:commandLink action="#{offerBean.save}" onclick="if(!askSave('#{offerBean.id}','#{msg['question.confirmSave']}')) return false;">
            <h:graphicImage title="#{msg.entityActions_save}"  value="/img/save.gif" styleClass="titleImg" />
          </h:commandLink>
          <h:commandLink action="#{offerBean.delete}" onclick="if( !confirm('#{msg['question.confirmDelete']}') ) return false;"
            rendered="#{offerBean.deleteAvailable}">
            <h:graphicImage title="#{msg.entityActions_delete}"  value="/img/delete.gif" styleClass="titleImg" />
          </h:commandLink>
          <h:commandLink action="#{offerBean.list}" immediate="true">
            <h:graphicImage title="#{msg.entityActions_back}"  value="/img/back.gif" styleClass="titleImg" />
          </h:commandLink>
          <t:commandLink rendered="#{offerBean.puedoCrearProyecto}" action="#{projectBean.copy}" immediate="true">
              <f:param name="rowid" value="#{offerBean.id}" />
              <h:outputText value="#{msg['offer.copy']}" />
          </t:commandLink>
          <h:commandLink rendered="#{offerBean.puedoImprimirOferta}" action="#" onclick="openPDF('#{offerBean.id}','#{offerBean.idSelectedOrganization}','#{offerBean.showSubreportRole}','#{offerBean.showSubreportCost}')" immediate="true">
            <h:graphicImage title="#{msg['offer.print']}" value="/img/page_white_acrobat.png" styleClass="titleImg" />
          </h:commandLink>
		  <h:commandLink action="#{offerBean.convertFromOfferToBill}" onclick="if( !confirm('#{msg['question.confirmBillConversion']}') ) return false;" immediate="true" rendered="#{offerBean.savedEntity}">
            <h:graphicImage title="#{msg['offer.bill']}" value="/img/arrow_branch.png" styleClass="titleImg" />
          </h:commandLink>
		  <h:commandLink action="#{offerBean.duplicateOffer}" onclick="if( !confirm('#{msg['question.confirmOfferDuplication']}') ) return false;" immediate="true" rendered="#{offerBean.savedEntity}">
            <h:graphicImage title="#{msg['offer.duplicate']}" value="/img/arrow_divide.png" styleClass="titleImg" />
          </h:commandLink>
        </i:titleBar>     
        
        <%-- Edition form --%>
        <table class="editTable" cellpadding="0" cellspacing="0">



<%-- Offer - generated by stajanov (do not edit/delete) --%>







              
  
      <%-- Ignored field: id --%>
  
                              
     
     <%-- Field: number --%>
          <tr>
            <td class="editLabelRW">*${msg['offer.number']}:</td>
            <td class="editFieldCell">
              <h:panelGroup>
                <h:message styleClass="error" showSummary="true" showDetail="false" for="number" />
                <h:inputText id="number" value="#{offerBean.number}" required="true" styleClass="requiredFieldClass" maxlength="64"/>
              </h:panelGroup>
            </td>
          </tr>
          
     
     <%-- Field: organization --%>
    <tr>
    	    		<td class="editLabelRW">*${msg['offer.organization']}:</td>
    	      
      <td class="editFieldCell">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="organization" />
            <h:selectOneMenu id="organization" value="#{offerBean.organization}" immediate="true" onchange="submit()"
                     valueChangeListener="#{offerBean.onSelectedOrganizationChanged}">
              <f:selectItems value="#{offerBean.organizations}" />
              <f:converter converterId="autentia.EntityConverter"/>
            </h:selectOneMenu>
          </h:panelGroup>

              </td>
    </tr>
                              
    
      <%-- Field: contact --%>
    <tr>
    	    		<td class="editLabelRW">*${msg['offer.contact']}:</td>
    	      
      <td class="editFieldCell">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="contact" />
            <h:selectOneMenu id="contact" value="#{offerBean.contact}"  required="true" styleClass="requiredFieldClass">
             <f:selectItems value="#{offerBean.contactsBySelectedOrganization}" />
              <f:converter converterId="autentia.EntityConverter"/>
            </h:selectOneMenu>
          </h:panelGroup>

              </td>
    </tr>
    
    
      <%-- Field: title --%>
    <tr>
    	    		<td class="editLabelRW">*${msg['offer.title']}:</td>
    	      
      <td class="editFieldCell">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="title" />
                		<h:inputText id="title" value="#{offerBean.title}" maxlength="128" required="true" styleClass="requiredFieldClass"/>
    	              </h:panelGroup>

              </td>
    </tr>
                              
  
      <%-- Field: description --%>
    <tr>
    	    		<td class="editLabelRW">${msg['offer.description']}:</td>
    	      
      <td class="editFieldCell">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="description" />
            <h:inputTextarea id="description" value="#{offerBean.description}" rows="7" cols="68" />
            
          </h:panelGroup>

              </td>
    </tr>
                              
  
      <%-- Field: creationDate --%>
    <tr>
    	    		<td class="editLabelRW">${msg['offer.creationDate']}:</td>
    	      
      <td class="editFieldCell">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="creationDate" />
            <t:inputCalendar id="creationDate" value="#{offerBean.creationDate}" styleClass="requiredFieldClass" required="true"
                             renderAsPopup="true" popupDateFormat="d/MM/yyyy" renderPopupButtonAsImage="true" 
                             popupTodayString="#{msg['calendar.today']}" popupWeekString="#{msg['calendar.week']}"
                             >
				<f:validator validatorId="autentia.dateValidator"/>
			</t:inputCalendar>
          </h:panelGroup>

              </td>
    </tr>
                              
    
      <%-- Field: validityDate --%>
    <tr>
    	    		<td class="editLabelRW">*${msg['offer.validityDate']}:</td>
    	      
      <td class="editFieldCell">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="validityDate" />
            <t:inputCalendar id="validityDate" value="#{offerBean.validityDate}" styleClass="requiredFieldClass" required="true"
                             renderAsPopup="true" popupDateFormat="d/MM/yyyy" renderPopupButtonAsImage="true" 
                             popupTodayString="#{msg['calendar.today']}" popupWeekString="#{msg['calendar.week']}"
                             >
				<f:validator validatorId="autentia.dateValidator"/>
			</t:inputCalendar>
          </h:panelGroup>

              </td>
    </tr>
    
    <%-- Field: maturityDate --%>
    <tr>
    	    		<td class="editLabelRW">${msg['offer.maturityDate']}:</td>
    	      
      <td class="editFieldCell">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="maturityDate" />
            <t:inputCalendar id="maturityDate" value="#{offerBean.maturityDate}" 
                             renderAsPopup="true" popupDateFormat="d/MM/yyyy" renderPopupButtonAsImage="true" 
                             popupTodayString="#{msg['calendar.today']}" popupWeekString="#{msg['calendar.week']}"
                             >
				<f:validator validatorId="autentia.dateValidator"/>
			</t:inputCalendar>
          </h:panelGroup>

              </td>
    </tr>
                              
    
      <%-- Field: offerState --%>
    <tr>
    	    		<td class="editLabelRW">*${msg['offer.offerState']}:</td>
    	      
      <td class="editFieldCell">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="offerState" />
            <h:selectOneMenu id="offerState" value="#{offerBean.offerState}"  required="true" styleClass="requiredFieldClass">
              <f:converter converterId="autentia.EnumConverter"/>
              <f:selectItems value="#{offerBean.offerStates}" />
            </h:selectOneMenu>
          </h:panelGroup>

              </td>
    </tr>
                              
  <%-- Field: offerPotential --%>
    <tr>
    	    		<td class="editLabelRW">*${msg['offer.offerPotential']}:</td>
    	      
      <td class="editFieldCell">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="offerPotential" />
            <h:selectOneMenu id="offerPotential" value="#{offerBean.offerPotential}"  required="true" styleClass="requiredFieldClass">
              <f:converter converterId="autentia.EnumConverter"/>
              <f:selectItems value="#{offerBean.offerPotentials}" />
            </h:selectOneMenu>
          </h:panelGroup>

              </td>
    </tr>
      <%-- Ignored field: ownerId --%>
  
                              
  
      <%-- Ignored field: departmentId --%>
  
                              
  
      <%-- Ignored field: insertDate --%>
  
                              
  
      <%-- Ignored field: updateDate --%>
  
                                          
  
      <%-- Field: user --%>
    <tr>
    	    		<td class="editLabelRW">${msg['offer.user']}:</td>
    	      
      <td class="editFieldCell">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="user" />
            <h:selectOneMenu id="user" value="#{offerBean.user}" disabled="true">
              <f:selectItems value="#{offerBean.users}" />
              <f:converter converterId="autentia.EntityConverter"/>
            </h:selectOneMenu>
          </h:panelGroup>

              </td>
    </tr>
                              
    
     
                              
  
      <%-- Field: offerRejectReason --%>
    <tr>
    	    		<td class="editLabelRW">${msg['offer.offerRejectReason']}:</td>
    	      
      <td class="editFieldCell">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="offerRejectReason" />
            <h:selectOneMenu id="offerRejectReason" value="#{offerBean.offerRejectReason}" >
              <f:selectItems value="#{offerBean.offerRejectReasons}" />
              <f:converter converterId="autentia.EntityConverter"/>
            </h:selectOneMenu>
          </h:panelGroup>

              </td>
    </tr>
     <%-- Field: interactions --%>
                                                 
  	<c:if test="${offerBean.interactionsAvailable}">     
    <tr>
    	    		<td class="editLabelRW">${msg['offer.interactions']}:</td>
    	      
      <td class="editFieldCell">
		
                              <%@include file="inlineDetailInteraction.jsp"%>
          
              </td>
    </tr>
    </c:if>
    
     <%-- Field: roles --%>
    <tr>
      <td class="editLabelRW">${msg['offer.roles']}:</td>
      <td class="editFieldCell">
            <%@include file="inlineEditOfferRole.jsp"%>
      </td>
    </tr>
     
    <%-- Base imponible (Roles) --%>
    <tr>
      <td class="editLabelRW">${msg['offer.taxBaseRoles']}:</td>
    	      
      <td class="editFieldCell">
		 <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="taxBaseRoles" />
            <h:inputText id="taxBaseRoles" value="#{offerBean.taxBaseRoles}" size="10" disabled="true"/>
    	 </h:panelGroup>
      </td>
    </tr>
    
    <%-- IVA (Roles) --%>
    <tr>
      <td class="editLabelRW">${msg['offer.ivaRoles']}:</td>
    	      
      <td class="editFieldCell">
	 	<h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="ivaRoles" />
            <h:inputText id="ivaRoles" value="#{offerBean.ivaRoles}" size="10" disabled="true"/>
        </h:panelGroup>
      </td>
    </tr>
    
    <%-- Field: totalRoles --%>
    <tr>
      <td class="editLabelRW">${msg['offer.totalRoles']}:</td>
    	      
      <td class="editFieldCell">
		 <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="totalRoles" />
            <h:inputText id="totalRoles" value="#{offerBean.totalRoles}" size="10" disabled="true"/>
    	 </h:panelGroup>
      </td>
    </tr>

      <%-- Field: costs --%>
    <tr>
      <td class="editLabelRW">${msg['offer.costs']}:</td>
    	      
      <td class="editFieldCell">
           <%@include file="inlineEditOfferCost.jsp"%>
      </td>
    </tr>
                        
  
  	<%-- Base imponible (Costes) --%>
    <tr>
      <td class="editLabelRW">${msg['offer.taxBaseCosts']}:</td>
    	      
      <td class="editFieldCell">
		 <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="taxBaseCosts" />
            <h:inputText id="taxBaseCosts" value="#{offerBean.taxBaseCosts}" size="10" disabled="true"/>
    	 </h:panelGroup>
      </td>
    </tr>
    
    <%-- IVA (Costes) --%>
    <tr>
      <td class="editLabelRW">${msg['offer.ivaCosts']}:</td>
    	      
      <td class="editFieldCell">
		 <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="ivaCosts" />
            <h:inputText id="ivaCosts" value="#{offerBean.ivaCosts}" size="10" disabled="true"/>
      	 </h:panelGroup>
      </td>
    </tr>
    
    <%-- Field: totalCosts --%>
    <tr>
      <td class="editLabelRW">${msg['offer.totalCosts']}:</td>
    	      
      <td class="editFieldCell">
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="totalCosts" />
        	<h:inputText id="totalCosts" value="#{offerBean.totalCosts}" size="10" disabled="true"/>
          </h:panelGroup>
      </td>
    </tr>
    
    <tr>
      <td class="editLabelRW">${msg['offer.showIva']}:</td>
      
      <td class="editFieldCell">
          <h:panelGroup>
         	 <h:selectBooleanCheckbox id="showIva" value="#{offerBean.showIvaIntoReport}" /> 
          </h:panelGroup>
      </td>
    </tr>
                              
  
      <%-- Field: total --%>
    <tr>
    	    		<td class="editLabelRW">${msg['offer.total']}:</td>
    	      
      <td class="editFieldCell">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="total" />
                			<h:inputText id="total" value="#{offerBean.total}" size="10" disabled="true"/>
    		          </h:panelGroup>

              </td>
    </tr>
              
             
       <%-- Field: observations --%>
    <tr>
    	    		<td class="editLabelRW">${msg['offer.observations']}:</td>
    	      
      <td class="editFieldCell">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="observations" />
            <h:inputTextarea id="observations" value="#{offerBean.observations}" rows="7" cols="68"/>
          </h:panelGroup>

              </td>
    </tr>
              

<%-- Offer - generated by stajanov (do not edit/delete) --%>
</table>
        
      </h:form>
    </f:view>
    
  </body>
</html>  	
