<%--

    TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.
    Copyright (C) 2007 Autentia Real Bussiness Solution S.L.

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

--%>

<%@page language="java" contentType="text/html; charset=UTF-8"%>

<%@include file="/inc/tlibs.jsp"%>
<html>
<head>
<%@include file="/inc/uiCore.jsp"%>

</head>
<body>
<!-- editContact.jsp: generated by stajanov code generator -->
<f:loadBundle basename="com.autentia.tnt.resources.messages" var="msg" />
<i:location place="editPosition" msg="${msg}" />

<f:view>

	<%@include file="/inc/header.jsp"%>
	<h:form id="position" enctype="multipart/form-data">

		<%-- Header --%>
		<i:titleBar name="${positionBean.name}" msg="${msg}">
			<h:commandLink action="#{positionBean.save}"
				onclick="if(!askSave('#{positionBean.id}','#{msg['question.confirmSave']}')) return false;">
				<h:graphicImage value="/img/save.gif" styleClass="titleImg" />
			</h:commandLink>
			<h:commandLink action="#{positionBean.delete}"
				rendered="#{positionBean.deleteAvailable}"
				onclick="return confirm('#{msg['question.confirmDelete']}');">
				<h:graphicImage value="/img/delete.gif" styleClass="titleImg" />
			</h:commandLink>
			<h:commandLink action="#{positionBean.list}" immediate="true">
				<h:graphicImage title="#{msg.entityActions_back}"
					value="/img/back.gif" styleClass="titleImg" />
			</h:commandLink>
		</i:titleBar>

		<h:messages errorClass="error" infoClass="info" warnClass="warning"
			id="errorMessage" showSummary="true" showDetail="false"
			globalOnly="true" />

		<%-- Edition form --%>
		<table class="editTable" cellpadding="0" cellspacing="0">

			<%-- Position - generated by stajanov (do not edit/delete) --%>


			<%-- Field: name --%>
			<tr>
				<td class="editLabelRW">*${msg['position.name']}:</td>

				<td class="editFieldCell"><h:panelGroup>
					<h:message styleClass="error" showSummary="true" showDetail="false"
						for="name" />
					<h:inputText id="name" value="#{positionBean.name}" required="true" styleClass="requiredFieldClass"/>
				</h:panelGroup></td>
			</tr>


			<%-- Field: description --%>
			<tr>
				<td class="editLabelRW">${msg['position.description']}:</td>

				<td class="editFieldCell"><h:panelGroup>
					<h:message styleClass="error" showSummary="true" showDetail="false"
						for="description" />
					<h:inputText id="description" value="#{positionBean.description}" />
				</h:panelGroup></td>
			</tr>

		 	<%-- Field: email --%>
		    <tr>
		    	    		<td class="editLabelRW">${msg['position.email']}:</td>
		    	      
		      <td class="editFieldCell">
		
		                  <h:panelGroup>
		            <h:message styleClass="error" showSummary="true" showDetail="false" for="email" />
		                		<h:inputText id="email" value="#{positionBean.email}" size="70" maxlength="128"/>
		    	              </h:panelGroup>
		
		              </td>
		    </tr>
		                                  
		    
		  
		      <%-- Field: phone --%>
		    <tr>
		    	    		<td class="editLabelRW">${msg['position.phone']}:</td>
		    	      
		      <td class="editFieldCell">
		
		                  <h:panelGroup>
		            <h:message styleClass="error" showSummary="true" showDetail="false" for="phone" />
		                		<h:inputText id="phone" value="#{positionBean.phone}" maxlength="15"/>
		    	              </h:panelGroup>
		
		              </td>
		    </tr>
		                                  
		     
		      <%-- Field: fax --%>
		    <tr>
		    	    		<td class="editLabelRW">${msg['position.fax']}:</td>
		    	      
		      <td class="editFieldCell">
		
		                  <h:panelGroup>
		            <h:message styleClass="error" showSummary="true" showDetail="false" for="fax" />
		                		<h:inputText id="fax" value="#{positionBean.fax}" maxlength="15"/>
		    	              </h:panelGroup>
		
		              </td>
		    </tr>
		
		      <%-- Field: country --%>
		    <tr>
		    	    		<td class="editLabelRW">${msg['position.country']}:</td>
		    	      
		      <td class="editFieldCell">
		
		                  <h:panelGroup>
		            <h:message styleClass="error" showSummary="true" showDetail="false" for="country" />
		                		<h:inputText id="country" value="#{positionBean.country}" maxlength="128"/>
		    	              </h:panelGroup>
		
		              </td>
		    </tr>
		    
		      <%-- Field: province --%>
		      
		    <tr>
		    	    		<td class="editLabelRW">${msg['position.province']}:</td>
		    	      
		      <td class="editFieldCell">
		
		                  <h:panelGroup>
		            <h:message styleClass="error" showSummary="true" showDetail="false" for="province" />
		            <h:selectOneMenu id="province" value="#{positionBean.province}" >
		              <f:selectItems value="#{positionBean.provinces}" />
		              <f:converter converterId="autentia.EntityConverter"/>
		            </h:selectOneMenu>
		          </h:panelGroup>
		
		              </td>
		    </tr>    
		    
			<%-- Field: city --%>
		    <tr>
		    	    		<td class="editLabelRW">${msg['position.city']}:</td>
		    	      
		      <td class="editFieldCell">
		
		                  <h:panelGroup>
		            <h:message styleClass="error" showSummary="true" showDetail="false" for="city" />
		                		<h:inputText id="city" value="#{positionBean.city}"/>
		    	              </h:panelGroup>
		
		              </td>
		    </tr>
		    
		      <%-- Field: postalCode --%>
		    <tr>
		    	    		<td class="editLabelRW">${msg['position.postalCode']}:</td>
		    	      
		      <td class="editFieldCell">
		
		                  <h:panelGroup>
		            <h:message styleClass="error" showSummary="true" showDetail="false" for="postalCode" />
		                		<h:inputText id="postalCode" value="#{positionBean.postalCode}" size="10" maxlength="5"/>
		    	              </h:panelGroup>
		
		              </td>
		    </tr>
		
		      <%-- Field: address --%>
		    <tr>
		    	    		<td class="editLabelRW">${msg['position.address']}:</td>
		    	      
		      <td class="editFieldCell">
		
		                  <h:panelGroup>
		            <h:message styleClass="error" showSummary="true" showDetail="false" for="address" />
		                		<h:inputText id="address" value="#{positionBean.address}" size="70" maxlength="128"/>
		    	              </h:panelGroup>
		
		              </td>
		    </tr>



			<%-- Field: tags --%>
		    <tr>
				<td class="editLabelRW">${msg['position.tags']}:</td>
				<td class="editFieldCell" colspan="2">
					<h:panelGroup>
						<h:panelGroup rendered="#{positionBean.areTagsToSelect}">
							<h:selectOneMenu id="tagsList" value="#{positionBean.selectedTag}" >
								<f:selectItems value="#{positionBean.allTags}" />
								<f:converter converterId="autentia.EntityConverter"/>
								<f:attribute name="com.autentia.tnt.converter.EntityConverter.valueClass" 
			                        	  value="com.autentia.tnt.businessobject.Tag"/> 
							</h:selectOneMenu>
							<h:commandLink action="#{positionBean.addTag}">
								<h:graphicImage value="/img/add.png" styleClass="titleImg" />
							</h:commandLink>
					</h:panelGroup>
					<h:panelGroup rendered="#{!positionBean.areTagsToSelect}">
						<h:graphicImage value="/img/updated.gif" styleClass="titleImg" />
						<h:outputText value="#{msg['position.warn.noTags']}"  />
					</h:panelGroup>
					<h:panelGroup rendered="#{positionBean.areTagsSelected}">
							<h:message styleClass="error" showSummary="true" showDetail="false"
								for="tags" />
							<t:dataTable id="tags" var="tagData"
								value="#{positionBean.departmentTags}"
								preserveDataModel="false" cellpadding="0" cellspacing="0"
								styleClass="listTable" headerClass="listHeaderCell"
								footerClass="listFooter" rows="#{settingBean.mySettings.listSize}"
								rowClasses="listRowO,listRowE"
								columnClasses="listCmdCell"
								rowOnMouseOver="this.savedClassName=this.className;this.className='listRowSel';"
								rowOnMouseOut="this.className=this.savedClassName;">						
								<h:column>
									<f:facet name="header">
										<f:verbatim>-</f:verbatim>
									</f:facet>
									<h:commandLink action="#{positionBean.deleteTag}">
										<h:graphicImage value="/img/delete.gif" styleClass="titleImg" />
									</h:commandLink>
								</h:column>						
								<h:column>
									<f:facet name="header">
										<f:verbatim>${msg['tag.name']}</f:verbatim>
									</f:facet>
									<h:outputText value="#{tagData.name}"  />
								</h:column>
								<h:column>
									<f:facet name="header">
										<f:verbatim>${msg['tag.description']}</f:verbatim>
									</f:facet>
									<h:outputText value="#{tagData.description}"  />
								</h:column>							
							</t:dataTable>
						</h:panelGroup>
					</h:panelGroup>
				</td>
			</tr>

		</table>

	</h:form>
</f:view>


</body>
</html>