<%--

    TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.
    Copyright (C) 2007 Autentia Real Bussiness Solution S.L.

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

--%>

<%@page language="java" contentType="text/html; charset=UTF-8"%>

<%@include file="/inc/tlibs.jsp"%>

<html>
<head>
<%@include file="/inc/uiCore.jsp"%>
</head>
<body>

<!-- editOrganization.jsp: generated by stajanov code generator -->
<f:loadBundle basename="com.autentia.tnt.resources.messages" var="msg" />
<i:location place="editOrganization" msg="${msg}" />

<f:view>
  <%@include file="/inc/header.jsp" %>
	<h:form id="organization" enctype="multipart/form-data">

		<%-- Header --%>
		<i:titleBar name="${organizationBean.name}" msg="${msg}">
			<h:commandLink action="#{organizationBean.save}"
				onclick="if(!askSave('#{organizationBean.id}','#{msg['question.confirmSave']}')) return false;">
				<h:graphicImage value="/img/save.gif" styleClass="titleImg" />
			</h:commandLink>
			<h:commandLink action="#{organizationBean.delete}" rendered="#{organizationBean.deleteAvailable}"
				onclick="if( !confirm('#{msg['question.confirmDelete']}') ) return false;">
				<h:graphicImage value="/img/delete.gif" styleClass="titleImg" />
			</h:commandLink>
			<h:commandLink action="#{organizationBean.list}" immediate="true">
				<h:graphicImage value="/img/back.gif" styleClass="titleImg" />
			</h:commandLink>
		</i:titleBar>
		<h:message styleClass="error" showSummary="true" showDetail="false" for="organization" />
		<%-- Edition form --%>
		<table class="editTable" cellpadding="0" cellspacing="0">

<%-- organization - generated by stajanov (do not edit/delete) --%>








                  
  
      <%-- Ignored field: id --%>
  
                                  
    
      <%-- Field: name --%>
    <tr>
    	    		<td class="editLabelRW">*${msg['organization.name']}:</td>
    	      
      <td class="editFieldCell">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="name" />
                		<h:inputText id="name" value="#{organizationBean.name}" size="70" maxlength="128" required="true" styleClass="requiredFieldClass"/>
    	              </h:panelGroup>

              </td>
    </tr>
                                  
  
      <%-- Field: cif --%>
    <tr>
    	    		<td class="editLabelRW">${msg['organization.cif']}:</td>
    	      
      <td class="editFieldCell">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="cif" />
                		<h:inputText id="cif" value="#{organizationBean.cif}" maxlength="50"/>
    	              </h:panelGroup>

              </td>
    </tr>
                                  
  
      <%-- Field: street --%>
    <tr>
    	    		<td class="editLabelRW">${msg['organization.street']}:</td>
    	      
      <td class="editFieldCell">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="street" />
                		<h:inputText id="street" value="#{organizationBean.street}" size="70" maxlength="256"/>
    	              </h:panelGroup>

              </td>
    </tr>
                                  
  
      <%-- Field: number --%>
    <tr>
    	    		<td class="editLabelRW">${msg['organization.number']}:</td>
    	      
      <td class="editFieldCell">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="number" />
                		<h:inputText id="number" value="#{organizationBean.number}" maxlength="16"/>
    	              </h:panelGroup>

              </td>
    </tr>
                                  
  
      <%-- Field: locator --%>
    <tr>
    	    		<td class="editLabelRW">${msg['organization.locator']}:</td>
    	      
      <td class="editFieldCell">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="locator" />
                		<h:inputText id="locator" value="#{organizationBean.locator}" size="70" maxlength="256"/>
    	              </h:panelGroup>

              </td>
    </tr>
                                  
  
      <%-- Field: postalCode --%>
    <tr>
    	    		<td class="editLabelRW">${msg['organization.postalCode']}:</td>
    	      
      <td class="editFieldCell">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="postalCode" />
                		<h:inputText id="postalCode" value="#{organizationBean.postalCode}" maxlength="32"/>
    	              </h:panelGroup>

              </td>
    </tr>
                                  
  
      <%-- Field: city --%>
    <tr>
    	    		<td class="editLabelRW">${msg['organization.city']}:</td>
    	      
      <td class="editFieldCell">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="city" />
                		<h:inputText id="city" value="#{organizationBean.city}" size="70" maxlength="256"/>
    	              </h:panelGroup>

              </td>
    </tr>
                                  
  
      <%-- Field: state --%>
    <tr>
    	    		<td class="editLabelRW">${msg['organization.state']}:</td>
    	      
      <td class="editFieldCell">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="state" />
                		<h:inputText id="state" value="#{organizationBean.state}" size="70" maxlength="256"/>
    	              </h:panelGroup>

              </td>
    </tr>
                                  
  
      <%-- Field: country --%>
    <tr>
    	    		<td class="editLabelRW">${msg['organization.country']}:</td>
    	      
      <td class="editFieldCell">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="country" />
                		<h:inputText id="country" value="#{organizationBean.country}" size="70" maxlength="256"/>
    	              </h:panelGroup>

              </td>
    </tr>
                                  
  
      <%-- Field: phone --%>
    <tr>
    	    		<td class="editLabelRW">${msg['organization.phone']}:</td>
    	      
      <td class="editFieldCell">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="phone" />
                		<h:inputText id="phone" value="#{organizationBean.phone}" maxlength="15"/>
    	              </h:panelGroup>

              </td>
    </tr>
                                  
  
      <%-- Field: fax --%>
    <tr>
    	    		<td class="editLabelRW">${msg['organization.fax']}:</td>
    	      
      <td class="editFieldCell">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="fax" />
                		<h:inputText id="fax" value="#{organizationBean.fax}" size="70" maxlength="16"/>
    	              </h:panelGroup>

              </td>
    </tr>
                                  
  
      <%-- Field: email --%>
    <tr>
    	    		<td class="editLabelRW">${msg['organization.email']}:</td>
    	      
      <td class="editFieldCell">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="email" />
                		<h:inputText id="email" value="#{organizationBean.email}" size="70" maxlength="256"/>
    	              </h:panelGroup>

              </td>
    </tr>
                                  
  
      <%-- Field: website --%>
    <tr>
    	    		<td class="editLabelRW">${msg['organization.website']}:</td>
    	      
      <td class="editFieldCell">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="website" />
                		<h:inputText id="website" value="#{organizationBean.website}" size="70" maxlength="256"/>
    	              </h:panelGroup>

              </td>
    </tr>
                                  
  
      <%-- Field: ftpsite --%>
    <tr>
    	    		<td class="editLabelRW">${msg['organization.ftpsite']}:</td>
    	      
      <td class="editFieldCell">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="ftpsite" />
                		<h:inputText id="ftpsite" value="#{organizationBean.ftpsite}" size="70" maxlength="256"/>
    	              </h:panelGroup>

              </td>
    </tr>
                                  
  
      <%-- Field: notes --%>
    <tr>
    	    		<td class="editLabelRW">${msg['organization.notes']}:</td>
    	      
      <td class="editFieldCell">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="notes" />
                		<h:inputText id="notes" value="#{organizationBean.notes}" size="70" maxlength="1024"/>
    	              </h:panelGroup>

              </td>
    </tr>
                                  
  
      <%-- Ignored field: ownerId --%>
  
                                  
  
      <%-- Ignored field: departmentId --%>
  
                                  
  
      <%-- Ignored field: insertDate --%>
  
                                  
  
      <%-- Ignored field: updateDate --%>
  
                                              
    
      <%-- Field: type --%>
    <tr>
    	    		<td class="editLabelRW">*${msg['organization.type']}:</td>
    	      
      <td class="editFieldCell">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="type" />
            <h:selectOneMenu id="type" value="#{organizationBean.type}"  required="true" styleClass="requiredFieldClass">
              <f:selectItems value="#{organizationBean.types}" />
              <f:converter converterId="autentia.EntityConverter"/>
            </h:selectOneMenu>
          </h:panelGroup>

              </td>
    </tr>
                                  
    
      <%-- Field: category --%>
    <tr>
    	    		<td class="editLabelRW">*${msg['organization.category']}:</td>
    	      
      <td class="editFieldCell">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="category" />
            <h:selectOneMenu id="category" value="#{organizationBean.category}"  required="true" styleClass="requiredFieldClass">
              <f:selectItems value="#{organizationBean.categorys}" />
              <f:converter converterId="autentia.EntityConverter"/>
            </h:selectOneMenu>
          </h:panelGroup>

              </td>
    </tr>
    
     <tr>
    	    		<td class="editLabelRW">${msg['organization.evaluationCriteria']}:</td>
    	      
      <td class="editFieldCell">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="evaluation" />
            <h:selectOneMenu id="evaluation" value="#{organizationBean.evaluationCriteria}">
              <f:selectItems value="#{organizationBean.evaluationCriterias}" />              
            </h:selectOneMenu>
          </h:panelGroup>

              </td>
    </tr>
    
                                  
    
      <%-- Field: province --%>
    <tr>
    	    		<td class="editLabelRW">*${msg['organization.province']}:</td>
    	      
      <td class="editFieldCell">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="province" />
            <h:selectOneMenu id="province" value="#{organizationBean.province}"  required="true" styleClass="requiredFieldClass">
              <f:selectItems value="#{organizationBean.provinces}" />
              <f:converter converterId="autentia.EntityConverter"/>
            </h:selectOneMenu>
          </h:panelGroup>

              </td>
    </tr>


           <%-- Field: departments --%>
    <tr>
    	    		<td class="editLabelRW">${msg['organization.departments']}:</td>
    	      
     				 <td class="editFieldCell">
                            <%@include file="inlineEditOrganizationDepartment.jsp"%>
          
              </td>
    </tr>

			<%-- Field: tags --%>
		    <tr>
				<td class="editLabelRW">${msg['organization.tags']}:</td>
				<td class="editFieldCell" colspan="2">
					<h:panelGroup>
						<h:panelGroup rendered="#{organizationBean.areTagsToSelect}">
							<h:selectOneMenu id="tagsList" value="#{organizationBean.selectedTag}">
								<f:selectItems value="#{organizationBean.allTags}" />
								<f:converter converterId="autentia.EntityConverter"/>
								<f:attribute name="com.autentia.tnt.converter.EntityConverter.valueClass" 
			                        	  value="com.autentia.tnt.businessobject.Tag"/> 
							</h:selectOneMenu>
							<h:commandLink action="#{organizationBean.addTag}">
								<h:graphicImage value="/img/add.png" styleClass="titleImg" />
							</h:commandLink>
						</h:panelGroup>
						<h:panelGroup rendered="#{!positionBean.areTagsToSelect}">
							<h:graphicImage value="/img/updated.gif" styleClass="titleImg" />
							<h:outputText value="#{msg['position.warn.noTags']}"  />
						</h:panelGroup>		
						
						<h:panelGroup rendered="#{organizationBean.areTagsSelected}">
							<h:message styleClass="error" showSummary="true" showDetail="false"
								for="tags" />
							
							<t:dataTable id="tags" var="tagData"
								value="#{organizationBean.departmentTags}"
								preserveDataModel="false" cellpadding="0" cellspacing="0"
								styleClass="listTable" headerClass="listHeaderCell"
								footerClass="listFooter" rows="#{settingBean.mySettings.listSize}"
								rowClasses="listRowO,listRowE"
								columnClasses="listCmdCell"
								rowOnMouseOver="this.savedClassName=this.className;this.className='listRowSel';"
								rowOnMouseOut="this.className=this.savedClassName;">						
								<h:column>
									<f:facet name="header">
										<f:verbatim>-</f:verbatim>
									</f:facet>
									<h:commandLink action="#{organizationBean.deleteTag}">
										<h:graphicImage value="/img/delete.gif" styleClass="titleImg" />
									</h:commandLink>
								</h:column>						
								<h:column>
									<f:facet name="header">
										<f:verbatim>${msg['tag.name']}</f:verbatim>
									</f:facet>
									<h:outputText value="#{tagData.name}"  />
								</h:column>
								<h:column>
									<f:facet name="header">
										<f:verbatim>${msg['tag.description']}</f:verbatim>
									</f:facet>
									<h:outputText value="#{tagData.description}"  />
								</h:column>							
							</t:dataTable>
						</h:panelGroup>
							
					</h:panelGroup>
				</td>
			</tr>	
	
<%-- organization - generated by stajanov (do not edit/delete) --%>

		</table>

	</h:form>
</f:view>

</body>
</html>

<%-- organization - generated by stajanov (do not edit/delete) --%>






