<%--

    TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.
    Copyright (C) 2007 Autentia Real Bussiness Solution S.L.

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

--%>

<%-- 
 * TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.  
 *	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.					   
 *	
 * 	This program is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU General Public License
 * 	as published by the Free Software Foundation; either version 2
 * 	of the License, or (at your option) any later version.
 *
 * 	This program is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *
 * 	You should have received a copy of the GNU General Public License
 * 	along with this program; if not, write to the Free Software
 * 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 	Autentia Real Bussiness Solution S.L.
 * 	Tlf: +34 91 675 33 06, +34 655 99 11 72
 * 	Fax: +34 91 656 65 04
 * 	info@autentia.com																
 *
 --%>
<%@page language="java" contentType="text/html; charset=UTF-8"%>

<%@include file="/inc/tlibs.jsp" %>

<html>
  <head>
    <%@include file="/inc/uiCore.jsp" %>
  </head>	
  <body>
    
    <!-- searchOrganization.jsp: generated by stajanov code generator -->
    <f:loadBundle basename="com.autentia.tnt.resources.messages" var="msg" />
    <i:location place="searchOrganization" msg="${msg}"/> 
    
    <f:view>
      <%@include file="/inc/header.jsp" %>
      <h:form id="search" enctype="multipart/form-data">
        
        <%-- Header --%>
        <i:titleBar msg="${msg}">
          <h:commandLink action="#{organizationBean.list}">
            <h:graphicImage title="#{msg.entityActions_run}"  value="/img/run.png" styleClass="titleImg" />
          </h:commandLink>
        </i:titleBar>
        
        <%-- Search form --%>
        <table class="searchTable" cellpadding="0" cellspacing="0">

          
      <%-- Ignored field: id --%>

                        
      <%-- Field: name --%>
    <tr>
      <td class="searchLabel">${msg['organization.name']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="name" />
            <h:selectBooleanCheckbox id="nameValid" value="#{organizationBean.searchNameValid}" 
                                      onclick="setEnabled('search:name',this.checked)"/>
            <h:inputText id="name" value="#{organizationBean.searchName}" size="70"/>
          </h:panelGroup>
          <script>
            setEnabled( 'search:name', ${organizationBean.searchNameValid} )
          </script>

        
      </td>
    </tr>
                        
      <%-- Field: cif --%>
    <tr>
      <td class="searchLabel">${msg['organization.cif']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="cif" />
            <h:selectBooleanCheckbox id="cifValid" value="#{organizationBean.searchCifValid}" 
                                      onclick="setEnabled('search:cif',this.checked)"/>
            <h:inputText id="cif" value="#{organizationBean.searchCif}" size="70"/>
          </h:panelGroup>
          <script>
            setEnabled( 'search:cif', ${organizationBean.searchCifValid} )
          </script>

        
      </td>
    </tr>
                        
      <%-- Field: street --%>
    <tr>
      <td class="searchLabel">${msg['organization.street']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="street" />
            <h:selectBooleanCheckbox id="streetValid" value="#{organizationBean.searchStreetValid}" 
                                      onclick="setEnabled('search:street',this.checked)"/>
            <h:inputText id="street" value="#{organizationBean.searchStreet}" size="70"/>
          </h:panelGroup>
          <script>
            setEnabled( 'search:street', ${organizationBean.searchStreetValid} )
          </script>

        
      </td>
    </tr>
                        
      <%-- Field: number --%>
    <tr>
      <td class="searchLabel">${msg['organization.number']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="number" />
            <h:selectBooleanCheckbox id="numberValid" value="#{organizationBean.searchNumberValid}" 
                                      onclick="setEnabled('search:number',this.checked)"/>
            <h:inputText id="number" value="#{organizationBean.searchNumber}" size="70"/>
          </h:panelGroup>
          <script>
            setEnabled( 'search:number', ${organizationBean.searchNumberValid} )
          </script>

        
      </td>
    </tr>
                        
      <%-- Field: locator --%>
    <tr>
      <td class="searchLabel">${msg['organization.locator']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="locator" />
            <h:selectBooleanCheckbox id="locatorValid" value="#{organizationBean.searchLocatorValid}" 
                                      onclick="setEnabled('search:locator',this.checked)"/>
            <h:inputText id="locator" value="#{organizationBean.searchLocator}" size="70"/>
          </h:panelGroup>
          <script>
            setEnabled( 'search:locator', ${organizationBean.searchLocatorValid} )
          </script>

        
      </td>
    </tr>
                        
      <%-- Field: postalCode --%>
    <tr>
      <td class="searchLabel">${msg['organization.postalCode']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="postalCode" />
            <h:selectBooleanCheckbox id="postalCodeValid" value="#{organizationBean.searchPostalCodeValid}" 
                                      onclick="setEnabled('search:postalCode',this.checked)"/>
            <h:inputText id="postalCode" value="#{organizationBean.searchPostalCode}" size="70"/>
          </h:panelGroup>
          <script>
            setEnabled( 'search:postalCode', ${organizationBean.searchPostalCodeValid} )
          </script>

        
      </td>
    </tr>
                        
      <%-- Field: city --%>
    <tr>
      <td class="searchLabel">${msg['organization.city']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="city" />
            <h:selectBooleanCheckbox id="cityValid" value="#{organizationBean.searchCityValid}" 
                                      onclick="setEnabled('search:city',this.checked)"/>
            <h:inputText id="city" value="#{organizationBean.searchCity}" size="70"/>
          </h:panelGroup>
          <script>
            setEnabled( 'search:city', ${organizationBean.searchCityValid} )
          </script>

        
      </td>
    </tr>
                        
      <%-- Field: state --%>
    <tr>
      <td class="searchLabel">${msg['organization.state']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="state" />
            <h:selectBooleanCheckbox id="stateValid" value="#{organizationBean.searchStateValid}" 
                                      onclick="setEnabled('search:state',this.checked)"/>
            <h:inputText id="state" value="#{organizationBean.searchState}" size="70"/>
          </h:panelGroup>
          <script>
            setEnabled( 'search:state', ${organizationBean.searchStateValid} )
          </script>

        
      </td>
    </tr>
                        
      <%-- Field: country --%>
    <tr>
      <td class="searchLabel">${msg['organization.country']}:</td>
      <td class="searchFieldCell">


          <h:panelGroup>
              <h:message styleClass="error" showSummary="true" showDetail="false" for="country" />
              <h:selectBooleanCheckbox id="countryValid" value="#{organizationBean.searchCountryValid}"
                                       onclick="setEnabled('search:country',this.checked)"/>
              <h:selectOneMenu id="country" value="#{organizationBean.searchCountry}" onclick="setEnabled('search:country',true)">
                  <f:selectItems value="#{organizationBean.countries}" />
                  <f:converter converterId="autentia.EntityConverter"/>
              </h:selectOneMenu>
          </h:panelGroup>
          <script>
            setEnabled( 'search:country', ${organizationBean.searchCountryValid} )
          </script>

        
      </td>
    </tr>
                        
      <%-- Field: phone --%>
    <tr>
      <td class="searchLabel">${msg['organization.phone']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="phone" />
            <h:selectBooleanCheckbox id="phoneValid" value="#{organizationBean.searchPhoneValid}" 
                                      onclick="setEnabled('search:phone',this.checked)"/>
            <h:inputText id="phone" value="#{organizationBean.searchPhone}" size="70"/>
          </h:panelGroup>
          <script>
            setEnabled( 'search:phone', ${organizationBean.searchPhoneValid} )
          </script>

        
      </td>
    </tr>
                        
      <%-- Field: fax --%>
    <tr>
      <td class="searchLabel">${msg['organization.fax']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="fax" />
            <h:selectBooleanCheckbox id="faxValid" value="#{organizationBean.searchFaxValid}" 
                                      onclick="setEnabled('search:fax',this.checked)"/>
            <h:inputText id="fax" value="#{organizationBean.searchFax}" size="70"/>
          </h:panelGroup>
          <script>
            setEnabled( 'search:fax', ${organizationBean.searchFaxValid} )
          </script>

        
      </td>
    </tr>
                        
      <%-- Field: email --%>
    <tr>
      <td class="searchLabel">${msg['organization.email']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="email" />
            <h:selectBooleanCheckbox id="emailValid" value="#{organizationBean.searchEmailValid}" 
                                      onclick="setEnabled('search:email',this.checked)"/>
            <h:inputText id="email" value="#{organizationBean.searchEmail}" size="70"/>
          </h:panelGroup>
          <script>
            setEnabled( 'search:email', ${organizationBean.searchEmailValid} )
          </script>

        
      </td>
    </tr>
                        
      <%-- Field: website --%>
    <tr>
      <td class="searchLabel">${msg['organization.website']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="website" />
            <h:selectBooleanCheckbox id="websiteValid" value="#{organizationBean.searchWebsiteValid}" 
                                      onclick="setEnabled('search:website',this.checked)"/>
            <h:inputText id="website" value="#{organizationBean.searchWebsite}" size="70"/>
          </h:panelGroup>
          <script>
            setEnabled( 'search:website', ${organizationBean.searchWebsiteValid} )
          </script>

        
      </td>
    </tr>
                        
      <%-- Field: ftpsite --%>
    <tr>
      <td class="searchLabel">${msg['organization.ftpsite']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="ftpsite" />
            <h:selectBooleanCheckbox id="ftpsiteValid" value="#{organizationBean.searchFtpsiteValid}" 
                                      onclick="setEnabled('search:ftpsite',this.checked)"/>
            <h:inputText id="ftpsite" value="#{organizationBean.searchFtpsite}" size="70"/>
          </h:panelGroup>
          <script>
            setEnabled( 'search:ftpsite', ${organizationBean.searchFtpsiteValid} )
          </script>

        
      </td>
    </tr>
                        
      <%-- Field: notes --%>
    <tr>
      <td class="searchLabel">${msg['organization.notes']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="notes" />
            <h:selectBooleanCheckbox id="notesValid" value="#{organizationBean.searchNotesValid}" 
                                      onclick="setEnabled('search:notes',this.checked)"/>
            <h:inputText id="notes" value="#{organizationBean.searchNotes}" size="70"/>
          </h:panelGroup>
          <script>
            setEnabled( 'search:notes', ${organizationBean.searchNotesValid} )
          </script>

        
      </td>
    </tr>
                        
      <%-- Ignored field: ownerId --%>

                        
      <%-- Ignored field: departmentId --%>

                        
      <%-- Ignored field: insertDate --%>

                        
      <%-- Ignored field: updateDate --%>

                                  
      <%-- Field: type --%>
    <tr>
      <td class="searchLabel">${msg['organization.type']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="type" />
            <h:selectBooleanCheckbox id="typeValid" value="#{organizationBean.searchTypeValid}" 
                                      onclick="setEnabled('search:type',this.checked)"/>
            <h:selectOneMenu id="type" value="#{organizationBean.searchType}" onclick="setEnabled('search:type',true)">
              <f:selectItems value="#{organizationBean.types}" />
              <f:converter converterId="autentia.EntityConverter"/>
            </h:selectOneMenu>
          </h:panelGroup>
          <script>
            setEnabled( 'search:type', ${organizationBean.searchTypeValid} )
          </script>

        
      </td>
    </tr>
                        
      <%-- Field: category --%>
    <tr>
      <td class="searchLabel">${msg['organization.category']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="category" />
            <h:selectBooleanCheckbox id="categoryValid" value="#{organizationBean.searchCategoryValid}" 
                                      onclick="setEnabled('search:category',this.checked)"/>
            <h:selectOneMenu id="category" value="#{organizationBean.searchCategory}" onclick="setEnabled('search:category',true)">
              <f:selectItems value="#{organizationBean.categorys}" />
              <f:converter converterId="autentia.EntityConverter"/>
            </h:selectOneMenu>
          </h:panelGroup>
          <script>
            setEnabled( 'search:category', ${organizationBean.searchCategoryValid} )
          </script>

        
      </td>
    </tr>
     <tr>
    	    		<td class="searchLabel">${msg['organization.evaluationCriteria']}:</td>
    	      
      <td class="searchFieldCell">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="evaluation" />
             <h:selectBooleanCheckbox id="evaluationValid" value="#{organizationBean.searchEvaluationCriteriaValid}" 
                                      onclick="setEnabled('search:evaluation',this.checked)"/>
            <h:selectOneMenu id="evaluation" value="#{organizationBean.searchEvaluationCriteria}"  onclick="setEnabled('search:evaluation',true)">
              <f:selectItems value="#{organizationBean.evaluationCriterias}" />              
            </h:selectOneMenu>
          </h:panelGroup>
          <script>
            setEnabled( 'search:evaluation', ${organizationBean.searchEvaluationCriteriaValid} )
          </script>

              </td>
    </tr>
    
    
    
    
    
                        
      <%-- Field: province --%>
    <tr>
      <td class="searchLabel">${msg['organization.province']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="province" />
            <h:selectBooleanCheckbox id="provinceValid" value="#{organizationBean.searchProvinceValid}" 
                                      onclick="setEnabled('search:province',this.checked)"/>
            <h:selectOneMenu id="province" value="#{organizationBean.searchProvince}" onclick="setEnabled('search:province',true)">
              <f:selectItems value="#{organizationBean.provinces}" />
              <f:converter converterId="autentia.EntityConverter"/>
            </h:selectOneMenu>
          </h:panelGroup>
          <script>
            setEnabled( 'search:province', ${organizationBean.searchProvinceValid} )
          </script>

        
      </td>
    </tr>
                                
        </table>
        
      </h:form>
    </f:view>
    
  </body>
</html>  		
