<%--

    TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.
    Copyright (C) 2007 Autentia Real Bussiness Solution S.L.

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

--%>

<%-- 
 * TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.  
 *	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.					   
 *	
 * 	This program is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU General Public License
 * 	as published by the Free Software Foundation; either version 2
 * 	of the License, or (at your option) any later version.
 *
 * 	This program is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *
 * 	You should have received a copy of the GNU General Public License
 * 	along with this program; if not, write to the Free Software
 * 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 	Autentia Real Bussiness Solution S.L.
 * 	Tlf: +34 91 675 33 06, +34 655 99 11 72
 * 	Fax: +34 91 656 65 04
 * 	info@autentia.com																
 *
 --%>
<%@page language="java" contentType="text/html; charset=UTF-8"%>

<%@include file="/inc/tlibs.jsp"%>

<html>
<head>
<%@include file="/inc/uiCore.jsp"%>
</head>
<body>

<!-- searchPosition.jsp: generated by stajanov code generator -->
<f:loadBundle basename="com.autentia.tnt.resources.messages" var="msg" />
<i:location place="searchPosition" msg="${msg}" />

<f:view>
	<%@include file="/inc/header.jsp"%>
	<h:form id="search" enctype="multipart/form-data">

		<%-- Header --%>
		<i:titleBar msg="${msg}">
			<h:commandLink action="#{positionBean.list}">
				<h:graphicImage title="#{msg.entityActions_run}"
					value="/img/run.png" styleClass="titleImg" />
			</h:commandLink>
		</i:titleBar>

		<%-- Search form --%>
		<table class="searchTable" cellpadding="0" cellspacing="0">



			<%-- Field: name --%>
			<tr>
				<td class="searchLabel">${msg['position.name']}:</td>
				<td class="searchFieldCell"><h:panelGroup>
					<h:message styleClass="error" showSummary="true" showDetail="false"
						for="name" />
					<h:selectBooleanCheckbox id="nameValid"
						value="#{positionBean.searchNameValid}"
						onclick="setEnabled('search:name',this.checked)" />
					<h:inputText id="name" value="#{positionBean.searchName}" size="70" />
				</h:panelGroup> <script>
            setEnabled( 'search:name', ${positionBean.searchNameValid} )
          </script></td>
			</tr>

			<%-- Field: description --%>
			<tr>
				<td class="searchLabel">${msg['position.description']}:</td>
				<td class="searchFieldCell"><h:panelGroup>
					<h:message styleClass="error" showSummary="true" showDetail="false"
						for="description" />
					<h:selectBooleanCheckbox id="descriptionValid"
						value="#{positionBean.searchDescriptionValid}"
						onclick="setEnabled('search:description',this.checked)" />
					<h:inputText id="description"
						value="#{positionBean.searchDescription}" size="70" />
				</h:panelGroup> <script>
            setEnabled( 'search:description', ${positionBean.searchDescriptionValid} )
          </script></td>
			</tr>

			<%-- Field: deleted --%>
			<tr>
				<td class="searchLabel">${msg['position.deleted']}:</td>
				<td class="searchFieldCell"><h:panelGroup>
					<h:message styleClass="error" showSummary="true" showDetail="false"
						for="deleted" />
					<h:selectBooleanCheckbox id="deletedValid"
						value="#{positionBean.searchDeletedValid}"
						onclick="setEnabledByName('search:deleted',this.checked)" />

					<h:outputLabel for="deleted" value="#{msg['msg.yesno']}"></h:outputLabel>
					<h:selectBooleanCheckbox id="deleted"
						value="#{positionBean.searchDeleted}" />

				</h:panelGroup> <script>
            setEnabledByName( 'search:deleted', ${positionBean.searchDeletedValid} )
          </script></td>
			</tr>
		</table>

	</h:form>
</f:view>

</body>
</html>
