/**
 * TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.
 * Copyright (C) 2007 Autentia Real Bussiness Solution S.L.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.autentia.tnt.businessobject;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import java.util.Set;

import com.autentia.tnt.dao.ITransferObject;

/**
 * Transfer object to store Bills
 * @author stajanov code generator
 */
public class CreditTitle implements Serializable, ITransferObject
{
	/* creditTitle - generated by stajanov (do not edit/delete) */


  // Fields
  
  
    
  private Integer id;

      
      
  private String number;

      
      
  private String concept;

      
  
    
  private CreditTitleState state;

      
  
    
  private CreditTitleType type;

      
      
  private Date issueDate;

      
      
  private Date expirationDate;

      
      
  private String observations;

      
      
  private Integer ownerId;

      
      
  private Integer departmentId;

      
      
  private Date insertDate;

      
      
  private Date updateDate;

        
  private BigDecimal amount;
  
    
  private Organization organization;

          
              
  private Set<Bill> bills;

    	 	

  // Setters and getters
  
  
  
  public Integer getId() {
    return id;
  }
  private void setId( Integer id ) {
    this.id = id;
  }
      
  
  
  public String getNumber() {
    return number;
  }
  public void setNumber( String number ) {
    this.number = number;
  }
      
  
  
  public String getConcept() {
    return concept;
  }
  public void setConcept( String concept ) {
    this.concept = concept;
  }
      
  
  
  public CreditTitleState getState() {
    return state;
  }
  public void setState( CreditTitleState creditTitleState ) {
    this.state = creditTitleState;
  }
      
  
  
  public CreditTitleType getType() {
    return type;
  }
  public void setType( CreditTitleType creditTitleType ) {
    this.type = creditTitleType;
  }
      
  
  
  public Date getIssueDate() {
    return issueDate;
  }
  public void setIssueDate( Date issueDate ) {
    this.issueDate = issueDate;
  }
      
  
  
  public Date getExpirationDate() {
    return expirationDate;
  }
  public void setExpirationDate( Date expirationDate ) {
    this.expirationDate = expirationDate;
  }
      
  
  
  public String getObservations() {
    return observations;
  }
  public void setObservations( String observations ) {
    this.observations = observations;
  }
      
  
  
  public Integer getOwnerId() {
    return ownerId;
  }
  public void setOwnerId( Integer ownerId ) {
    this.ownerId = ownerId;
  }
      
  
  
  public Integer getDepartmentId() {
    return departmentId;
  }
  public void setDepartmentId( Integer departmentId ) {
    this.departmentId = departmentId;
  }
      
  
  
  public Date getInsertDate() {
    return insertDate;
  }
  public void setInsertDate( Date insertDate ) {
    this.insertDate = insertDate;
  }
      
  
  
  public Date getUpdateDate() {
    return updateDate;
  }
  public void setUpdateDate( Date updateDate ) {
    this.updateDate = updateDate;
  }
        
  
  
  public Organization getOrganization() {
    return organization;
  }
  public void setOrganization( Organization organization ) {
    this.organization = organization;
  }
          
            
  public Set<Bill> getBills() {
    return bills;
  }
  public void setBills( Set<Bill> bills ) {
    this.bills = bills;
  }
    
    
    
    
  
  public BigDecimal getAmount() {
	return amount;
  }
	
  public void setAmount(BigDecimal amount) {
	this.amount = amount;
  }
  
  
@Override
  public boolean equals( Object that )
  {
  	try {
  		if (that == null) 
  			return false;
  		else 
    		return this.getId().equals( ((CreditTitle)that).getId() );
    } catch (Exception e) {
		return false;
	}
  }
  
  @Override
  public int hashCode() {
  	  if(this.getId()==null)
  	  	return super.hashCode();
  	  else	
	 	return this.getId().intValue();
	}

	public List<Integer> getOwnersId() {
		// TODO Auto-generated method stub
		return null;
	}

/* creditTitle - generated by stajanov (do not edit/delete) */
}