/**
 * TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.
 * Copyright (C) 2007 Autentia Real Bussiness Solution S.L.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.autentia.tnt.businessobject;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import com.autentia.tnt.dao.ITransferObject;



public class FinancialRatio implements Serializable, ITransferObject {
/* FinancialRatio - generated by stajanov (do not edit/delete) */







  // Fields
  
  
    
  private Integer id;

      
      
  private String title;

      
      
  private Date ratioDate;

      
      
  private BigDecimal banksAccounts;

      
      
  private BigDecimal customers;

      
      
  private BigDecimal stocks;

      
      
  private BigDecimal amortizations;

      
      
  private BigDecimal infrastructures;

      
      
  private BigDecimal shortTermLiability;

      
      
  private BigDecimal obligationBond;

      
      
  private BigDecimal capital;

      
      
  private BigDecimal reserves;

      
      
  private BigDecimal incomes;

      
      
  private BigDecimal expenses;

      
      
  private BigDecimal otherExploitationExpenses;

      
      
  private BigDecimal financialExpenses;

      
      
  private BigDecimal taxes;

      
      
  private BigDecimal netAsset;

      
      
  private BigDecimal totalAsset;

      
      
  private BigDecimal totalOtherResources;

      
      
  private BigDecimal totalOurResources;

      
      
  private BigDecimal totalLiability;

      
      
  private BigDecimal margin;

      
      
  private BigDecimal bait;

      
      
  private BigDecimal bat;

      
      
  private BigDecimal bdt;

      
      
  private BigDecimal baitd;

      
      
  private BigDecimal liquidity;

      
      
  private BigDecimal exchequer;

      
      
  private BigDecimal availability;

      
      
  private BigDecimal expensesCoverage;

      
      
  private BigDecimal workingCapital;

      
      
  private BigDecimal solvency;

      
      
  private BigDecimal debtRatio;

      
      
  private BigDecimal debtTotalLiability;

      
      
  private BigDecimal guarantee;

      
      
  private BigDecimal financeCoverage;

      
      
  private BigDecimal collectionPeriod;

      
      
  private BigDecimal payPeriod;

      
      
  private BigDecimal turnoverAsset;

      
      
  private BigDecimal turnoverPermanentAsset;

      
      
  private BigDecimal turnoverFM;

      
      
  private BigDecimal grossSpread;

      
      
  private BigDecimal baitSpread;

      
      
  private BigDecimal bdtSpread;

      
      
  private BigDecimal baitROA;

      
      
  private BigDecimal baitdROA;

      
      
  private BigDecimal ROE;

      
      
  private BigDecimal leveraging;

      
      
  private BigDecimal ROCE;

      
      
  private Integer ownerId;

      
      
  private Integer departmentId;

      
      
  private Date insertDate;

      
      
  private Date updateDate;

          	 	

  // Setters and getters
  
  
  
  public Integer getId() {
    return id;
  }
  private void setId( Integer id ) {
    this.id = id;
  }
      
  
  
  public String getTitle() {
    return title;
  }
  public void setTitle( String title ) {
    this.title = title;
  }
      
  
  
  public Date getRatioDate() {
    return ratioDate;
  }
  public void setRatioDate( Date ratioDate ) {
    this.ratioDate = ratioDate;
  }
      
  
  
  public BigDecimal getBanksAccounts() {
    return banksAccounts;
  }
  public void setBanksAccounts( BigDecimal banksAccounts ) {
    this.banksAccounts = banksAccounts;
  }
      
  
  
  public BigDecimal getCustomers() {
    return customers;
  }
  public void setCustomers( BigDecimal customers ) {
    this.customers = customers;
  }
      
  
  
  public BigDecimal getStocks() {
    return stocks;
  }
  public void setStocks( BigDecimal stocks ) {
    this.stocks = stocks;
  }
      
  
  
  public BigDecimal getAmortizations() {
    return amortizations;
  }
  public void setAmortizations( BigDecimal amortizations ) {
    this.amortizations = amortizations;
  }
      
  
  
  public BigDecimal getInfrastructures() {
    return infrastructures;
  }
  public void setInfrastructures( BigDecimal infrastructures ) {
    this.infrastructures = infrastructures;
  }
      
  
  
  public BigDecimal getShortTermLiability() {
    return shortTermLiability;
  }
  public void setShortTermLiability( BigDecimal shortTermLiability ) {
    this.shortTermLiability = shortTermLiability;
  }
      
  
  
  public BigDecimal getObligationBond() {
    return obligationBond;
  }
  public void setObligationBond( BigDecimal obligationBond ) {
    this.obligationBond = obligationBond;
  }
      
  
  
  public BigDecimal getCapital() {
    return capital;
  }
  public void setCapital( BigDecimal capital ) {
    this.capital = capital;
  }
      
  
  
  public BigDecimal getReserves() {
    return reserves;
  }
  public void setReserves( BigDecimal reserves ) {
    this.reserves = reserves;
  }
      
  
  
  public BigDecimal getIncomes() {
    return incomes;
  }
  public void setIncomes( BigDecimal incomes ) {
    this.incomes = incomes;
  }
      
  
  
  public BigDecimal getExpenses() {
    return expenses;
  }
  public void setExpenses( BigDecimal expenses ) {
    this.expenses = expenses;
  }
      
  
  
  public BigDecimal getOtherExploitationExpenses() {
    return otherExploitationExpenses;
  }
  public void setOtherExploitationExpenses( BigDecimal otherExploitationExpenses ) {
    this.otherExploitationExpenses = otherExploitationExpenses;
  }
      
  
  
  public BigDecimal getFinancialExpenses() {
    return financialExpenses;
  }
  public void setFinancialExpenses( BigDecimal financialExpenses ) {
    this.financialExpenses = financialExpenses;
  }
      
  
  
  public BigDecimal getTaxes() {
    return taxes;
  }
  public void setTaxes( BigDecimal taxes ) {
    this.taxes = taxes;
  }
      
  
  
  public BigDecimal getNetAsset() {
    return netAsset;
  }
  public void setNetAsset( BigDecimal netAsset ) {
    this.netAsset = netAsset;
  }
      
  
  
  public BigDecimal getTotalAsset() {
    return totalAsset;
  }
  public void setTotalAsset( BigDecimal totalAsset ) {
    this.totalAsset = totalAsset;
  }
      
  
  
  public BigDecimal getTotalOtherResources() {
    return totalOtherResources;
  }
  public void setTotalOtherResources( BigDecimal totalOtherResources ) {
    this.totalOtherResources = totalOtherResources;
  }
      
  
  
  public BigDecimal getTotalOurResources() {
    return totalOurResources;
  }
  public void setTotalOurResources( BigDecimal totalOurResources ) {
    this.totalOurResources = totalOurResources;
  }
      
  
  
  public BigDecimal getTotalLiability() {
    return totalLiability;
  }
  public void setTotalLiability( BigDecimal totalLiability ) {
    this.totalLiability = totalLiability;
  }
      
  
  
  public BigDecimal getMargin() {
    return margin;
  }
  public void setMargin( BigDecimal margin ) {
    this.margin = margin;
  }
      
  
  
  public BigDecimal getBait() {
    return bait;
  }
  public void setBait( BigDecimal bait ) {
    this.bait = bait;
  }
      
  
  
  public BigDecimal getBat() {
    return bat;
  }
  public void setBat( BigDecimal bat ) {
    this.bat = bat;
  }
      
  
  
  public BigDecimal getBdt() {
    return bdt;
  }
  public void setBdt( BigDecimal bdt ) {
    this.bdt = bdt;
  }
      
  
  
  public BigDecimal getBaitd() {
    return baitd;
  }
  public void setBaitd( BigDecimal baitd ) {
    this.baitd = baitd;
  }
      
  
  
  public BigDecimal getLiquidity() {
    return liquidity;
  }
  public void setLiquidity( BigDecimal liquidity ) {
    this.liquidity = liquidity;
  }
      
  
  
  public BigDecimal getExchequer() {
    return exchequer;
  }
  public void setExchequer( BigDecimal exchequer ) {
    this.exchequer = exchequer;
  }
      
  
  
  public BigDecimal getAvailability() {
    return availability;
  }
  public void setAvailability( BigDecimal availability ) {
    this.availability = availability;
  }
      
  
  
  public BigDecimal getExpensesCoverage() {
    return expensesCoverage;
  }
  public void setExpensesCoverage( BigDecimal expensesCoverage ) {
    this.expensesCoverage = expensesCoverage;
  }
      
  
  
  public BigDecimal getWorkingCapital() {
    return workingCapital;
  }
  public void setWorkingCapital( BigDecimal workingCapital ) {
    this.workingCapital = workingCapital;
  }
      
  
  
  public BigDecimal getSolvency() {
    return solvency;
  }
  public void setSolvency( BigDecimal solvency ) {
    this.solvency = solvency;
  }
      
  
  
  public BigDecimal getDebtRatio() {
    return debtRatio;
  }
  public void setDebtRatio( BigDecimal debtRatio ) {
    this.debtRatio = debtRatio;
  }
      
  
  
  public BigDecimal getDebtTotalLiability() {
    return debtTotalLiability;
  }
  public void setDebtTotalLiability( BigDecimal debtTotalLiability ) {
    this.debtTotalLiability = debtTotalLiability;
  }
      
  
  
  public BigDecimal getGuarantee() {
    return guarantee;
  }
  public void setGuarantee( BigDecimal guarantee ) {
    this.guarantee = guarantee;
  }
      
  
  
  public BigDecimal getFinanceCoverage() {
    return financeCoverage;
  }
  public void setFinanceCoverage( BigDecimal financeCoverage ) {
    this.financeCoverage = financeCoverage;
  }
      
  
  
  public BigDecimal getCollectionPeriod() {
    return collectionPeriod;
  }
  public void setCollectionPeriod( BigDecimal collectionPeriod ) {
    this.collectionPeriod = collectionPeriod;
  }
      
  
  
  public BigDecimal getPayPeriod() {
    return payPeriod;
  }
  public void setPayPeriod( BigDecimal payPeriod ) {
    this.payPeriod = payPeriod;
  }
      
  
  
  public BigDecimal getTurnoverAsset() {
    return turnoverAsset;
  }
  public void setTurnoverAsset( BigDecimal turnoverAsset ) {
    this.turnoverAsset = turnoverAsset;
  }
      
  
  
  public BigDecimal getTurnoverPermanentAsset() {
    return turnoverPermanentAsset;
  }
  public void setTurnoverPermanentAsset( BigDecimal turnoverPermanentAsset ) {
    this.turnoverPermanentAsset = turnoverPermanentAsset;
  }
      
  
  
  public BigDecimal getTurnoverFM() {
    return turnoverFM;
  }
  public void setTurnoverFM( BigDecimal turnoverFM ) {
    this.turnoverFM = turnoverFM;
  }
      
  
  
  public BigDecimal getGrossSpread() {
    return grossSpread;
  }
  public void setGrossSpread( BigDecimal grossSpread ) {
    this.grossSpread = grossSpread;
  }
      
  
  
  public BigDecimal getBaitSpread() {
    return baitSpread;
  }
  public void setBaitSpread( BigDecimal baitSpread ) {
    this.baitSpread = baitSpread;
  }
      
  
  
  public BigDecimal getBdtSpread() {
    return bdtSpread;
  }
  public void setBdtSpread( BigDecimal bdtSpread ) {
    this.bdtSpread = bdtSpread;
  }
      
  
  
  public BigDecimal getBaitROA() {
    return baitROA;
  }
  public void setBaitROA( BigDecimal baitROA ) {
    this.baitROA = baitROA;
  }
      
  
  
  public BigDecimal getBaitdROA() {
    return baitdROA;
  }
  public void setBaitdROA( BigDecimal baitdROA ) {
    this.baitdROA = baitdROA;
  }
      
  
  
  public BigDecimal getROE() {
    return ROE;
  }
  public void setROE( BigDecimal ROE ) {
    this.ROE = ROE;
  }
      
  
  
  public BigDecimal getLeveraging() {
    return leveraging;
  }
  public void setLeveraging( BigDecimal leveraging ) {
    this.leveraging = leveraging;
  }
      
  
  
  public BigDecimal getROCE() {
    return ROCE;
  }
  public void setROCE( BigDecimal ROCE ) {
    this.ROCE = ROCE;
  }
      
  
  
  public Integer getOwnerId() {
    return ownerId;
  }
  public void setOwnerId( Integer ownerId ) {
    this.ownerId = ownerId;
  }
      
  
  
  public Integer getDepartmentId() {
    return departmentId;
  }
  public void setDepartmentId( Integer departmentId ) {
    this.departmentId = departmentId;
  }
      
  
  
  public Date getInsertDate() {
    return insertDate;
  }
  private void setInsertDate( Date insertDate ) {
    this.insertDate = insertDate;
  }
      
  
  
  public Date getUpdateDate() {
    return updateDate;
  }
  public void setUpdateDate( Date updateDate ) {
    this.updateDate = updateDate;
  }
          
    
    
    
  
  @Override
  public boolean equals( Object that )
  {
  	try {
  		if (that == null) 
  			return false;
  		else 
    		return this.getId().equals( ((FinancialRatio)that).getId() );
    } catch (Exception e) {
		return false;
	}
  }
  
  @Override
  public int hashCode() {
  	  if(this.getId()==null)
  	  	return super.hashCode();
  	  else	
	 	return this.getId().intValue();
	}

	public List<Integer> getOwnersId() {
		// TODO Auto-generated method stub
		return null;
	}

/* FinancialRatio - generated by stajanov (do not edit/delete) */

  
}
