<%--

    TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.
    Copyright (C) 2007 Autentia Real Bussiness Solution S.L.

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

--%>

<%@page language="java" contentType="text/html; charset=UTF-8"%>

<%@include file="/inc/tlibs.jsp" %>

<html>
  <head>
    <%@include file="/inc/uiCore.jsp" %>
  </head>	
  <body>
    
    <!-- editRequestHoliday.jsp: generated by stajanov code generator -->
    <f:loadBundle basename="com.autentia.tnt.resources.messages" var="msg" />
    <i:location place="detailRequestHoliday" msg="${msg}"/> 
    
    <f:view>
      <%@include file="/inc/header.jsp" %>
      <h:form id="requestHoliday" enctype="multipart/form-data">
        
        <%-- Header --%>
        <i:titleBar name="${requestHolidayBean.beginDate}" msg="${msg}">
          <t:commandLink action="#{requestHolidayBean.edit}" immediate="true" rendered="#{requestHolidayBean.editAvailable}">
            <f:param name="rowid" value="#{requestHolidayBean.id}" />
            <h:graphicImage title="#{msg.entityActions_edit}"  value="/img/edit.gif" styleClass="cmdImg" />
          </t:commandLink>
          <h:commandLink action="#{requestHolidayBean.delete}" rendered="#{requestHolidayBean.deleteAvailable}" onclick="if( !confirm('#{msg['question.confirmDelete']}') ) return false;">
            <h:graphicImage title="#{msg.entityActions_delete}"  value="/img/delete.gif" styleClass="titleImg" />
          </h:commandLink>
          <h:commandLink action="#{requestHolidayBean.list}" immediate="true">
            <h:graphicImage title="#{msg.entityActions_back}"  value="/img/back.gif" styleClass="titleImg" />
          </h:commandLink>
        </i:titleBar>


        <%-- Detail form --%>
        <table class="detailTable" cellpadding="0" cellspacing="0">

            
    
  
  
      <%-- Ignored field: id --%>
  
                            
    
  
  
      <%-- Field: beginDate --%>
    <tr>
	<td class="detailLabelRW">${msg['requestHoliday.beginDate']}:</td>
	<td class="detailFieldCell">
         	    	<h:outputText value="#{requestHolidayBean.beginDate}" converter="autentia.dateConverter" />
 	          </td>
    </tr>
                            
    
  
  
      <%-- Field: finalDate --%>
    <tr>
	<td class="detailLabelRW">${msg['requestHoliday.finalDate']}:</td>
	<td class="detailFieldCell">
         	    	<h:outputText value="#{requestHolidayBean.finalDate}" converter="autentia.dateConverter" />
 	          </td>
    </tr>
                            
    
  
  
      <%-- Field: state --%>
    <tr>
	<td class="detailLabelRW">${msg['requestHoliday.state']}:</td>
	<td class="detailFieldCell">
                	<h:outputText value="#{requestHolidayBean.stateFormatted}" />
              </td>
    </tr>
                            
    
  
  
      <%-- Field: userComment --%>
    <tr>
	<td class="detailLabelRW">${msg['requestHoliday.userComment']}:</td>
	<td class="detailFieldCell">
         	       <h:outputText value="#{requestHolidayBean.userComment}" />
 	      </td>
    </tr>
                            
    
  
  
      <%-- Field: observations --%>
    <tr>
	<td class="detailLabelRW">${msg['requestHoliday.observations']}:</td>
	<td class="detailFieldCell">
         	       <h:outputText value="#{requestHolidayBean.observations}" />
 	      </td>
    </tr>
                            
    
  
  
      <%-- Field: chargeYear --%>
    <tr>
	<td class="detailLabelRW">${msg['requestHoliday.chargeYear']}:</td>
	<td class="detailFieldCell">
         	    	<h:outputText value="#{requestHolidayBean.chargeYear}"  converter="autentia.date2YearConverter" />
 	          </td>
    </tr>
                            
    
  
  
      <%-- Ignored field: departmentId --%>
  
                            
    
  
  
      <%-- Ignored field: insertDate --%>
  
                            
    
  
  
      <%-- Ignored field: updateDate --%>
  
                                        
    
  
  
      <%-- Ignored field: userRequest --%>
  
                                      
        </table>

      </h:form>
    </f:view>
    
  </body>
</html>  		

<%-- requestHoliday - generated by stajanov (do not edit/delete) --%>
