<%--

    TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.
    Copyright (C) 2007 Autentia Real Bussiness Solution S.L.

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

--%>

 <%@page language="java" contentType="text/html; charset=UTF-8"%>

<%@include file="/inc/tlibs.jsp" %>

<html>
  <head>
    <%@include file="/inc/uiCore.jsp" %>
  </head>	
  <body>
    

    <f:loadBundle basename="com.autentia.tnt.resources.messages" var="msg" />
    <i:location place="editAdminHoliday" msg="${msg}"/> 
    
    <f:view>
        <%@include file="/inc/header.jsp" %>
      <h:form id="holiday" enctype="multipart/form-data">
        
        <%-- Header --%>
        <i:titleBar name="${adminHolidayBean.beginDate}" msg="${msg}">
          <h:commandLink action="#{adminHolidayBean.save}" onclick="if(!askSave('#{adminHolidayBean.id}','#{msg['question.confirmSave']}')) return false;">
            <h:graphicImage title="#{msg.entityActions_save}"  value="/img/save.gif" styleClass="titleImg" />
          </h:commandLink>
          <h:commandLink action="#{adminHolidayBean.delete}" onclick="if( !confirm('#{msg['question.confirmDelete']}') ) return false;">
            <h:graphicImage title="#{msg.entityActions_delete}"  value="/img/delete.gif" styleClass="titleImg" />
          </h:commandLink>
          <h:commandLink action="#{adminHolidayBean.list}" immediate="true">
            <h:graphicImage title="#{msg.entityActions_back}"  value="/img/back.gif" styleClass="titleImg" />
          </h:commandLink>
        </i:titleBar>        
        
        <%-- Edition form --%>
        <table class="editTable" cellpadding="0" cellspacing="0">

            
            
<%-- adminHoliday - generated by stajanov (do not edit/delete) --%>








                  
  
      <%-- Ignored field: id --%>
  
                                  
  
      <%-- Ignored field: beginDate --%>
  
                                  
  
      <%-- Ignored field: finalDate --%>
  
                                  
    
      <%-- Field: state --%>
    <tr>
    	    		<td class="editLabelRW">*${msg['adminHoliday.state']}:</td>
    	      
      <td class="editFieldCell">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="state" />
            <h:selectOneMenu id="state" value="#{adminHolidayBean.state}"  required="true" styleClass="requiredFieldClass">
              <f:converter converterId="autentia.EnumConverter"/>
              <f:selectItems value="#{adminHolidayBean.states}" />
            </h:selectOneMenu>
          </h:panelGroup>

              </td>
    </tr>
                                  
  
      <%-- Field: observations --%>
    <tr>
    	    		<td class="editLabelRW">${msg['adminHoliday.observations']}:</td>
    	      
      <td class="editFieldCell">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="observations" />
            <h:inputTextarea id="observations" value="#{adminHolidayBean.observations}" rows="5" cols="68"/>
          </h:panelGroup>

              </td>
    </tr>
                                  
  
      <%-- Ignored field: userComment --%>
  
                                  
  
      <%-- Ignored field: chargeYear --%>
  
                                  
  
      <%-- Ignored field: departmentId --%>
  
                                  
  
      <%-- Ignored field: insertDate --%>
  
                                  
  
      <%-- Ignored field: updateDate --%>
  
                                              
  
      <%-- Ignored field: userRequest --%>
  
                                      


<%-- adminHoliday - generated by stajanov (do not edit/delete) --%>
       </table>
        
      </h:form>
    </f:view>
    
  </body>
</html> 
