<%--

    TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.
    Copyright (C) 2007 Autentia Real Bussiness Solution S.L.

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

--%>

<%@page language="java" contentType="text/html; charset=UTF-8"%>

<%@include file="/inc/tlibs.jsp" %>

<html>
  <head>
    <%@include file="/inc/uiCore.jsp" %>
  </head>	
  <body>
    
    <!-- editAccount.jsp: generated by stajanov code generator -->
    <f:loadBundle basename="com.autentia.tnt.resources.messages" var="msg" />
    <i:location place="detailAccount" msg="${msg}"/> 
    
    <f:view>
      <%@include file="/inc/header.jsp" %>
      <h:form id="account" enctype="multipart/form-data">
        
        <%-- Header --%>
        <i:titleBar name="${accountBean.name}" msg="${msg}">
          <t:commandLink action="#{accountBean.edit}" immediate="true" rendered="#{accountBean.editAvailable}">
            <f:param name="rowid" value="#{accountBean.id}" />
            <h:graphicImage title="#{msg.entityActions_edit}"  value="/img/edit.gif" styleClass="cmdImg" />
          </t:commandLink>
          <h:commandLink action="#{accountBean.delete}" rendered="#{accountBean.deleteAvailable}" onclick="if( !confirm('#{msg['question.confirmDelete']}') ) return false;">
            <h:graphicImage title="#{msg.entityActions_delete}"  value="/img/delete.gif" styleClass="titleImg" />
          </h:commandLink>
          <h:commandLink action="#{accountBean.list}" immediate="true">
            <h:graphicImage title="#{msg.entityActions_back}"  value="/img/back.gif" styleClass="titleImg" />
          </h:commandLink>
        </i:titleBar>


        <%-- Detail form --%>
        <table class="detailTable" cellpadding="0" cellspacing="0">

            
    
  
  
      <%-- Ignored field: id --%>
  
                            
    
  
  
      <%-- Field: name --%>
    <tr>
	<td class="detailLabelRW">${msg['account.name']}:</td>
	<td class="detailFieldCell">
         	       <h:outputText value="#{accountBean.name}" />
 	      </td>
    </tr>
                            
    
  
  
      <%-- Field: number --%>
    <tr>
	<td class="detailLabelRW">${msg['account.number']}:</td>
	<td class="detailFieldCell">
         	       <h:outputText value="#{accountBean.number}" />
 	      </td>
    </tr>
                            
    
  
  
      <%-- Field: description --%>
    <tr>
	<td class="detailLabelRW">${msg['account.description']}:</td>
	<td class="detailFieldCell">
         	       <h:outputText value="#{accountBean.description}" />
 	      </td>
    </tr>
                            
    
  
  
      <%-- Ignored field: ownerId --%>
  
                            
    
  
  
      <%-- Ignored field: departmentId --%>
  
                            
    
  
  
      <%-- Ignored field: insertDate --%>
  
                            
    
  
  
      <%-- Ignored field: updateDate --%>
  
                                        
    
  
  
      <%-- Field: type --%>
    <tr>
	<td class="detailLabelRW">${msg['account.type']}:</td>
	<td class="detailFieldCell">
         	    	<h:outputText value="#{accountBean.type.name}"/>
 	          </td>
    </tr>
                                      
        </table>

      </h:form>
    </f:view>
    
  </body>
</html>  		

<%-- account - generated by stajanov (do not edit/delete) --%>
