<%--

    TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.
    Copyright (C) 2007 Autentia Real Bussiness Solution S.L.

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

--%>

<%@page language="java" contentType="text/html; charset=UTF-8"%>

<%@include file="/inc/tlibs.jsp" %>

<html>
  <head>
    <%@include file="/inc/uiCore.jsp" %>
  </head>	
  <body>
    
    <!-- editAccountEntryType.jsp: generated by stajanov code generator -->
    <f:loadBundle basename="com.autentia.tnt.resources.messages" var="msg" />
    <i:location place="editAccountEntryType" msg="${msg}"/> 
    
    <f:view>
        <%@include file="/inc/header.jsp" %>
      <h:form id="accountEntryType" enctype="multipart/form-data">
        
        <%-- Header --%>
        <i:titleBar name="${accountEntryTypeBean.name}" msg="${msg}">
          <h:commandLink action="#{accountEntryTypeBean.save}" onclick="if(!askSave('#{accountEntryTypeBean.id}','#{msg['question.confirmSave']}')) return false;">
            <h:graphicImage title="#{msg.entityActions_save}" value="/img/save.gif" styleClass="titleImg" />
          </h:commandLink>
          <h:commandLink action="#{accountEntryTypeBean.delete}" onclick="if( !confirm('#{msg['question.confirmDelete']}') ) return false;">
            <h:graphicImage title="#{msg.entityActions_delete}" value="/img/delete.gif" styleClass="titleImg" />
          </h:commandLink>
          <h:commandLink action="#{accountEntryTypeBean.list}" immediate="true">
            <h:graphicImage title="#{msg.entityActions_back}" value="/img/back.gif" styleClass="titleImg" />
          </h:commandLink>
        </i:titleBar>     
        
        <%-- Edition form --%>
        <table class="editTable" cellpadding="0" cellspacing="0">

<%-- accountEntryType - generated by stajanov (do not edit/delete) --%>








                  
  
      <%-- Ignored field: id --%>
  
                                  
    
      <%-- Field: name --%>
    <tr>
    	    		<td class="editLabelRW">*${msg['accountEntryType.name']}:</td>
    	      
      <td class="editFieldCell">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="name" />
                		<h:inputText id="name" value="#{accountEntryTypeBean.name}" maxlength="256" required="true" styleClass="requiredFieldClass"/>
    	              </h:panelGroup>

              </td>
    </tr>
                                  
  
      <%-- Field: observations --%>
    <tr>
    	    		<td class="editLabelRW">${msg['accountEntryType.observations']}:</td>
    	      
      <td class="editFieldCell">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="observations" />
            <h:inputTextarea id="observations" value="#{accountEntryTypeBean.observations}" rows="5" cols="68"/>
          </h:panelGroup>

              </td>
    </tr>
                                  
  
      <%-- Field: customizableId --%>
    <tr>
    	    		<td class="editLabelRW">${msg['accountEntryType.customizableId']}:</td>
    	      
      <td class="editFieldCell">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="customizableId" />
                			<h:inputText id="customizableId" value="#{accountEntryTypeBean.customizableId}" size="10" />
    		          </h:panelGroup>

              </td>
    </tr>
                                  
  
      <%-- Ignored field: ownerId --%>
  
                                  
  
      <%-- Ignored field: departmentId --%>
  
                                  
  
      <%-- Ignored field: insertDate --%>
  
                                  
  
      <%-- Ignored field: updateDate --%>
  
                                              
    
      <%-- Field: group --%>
    <tr>
    	    		<td class="editLabelRW">*${msg['accountEntryType.group']}:</td>
    	      
      <td class="editFieldCell">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="group" />
            <h:selectOneMenu id="group" value="#{accountEntryTypeBean.group}"  required="true" styleClass="requiredFieldClass">
              <f:selectItems value="#{accountEntryTypeBean.groups}" />
              <f:converter converterId="autentia.EntityConverter"/>
            </h:selectOneMenu>
          </h:panelGroup>

              </td>
    </tr>
                                  
  
      <%-- Field: parent --%>
    <tr>
    	    		<td class="editLabelRW">${msg['accountEntryType.parent']}:</td>
    	      
      <td class="editFieldCell">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="parent" />
            <h:selectOneMenu id="parent" value="#{accountEntryTypeBean.parent}" >
              <f:selectItems value="#{accountEntryTypeBean.parents}" />
              <f:converter converterId="autentia.EntityConverter"/>
            </h:selectOneMenu>
          </h:panelGroup>

              </td>
    </tr>
                                      


<%-- accountEntryType - generated by stajanov (do not edit/delete) --%>

        </table>
        
      </h:form>
    </f:view>
    
  </body>
</html>  		

