<%--

    TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.
    Copyright (C) 2007 Autentia Real Bussiness Solution S.L.

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

--%>

<%-- 
 * TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.  
 *	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.					   
 *	
 * 	This program is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU General Public License
 * 	as published by the Free Software Foundation; either version 2
 * 	of the License, or (at your option) any later version.
 *
 * 	This program is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *
 * 	You should have received a copy of the GNU General Public License
 * 	along with this program; if not, write to the Free Software
 * 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 	Autentia Real Bussiness Solution S.L.
 * 	Tlf: +34 91 675 33 06, +34 655 99 11 72
 * 	Fax: +34 91 656 65 04
 * 	info@autentia.com																
 *
 --%>
<%@page language="java" contentType="text/html; charset=UTF-8"%>

<%@include file="/inc/tlibs.jsp" %>

<html>
  <head>
    <%@include file="/inc/uiCore.jsp" %>
  </head>	
  <body>
    
    <!-- searchAccountEntryType.jsp: generated by stajanov code generator -->
    <f:loadBundle basename="com.autentia.tnt.resources.messages" var="msg" />
    <i:location place="searchAccountEntryType" msg="${msg}"/> 
    
    <f:view>
      <%@include file="/inc/header.jsp" %>
      <h:form id="search" enctype="multipart/form-data">
        
        <%-- Header --%>
        <i:titleBar msg="${msg}">
          <h:commandLink action="#{accountEntryTypeBean.list}">
            <h:graphicImage title="#{msg.entityActions_run}"  value="/img/run.png" styleClass="titleImg" />
          </h:commandLink>
        </i:titleBar>
        
        <%-- Search form --%>
        <table class="searchTable" cellpadding="0" cellspacing="0">

          
      <%-- Ignored field: id --%>

                        
      <%-- Field: name --%>
    <tr>
      <td class="searchLabel">${msg['accountEntryType.name']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="name" />
            <h:selectBooleanCheckbox id="nameValid" value="#{accountEntryTypeBean.searchNameValid}" 
                                      onclick="setEnabled('search:name',this.checked)"/>
            <h:inputText id="name" value="#{accountEntryTypeBean.searchName}" size="70"/>
          </h:panelGroup>
          <script>
            setEnabled( 'search:name', ${accountEntryTypeBean.searchNameValid} )
          </script>

        
      </td>
    </tr>
                        
      <%-- Field: observations --%>
    <tr>
      <td class="searchLabel">${msg['accountEntryType.observations']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="observations" />
            <h:selectBooleanCheckbox id="observationsValid" value="#{accountEntryTypeBean.searchObservationsValid}" 
                                      onclick="setEnabled('search:observations',this.checked)"/>
            <h:inputText id="observations" value="#{accountEntryTypeBean.searchObservations}" size="70"/>
          </h:panelGroup>
          <script>
            setEnabled( 'search:observations', ${accountEntryTypeBean.searchObservationsValid} )
          </script>

        
      </td>
    </tr>
                        
      <%-- Field: customizableId --%>
    <tr>
      <td class="searchLabel">${msg['accountEntryType.customizableId']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="customizableId" />
            <h:selectBooleanCheckbox id="customizableIdValid" value="#{accountEntryTypeBean.searchCustomizableIdValid}" 
                                      onclick="setEnabled('search:customizableId',this.checked)"/>
            <h:inputText id="customizableId" value="#{accountEntryTypeBean.searchCustomizableId}" size="70"/>
          </h:panelGroup>
          <script>
            setEnabled( 'search:customizableId', ${accountEntryTypeBean.searchCustomizableIdValid} )
          </script>

        
      </td>
    </tr>
                        
      <%-- Ignored field: ownerId --%>

                        
      <%-- Ignored field: departmentId --%>

                        
      <%-- Ignored field: insertDate --%>

                        
      <%-- Ignored field: updateDate --%>

                                  
      <%-- Field: group --%>
    <tr>
      <td class="searchLabel">${msg['accountEntryType.group']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="group" />
            <h:selectBooleanCheckbox id="groupValid" value="#{accountEntryTypeBean.searchGroupValid}" 
                                      onclick="setEnabled('search:group',this.checked)"/>
            <h:selectOneMenu id="group" value="#{accountEntryTypeBean.searchGroup}" onclick="setEnabled('search:group',true)">
              <f:selectItems value="#{accountEntryTypeBean.groups}" />
              <f:converter converterId="autentia.EntityConverter"/>
            </h:selectOneMenu>
          </h:panelGroup>
          <script>
            setEnabled( 'search:group', ${accountEntryTypeBean.searchGroupValid} )
          </script>

        
      </td>
    </tr>
                        
      <%-- Field: parent --%>
    <tr>
      <td class="searchLabel">${msg['accountEntryType.parent']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="parent" />
            <h:selectBooleanCheckbox id="parentValid" value="#{accountEntryTypeBean.searchParentValid}" 
                                      onclick="setEnabled('search:parent',this.checked)"/>
            <h:selectOneMenu id="parent" value="#{accountEntryTypeBean.searchParent}" onclick="setEnabled('search:parent',true)">
              <f:selectItems value="#{accountEntryTypeBean.parents}" />
              <f:converter converterId="autentia.EntityConverter"/>
            </h:selectOneMenu>
          </h:panelGroup>
          <script>
            setEnabled( 'search:parent', ${accountEntryTypeBean.searchParentValid} )
          </script>

        
      </td>
    </tr>
                                
        </table>
        
      </h:form>
    </f:view>
    
  </body>
</html>  		
