<%--

    TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.
    Copyright (C) 2007 Autentia Real Bussiness Solution S.L.

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

--%>

<%-- 
 * TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.  
 *	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.					   
 *	
 * 	This program is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU General Public License
 * 	as published by the Free Software Foundation; either version 2
 * 	of the License, or (at your option) any later version.
 *
 * 	This program is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *
 * 	You should have received a copy of the GNU General Public License
 * 	along with this program; if not, write to the Free Software
 * 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 	Autentia Real Bussiness Solution S.L.
 * 	Tlf: +34 91 675 33 06, +34 655 99 11 72
 * 	Fax: +34 91 656 65 04
 * 	info@autentia.com																
 *
 --%>
<%@page language="java" contentType="text/html; charset=UTF-8"%>

<%@include file="/inc/tlibs.jsp"%>

<html>
<head>
<%@include file="/inc/uiCore.jsp"%>
</head>
<body>

<!-- searchTag.jsp: generated by stajanov code generator -->
<f:loadBundle basename="com.autentia.tnt.resources.messages" var="msg" />
<i:location place="searchTag" msg="${msg}" />

<f:view>
	<%@include file="/inc/header.jsp"%>
	<h:form id="search" enctype="multipart/form-data">

		<%-- Header --%>
		<i:titleBar msg="${msg}">
			<h:commandLink action="#{tagBean.list}">
				<h:graphicImage title="#{msg.entityActions_run}"
					value="/img/run.png" styleClass="titleImg" />
			</h:commandLink>
		</i:titleBar>

		<%-- Search form --%>
		<table class="searchTable" cellpadding="0" cellspacing="0">


			<%-- Field: name --%>
			<tr>
				<td class="searchLabel">${msg['tag.name']}:</td>
				<td class="searchFieldCell"><h:panelGroup>
					<h:message styleClass="error" showSummary="true" showDetail="false"
						for="name" />
					<h:selectBooleanCheckbox id="nameValid"
						value="#{tagBean.searchNameValid}"
						onclick="setEnabled('search:name',this.checked)" />
					<h:inputText id="name" value="#{tagBean.searchName}" size="70" />
				</h:panelGroup> <script>
            setEnabled( 'search:name', ${tagBean.searchNameValid} )
          </script></td>
			</tr>

			<%-- Field: description --%>
			<tr>
				<td class="searchLabel">${msg['tag.description']}:</td>
				<td class="searchFieldCell"><h:panelGroup>
					<h:message styleClass="error" showSummary="true" showDetail="false"
						for="description" />
					<h:selectBooleanCheckbox id="descriptionValid"
						value="#{tagBean.searchDescriptionValid}"
						onclick="setEnabled('search:description',this.checked)" />
					<h:inputText id="description" value="#{tagBean.searchDescription}"
						size="70" />
				</h:panelGroup> <script>
            setEnabled( 'search:description', ${tagBean.searchDescriptionValid} )
          </script></td>
			</tr>



			<%-- Field: contactTags --%>
			<tr>
				<td class="searchLabel">${msg['tag.contactTags']}:</td>
				<td class="searchFieldCell"><h:panelGroup>
					<h:message styleClass="error" showSummary="true" showDetail="false"
						for="contactTags" />
					<h:selectBooleanCheckbox id="contactTagsValid"
						value="#{tagBean.searchContactTagsValid}"
						onclick="setEnabled('search:contactTags',this.checked)"
						style="vertical-align: top;" />

					<h:selectManyListbox id="contactTags"
						value="#{tagBean.searchContactTags}"
						onclick="setEnabled('search:contactTags',true)" size="4">
						<f:selectItems value="#{tagBean.contactTagss}" />
						<f:converter converterId="autentia.EntityConverter" />
						<f:attribute
							name="com.autentia.tnt.converter.EntityConverter.valueClass"
							value="com.autentia.tnt.businessobject.Contact" />
					</h:selectManyListbox>

				</h:panelGroup> <script>
            setEnabled( 'search:contactTags', ${tagBean.searchContactTagsValid} )
          </script></td>
			</tr>

			<%-- Field: positionTags --%>
			<tr>
				<td class="searchLabel">${msg['tag.positionTags']}:</td>
				<td class="searchFieldCell"><h:panelGroup>
					<h:message styleClass="error" showSummary="true" showDetail="false"
						for="positionTags" />
					<h:selectBooleanCheckbox id="positionTagsValid"
						value="#{tagBean.searchPositionTagsValid}"
						onclick="setEnabled('search:positionTags',this.checked)"
						style="vertical-align: top;" />

					<h:selectManyListbox id="positionTags"
						value="#{tagBean.searchPositionTags}"
						onclick="setEnabled('search:positionTags',true)" size="4">
						<f:selectItems value="#{tagBean.positionTagss}" />
						<f:converter converterId="autentia.EntityConverter" />
						<f:attribute
							name="com.autentia.tnt.converter.EntityConverter.valueClass"
							value="com.autentia.tnt.businessobject.Position" />
					</h:selectManyListbox>

				</h:panelGroup> <script>
            setEnabled( 'search:positionTags', ${tagBean.searchPositionTagsValid} )
          </script></td>
			</tr>

			<%-- Field: departmentTags --%>
			<tr>
				<td class="searchLabel">${msg['tag.departmentTags']}:</td>
				<td class="searchFieldCell"><h:panelGroup>
					<h:message styleClass="error" showSummary="true" showDetail="false"
						for="departmentTags" />
					<h:selectBooleanCheckbox id="departmentTagsValid"
						value="#{tagBean.searchDepartmentTagsValid}"
						onclick="setEnabled('search:departmentTags',this.checked)"
						style="vertical-align: top;" />

					<h:selectManyListbox id="departmentTags"
						value="#{tagBean.searchDepartmentTags}"
						onclick="setEnabled('search:departmentTags',true)" size="4">
						<f:selectItems value="#{tagBean.departmentTagss}" />
						<f:converter converterId="autentia.EntityConverter" />
						<f:attribute
							name="com.autentia.tnt.converter.EntityConverter.valueClass"
							value="com.autentia.tnt.businessobject.Department" />
					</h:selectManyListbox>

				</h:panelGroup> <script>
            setEnabled( 'search:departmentTags', ${tagBean.searchDepartmentTagsValid} )
          </script></td>
			</tr>

			<%-- Field: organizationTags --%>
			<tr>
				<td class="searchLabel">${msg['tag.organizationTags']}:</td>
				<td class="searchFieldCell"><h:panelGroup>
					<h:message styleClass="error" showSummary="true" showDetail="false"
						for="organizationTags" />
					<h:selectBooleanCheckbox id="organizationTagsValid"
						value="#{tagBean.searchOrganizationTagsValid}"
						onclick="setEnabled('search:organizationTags',this.checked)"
						style="vertical-align: top;" />

					<h:selectManyListbox id="organizationTags"
						value="#{tagBean.searchOrganizationTags}"
						onclick="setEnabled('search:organizationTags',true)" size="4">
						<f:selectItems value="#{tagBean.organizationTagss}" />
						<f:converter converterId="autentia.EntityConverter" />
						<f:attribute
							name="com.autentia.tnt.converter.EntityConverter.valueClass"
							value="com.autentia.tnt.businessobject.Organization" />
					</h:selectManyListbox>

				</h:panelGroup> <script>
            setEnabled( 'search:organizationTags', ${tagBean.searchOrganizationTagsValid} )
          </script></td>
			</tr>
		</table>

	</h:form>
</f:view>

</body>
</html>
