<%--

    TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.
    Copyright (C) 2007 Autentia Real Bussiness Solution S.L.

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

--%>

<%-- 
 * TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.  
 *	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.					   
 *	
 * 	This program is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU General Public License
 * 	as published by the Free Software Foundation; either version 2
 * 	of the License, or (at your option) any later version.
 *
 * 	This program is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *
 * 	You should have received a copy of the GNU General Public License
 * 	along with this program; if not, write to the Free Software
 * 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 	Autentia Real Bussiness Solution S.L.
 * 	Tlf: +34 91 675 33 06, +34 655 99 11 72
 * 	Fax: +34 91 656 65 04
 * 	info@autentia.com																
 *
 --%>
<%@page language="java" contentType="text/html; charset=UTF-8"%>

<%@include file="/inc/tlibs.jsp" %>

<html>
  <head>
    <%@include file="/inc/uiCore.jsp" %>
  </head>	
  <body>

    <!-- creditTitles.jsp: generated by stajanov code generator -->
    <f:loadBundle basename="com.autentia.tnt.resources.messages" var="msg" />
    <i:location place="creditTitles" msg="${msg}"/> 
    
    <f:view>
     <%@include file="/inc/header.jsp" %>
      <h:form id="creditTitles">
        
        <%-- Header --%>
        <i:titleBar msg="${msg}">
          <h:commandLink action="#{creditTitleBean.search}">
            <h:graphicImage rendered="#{ creditTitleBean.search.searchActive}" title="#{msg.entityActions_filtered}"  value="/img/search_applied.gif" styleClass="titleImg" />
            <h:graphicImage rendered="#{!creditTitleBean.search.searchActive}" title="#{msg.entityActions_search}"    value="/img/search.gif"         styleClass="titleImg" />
          </h:commandLink>
           <h:commandLink action="#{creditTitleBean.reset}">
            <h:graphicImage rendered="#{creditTitleBean.search.searchActive}" title="#{msg.entityActions_reset}"  value="/img/eraser.png" styleClass="titleImg" />           
          </h:commandLink>
          <h:commandLink action="#{creditTitleBean.create}" rendered="#{creditTitleBean.createAvailable}">
            <h:graphicImage title="#{msg.entityActions_create}"  value="/img/new.gif" styleClass="titleImg" />
          </h:commandLink>
        </i:titleBar>
        
        
        <%-- List of creditTitles --%>
        <t:dataTable id="list" var="creditTitle" value="#{creditTitleBean.all}" preserveDataModel="false" 
            cellpadding="0" cellspacing="0" styleClass="listTable" 
            headerClass="listHeaderCell" footerClass="listFooter" 
            rows="#{settingBean.mySettings.listSize}" rowClasses="listRowO,listRowE"
            columnClasses="listCmdCell,listCreditTitleId,listCreditTitleNumber,listCreditTitleConcept,listCreditTitleCreditTitleState,listCreditTitleCreditTitleType,listCreditTitleIssueDate,listCreditTitleExpirationDate,listCreditTitleObservations,listCreditTitleOwnerId,listCreditTitleDepartmentId,listCreditTitleInsertDate,listCreditTitleUpdateDate,listCreditTitleOrganization"
            sortColumn="#{creditTitleBean.sortColumn}" sortAscending="#{creditTitleBean.sortAscending}"
	    rowOnMouseOver="this.savedClassName=this.className;this.className='listRowSel';" 
	    rowOnMouseOut="this.className=this.savedClassName;">
          
          <%-- Commands --%>
          <h:column>
            <f:facet name="header">
              <f:verbatim>-</f:verbatim>
            </f:facet>
            <t:commandLink action="#{creditTitleBean.detail}" immediate="true">
              <f:param name="rowid" value="#{creditTitle.id}" />
              <h:graphicImage title="#{msg.entityActions_detail}"  value="/img/detail.gif" styleClass="cmdImg" />
            </t:commandLink>
          </h:column>

      <%-- Field: number --%>
    <h:column>
      <f:facet name="header">
      	        <t:commandSortHeader styleClass="listHeader" columnName="number">
                 <f:facet name="ascending">
            <t:graphicImage value="/img/ascending-arrow.gif" border="0" />
          </f:facet>
          <f:facet name="descending">
            <t:graphicImage value="/img/descending-arrow.gif" border="0" />
          </f:facet>
          <f:verbatim>${msg['creditTitle.number']}</f:verbatim>
        </t:commandSortHeader>
      </f:facet>

      <t:commandLink action="#{creditTitleBean.detail}" immediate="true">
	<f:param name="rowid" value="#{creditTitle.id}" />
		  <%-- String field --%>
	  <h:outputText value="#{creditTitle.number}" />
	      </t:commandLink>

    </h:column>

      <%-- Field: amount --%>
    <h:column>
      <f:facet name="header">
      	        <t:commandSortHeader styleClass="listHeader" columnName="amount">
                 <f:facet name="ascending">
            <t:graphicImage value="/img/ascending-arrow.gif" border="0" />
          </f:facet>
          <f:facet name="descending">
            <t:graphicImage value="/img/descending-arrow.gif" border="0" />
          </f:facet>
          <f:verbatim>${msg['creditTitle.amount']}</f:verbatim>
        </t:commandSortHeader>
      </f:facet>

      <t:commandLink action="#{creditTitleBean.detail}" immediate="true">
	<f:param name="rowid" value="#{creditTitle.id}" />
		  <%-- String field --%>
	  <h:outputText value="#{creditTitle.amount}" />
	      </t:commandLink>

    </h:column>  

      <%-- Field: concept --%>
    <h:column>
      <f:facet name="header">
      	        <t:commandSortHeader styleClass="listHeader" columnName="concept">
                 <f:facet name="ascending">
            <t:graphicImage value="/img/ascending-arrow.gif" border="0" />
          </f:facet>
          <f:facet name="descending">
            <t:graphicImage value="/img/descending-arrow.gif" border="0" />
          </f:facet>
          <f:verbatim>${msg['creditTitle.concept']}</f:verbatim>
        </t:commandSortHeader>
      </f:facet>

      <t:commandLink action="#{creditTitleBean.detail}" immediate="true">
	<f:param name="rowid" value="#{creditTitle.id}" />
		  <%-- String field --%>
	  <h:outputText value="#{creditTitle.concept}" />
	      </t:commandLink>

    </h:column>
  

      <%-- Field: creditTitleState --%>
    <h:column>
      <f:facet name="header">
      	        <t:commandSortHeader styleClass="listHeader" columnName="state">
                 <f:facet name="ascending">
            <t:graphicImage value="/img/ascending-arrow.gif" border="0" />
          </f:facet>
          <f:facet name="descending">
            <t:graphicImage value="/img/descending-arrow.gif" border="0" />
          </f:facet>
          <f:verbatim>${msg['creditTitle.state']}</f:verbatim>
        </t:commandSortHeader>
      </f:facet>

      <t:commandLink action="#{creditTitleBean.detail}" immediate="true">
	<f:param name="rowid" value="#{creditTitle.id}" />
		  <%-- Enumerated field --%>
	  <h:outputText value="#{creditTitle.state}">
	    <f:converter converterId="autentia.EnumTranslator"/>
	  </h:outputText>
	      </t:commandLink>

    </h:column>
  

      <%-- Field: creditTitleType --%>
    <h:column>
      <f:facet name="header">
      	        <t:commandSortHeader styleClass="listHeader" columnName="type">
                 <f:facet name="ascending">
            <t:graphicImage value="/img/ascending-arrow.gif" border="0" />
          </f:facet>
          <f:facet name="descending">
            <t:graphicImage value="/img/descending-arrow.gif" border="0" />
          </f:facet>
          <f:verbatim>${msg['creditTitle.type']}</f:verbatim>
        </t:commandSortHeader>
      </f:facet>

      <t:commandLink action="#{creditTitleBean.detail}" immediate="true">
	<f:param name="rowid" value="#{creditTitle.id}" />
		  <%-- Enumerated field --%>
	  <h:outputText value="#{creditTitle.type}">
	    <f:converter converterId="autentia.EnumTranslator"/>
	  </h:outputText>
	      </t:commandLink>

    </h:column>
  

      <%-- Field: issueDate --%>
    <h:column>
      <f:facet name="header">
      	        <t:commandSortHeader styleClass="listHeader" columnName="issueDate">
                 <f:facet name="ascending">
            <t:graphicImage value="/img/ascending-arrow.gif" border="0" />
          </f:facet>
          <f:facet name="descending">
            <t:graphicImage value="/img/descending-arrow.gif" border="0" />
          </f:facet>
          <f:verbatim>${msg['creditTitle.issueDate']}</f:verbatim>
        </t:commandSortHeader>
      </f:facet>

      <t:commandLink action="#{creditTitleBean.detail}" immediate="true">
	<f:param name="rowid" value="#{creditTitle.id}" />
		  <%-- Date field --%>
	  <h:outputText value="#{creditTitle.issueDate}" converter="autentia.dateConverter"/>

	      </t:commandLink>

    </h:column>
  

      <%-- Field: expirationDate --%>
    <h:column>
      <f:facet name="header">
      	        <t:commandSortHeader styleClass="listHeader" columnName="expirationDate">
                 <f:facet name="ascending">
            <t:graphicImage value="/img/ascending-arrow.gif" border="0" />
          </f:facet>
          <f:facet name="descending">
            <t:graphicImage value="/img/descending-arrow.gif" border="0" />
          </f:facet>
          <f:verbatim>${msg['creditTitle.expirationDate']}</f:verbatim>
        </t:commandSortHeader>
      </f:facet>

      <t:commandLink action="#{creditTitleBean.detail}" immediate="true">
	<f:param name="rowid" value="#{creditTitle.id}" />
		  <%-- Date field --%>
	  <h:outputText value="#{creditTitle.expirationDate}" converter="autentia.dateConverter"/>

	      </t:commandLink>

    </h:column>
 
      <%-- Field: organization --%>
    <h:column>
      <f:facet name="header">
      	        <t:commandSortHeader styleClass="listHeader" columnName="organization">
                 <f:facet name="ascending">
            <t:graphicImage value="/img/ascending-arrow.gif" border="0" />
          </f:facet>
          <f:facet name="descending">
            <t:graphicImage value="/img/descending-arrow.gif" border="0" />
          </f:facet>
          <f:verbatim>${msg['creditTitle.organization']}</f:verbatim>
        </t:commandSortHeader>
      </f:facet>

      <t:commandLink action="#{creditTitleBean.detail}" immediate="true">
	<f:param name="rowid" value="#{creditTitle.id}" />
		  <%-- Referenced field --%>
	  <h:outputText value="#{creditTitle.organization.name}" />

	      </t:commandLink>

    </h:column>
  
        </t:dataTable>
          
        <%-- Paginator control --%>
        <%@include file="/inc/paginator.jsp" %>
        
      </h:form>
    </f:view>
    
  </body>
</html>  		

