<%--

    TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.
    Copyright (C) 2007 Autentia Real Bussiness Solution S.L.

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

--%>

<%@page language="java" contentType="text/html; charset=UTF-8"%>

<%@include file="/inc/tlibs.jsp" %>

<html>
  <head>
    <%@include file="/inc/uiCore.jsp" %>
  </head>	
  <body>
    
    <!-- editBill.jsp: generated by stajanov code generator -->
    <f:loadBundle basename="com.autentia.tnt.resources.messages" var="msg" />
    <i:location place="detailBill" msg="${msg}"/> 
    
    <f:view>
        <%@include file="/inc/header.jsp" %>
      <h:form id="bill" enctype="multipart/form-data">
        
        <%-- Header --%>
        <i:titleBar name="${billBean.name}" msg="${msg}">
          <t:commandLink action="#{billBean.edit}" immediate="true">
              <f:param name="rowid" value="#{billBean.id}" />
              <h:graphicImage title="#{msg.entityActions_edit}"  value="/img/edit.gif" styleClass="cmdImg" />
            </t:commandLink>
          <h:commandLink action="#{billBean.list}" immediate="true">
            <h:graphicImage title="#{msg.entityActions_back}"  value="/img/back.gif" styleClass="titleImg" />
          </h:commandLink>
        </i:titleBar>


        <%-- Detail form --%>
        <table class="detailTable" cellpadding="0" cellspacing="0">

            
  
      <%-- Ignored field: id --%>
    
      <%-- Field: number --%>
    <tr>
   		<td class="detailLabelRW">${msg['bill.number']}:</td>
 
        <td class="detailFieldCell">
        
         	       <h:outputText value="#{billBean.number}" />
 	          </td>
    </tr>
    
     <%-- Field: provider --%>
    <tr>
   		<td class="detailLabelRW">${msg['bill.provider']}:</td>
 
        <td class="detailFieldCell">
        
         	    	<h:outputText value="#{billBean.provider.name}"/>
 	          </td>
    </tr>
    
     <%-- Field: organization --%>
          <tr>
            <td class="editLabelRW">${msg['bill.organization']}:</td>
     
            <td class="editFieldCell">
				<h:outputText value="#{billBean.selectedOrganization.name}" />
          </tr>
    
      <%-- Field: project --%>
    <tr>
   		<td class="detailLabelRW">${msg['bill.project']}:</td>
 
        <td class="detailFieldCell">
        
         	    	<h:outputText value="#{billBean.project.name}"/>
 	          </td>
    </tr>    
    
                              
  
      <%-- Field: name --%>
    <tr>
   		<td class="detailLabelRW">${msg['bill.name']}:</td>
 
        <td class="detailFieldCell">
        
         	       <h:outputText value="#{billBean.name}" />
 	          </td>
    </tr>               
    
                                
  
      <%-- Field: orderNumber --%>
    <tr>
   		<td class="detailLabelRW">${msg['bill.orderNumber']}:</td>
 
        <td class="detailFieldCell">
        
         	       <h:outputText value="#{billBean.orderNumber}" />
 	          </td>
    </tr>    
    
                                       
                            
  
      <%-- Field: contact --%>
    <tr>
   		<td class="detailLabelRW">${msg['bill.contact']}:</td>
 
        <td class="detailFieldCell">
        
         	    	<h:outputText value="#{billBean.contact.name}"/>
 	          </td>
    </tr>
  
  
    <tr>
            <td class="editLabelRW">${msg['bill.account']}:</td>
            <td class="editFieldCell">
	
	              <h:outputText value="#{billBean.selectedAccount.name}"/>
 	          </td>
          </tr>
    
                                                      
                       
  
      <%-- Field: breakDown --%>
    <tr>
   		<td class="detailLabelRW">${msg['bill.breakDown']}:</td>
 
        <td class="detailFieldCell">
        
                  			        <%@include file="inlineDetailBillBreakDown.jsp"%>
          	 	          </td>
    </tr>
  
    <%-- Field: amount --%>
    <tr>
   		<td class="detailLabelRW">${msg['bill.total']}:</td>
 
        <td class="detailFieldCell">
        
         	       <h:outputText value="#{billBean.total}" />
 	          </td>
    </tr>
  
  
      <%-- Field: creationDate --%>
    <tr>
   		<td class="detailLabelRW">${msg['bill.creationDate']}:</td>
 
        <td class="detailFieldCell">
        
         	    	<h:outputText value="#{billBean.creationDate}" converter="autentia.dateConverter" />
 	          </td>
    </tr>
                            
  
      <%-- Field: startBillDate --%>
    <tr>
   		<td class="detailLabelRW">${msg['bill.startBillDate']}:</td>
 
        <td class="detailFieldCell">
        
         	    	<h:outputText value="#{billBean.startBillDate}" converter="autentia.dateConverter" />
 	          </td>
    </tr>
                            
  
      <%-- Field: endBillDate --%>
    <tr>
   		<td class="detailLabelRW">${msg['bill.endBillDate']}:</td>
 
        <td class="detailFieldCell">
        
         	    	<h:outputText value="#{billBean.endBillDate}" converter="autentia.dateConverter" />
 	          </td>
    </tr>
                            
  
      <%-- Field: paymentMode --%>
    <tr>
   		<td class="detailLabelRW">${msg['bill.paymentMode']}:</td>
 
        <td class="detailFieldCell">
        
                	<h:outputText value="#{billBean.paymentModeFormatted}" />
              </td>
    </tr>
                            
  
      <%-- Field: state --%>
    <tr>
   		<td class="detailLabelRW">${msg['bill.state']}:</td>
 
        <td class="detailFieldCell">
        
                	<h:outputText value="#{billBean.stateFormatted}" />
              </td>
    </tr>
                            

                            
  
      <%-- Field: file --%>
    <tr>
   		<td class="detailLabelRW">${msg['bill.file']}:</td>
 
        <td class="detailFieldCell">
        
                  <i:fileLink type="bill" objectId="${billBean.id}" file="${billBean.file}" /> 
     	      </td>
    </tr>
                            
  
      <%-- Ignored field: fileMime --%>
                            
  
      <%-- Field: observations --%>
    <tr>
   		<td class="detailLabelRW">${msg['bill.observations']}:</td>
 
        <td class="detailFieldCell">
        
         	       <h:outputText value="#{billBean.observations}" />
 	          </td>
    </tr>
                            
  
      <%-- Ingore field: billType --%>

                            
  
    
                            
  
      <%-- Ignored field: entriesNumber --%>


              
        </table>
        
        <%-- Field: versiones --%>
		  <h:panelGrid rendered="#{billBean.id!=null}" columnClasses="detailLabelRW">
		  <h:panelGroup styleClass="detailLabelRW">	  
		  <h:outputText  value="#{msg['bill.entries']}" />
           </h:panelGroup>                 
          <h:panelGroup>
                  <%@include file="inlineDetailShowEntries.jsp"%>
          </h:panelGroup>
		 </h:panelGrid> 

      </h:form>
    </f:view>
    
  </body>
</html>  		
<%-- bill - generated by stajanov (do not edit/delete) --%>
