<%--

    TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.
    Copyright (C) 2007 Autentia Real Bussiness Solution S.L.

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

--%>

<%@page language="java" contentType="text/html; charset=UTF-8"%>

<%@include file="/inc/tlibs.jsp" %>

<html>
  <head>
    <%@include file="/inc/uiCore.jsp" %>
  </head>	
  <body>
    
    <!-- editIdea.jsp: generated by stajanov code generator -->
    <f:loadBundle basename="com.autentia.tnt.resources.messages" var="msg" />
    <i:location place="editFinancialRatio" msg="${msg}"/> 
    
    <f:view>
        <%@include file="/inc/header.jsp" %>
      <h:form id="financialRatio" enctype="multipart/form-data">
        
        <%-- Header --%>
        <i:titleBar name="${financialRatioBean.title}" msg="${msg}">
          <h:commandLink action="#{financialRatioBean.save}">
            <h:graphicImage value="/img/save.gif" styleClass="titleImg" />
          </h:commandLink>
          <h:commandLink action="#{financialRatioBean.delete}" onclick="if( !confirm('#{msg['question.confirmDelete']}') ) return false;">
            <h:graphicImage value="/img/delete.gif" styleClass="titleImg" />
          </h:commandLink>
          <h:commandLink action="#{financialRatioBean.list}" immediate="true">
            <h:graphicImage value="/img/back.gif" styleClass="titleImg" />
          </h:commandLink>
          <h:commandLink action="#{financialRatioBean.compareRatioForm}" immediate="true">
           <h:outputText value="#{msg['financialRatio.compare']}" />
          </h:commandLink>
        </i:titleBar>
        
        <%-- Edition form --%>
        <table class="editTable" cellpadding="0" cellspacing="0">


<%-- FinancialRatio - generated by stajanov (do not edit/delete) --%>







              
  
      <%-- Ignored field: id --%>
  
                              
    
      <%-- Field: title --%>
    <tr>
    	    		<td class="editLabelRatiosW">*${msg['financialRatio.title']}:</td>
    	      
      <td class="editFieldCell">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="title" />
                		<h:inputText id="title" value="#{financialRatioBean.title}" size="70" required="true" styleClass="requiredFieldClass"/>
    	              </h:panelGroup>

              </td>
    </tr>
    
    
                              
    
      <%-- Field: ratioDate --%>
    <tr>
    	    		<td class="editLabelRatiosW">*${msg['financialRatio.ratioDate']}:</td>
    	      
      <td class="editFieldCell">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="ratioDate" />
            <t:inputCalendar id="ratioDate" value="#{financialRatioBean.ratioDate}"  required="true" styleClass="requiredFieldClass"
                             renderAsPopup="true" popupDateFormat="d/MM/yyyy" renderPopupButtonAsImage="true" 
                             popupTodayString="#{msg['calendar.today']}" popupWeekString="#{msg['calendar.week']}"
                             >
				<f:validator validatorId="autentia.dateValidator"/>
			</t:inputCalendar>
          </h:panelGroup>

              </td>
    </tr>
    
    <tr>
    <td valign="top">
    <table class="editTable" cellpadding="0" cellspacing="0">
    
                              
    <tr>
    	    		<td class="detailLabelRatiosTitle" colspan="2">${msg['financialRatio.asset']}</td>
    </tr> 	    		
   
    
    
      <%-- Field: banksAccounts --%>
    <tr>
    	    		<td class="detailLabelRatiosAsset">*${msg['financialRatio.banksAccounts']}:</td>
    	      
      <td class="detailLabelRatiosAsset">
                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="banksAccounts" />
                			<h:inputText id="banksAccounts" value="#{financialRatioBean.banksAccounts}" size="12" required="true" styleClass="requiredFieldClass">
                				<f:validator validatorId="autentia.genericMoneyValidator" />
	                				<f:attribute name="scale" value="2" />
									<f:attribute name="maxSize" value="10" />
                			</h:inputText>
                			
    		          </h:panelGroup>

              </td>
    </tr>
                              
    
      <%-- Field: customers --%>
    <tr>
    	    		<td class="detailLabelRatiosAsset">*${msg['financialRatio.customers']}:</td>
    	      
      <td class="detailLabelRatiosAsset">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="customers" />
                			<h:inputText id="customers" value="#{financialRatioBean.customers}" size="12"  required="true" styleClass="requiredFieldClass">
                			<f:validator validatorId="autentia.genericMoneyValidator" />
	                				<f:attribute name="scale" value="2" />
									<f:attribute name="maxSize" value="10" />
                			</h:inputText>
    		          </h:panelGroup>

              </td>
    </tr>
                              
    
      <%-- Field: stocks --%>
    <tr>
    	    		<td class="detailLabelRatiosAsset">*${msg['financialRatio.stocks']}:</td>
    	      
      <td class="detailLabelRatiosAsset">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="stocks" />
                			<h:inputText id="stocks" value="#{financialRatioBean.stocks}" size="12"  required="true" styleClass="requiredFieldClass">
                			<f:validator validatorId="autentia.genericMoneyValidator" />
	                				<f:attribute name="scale" value="2" />
									<f:attribute name="maxSize" value="10" />
                			</h:inputText>
    		          </h:panelGroup>

              </td>
    </tr>
                              
    <%-- Field: netAsset --%>
    <tr>
	<td class="detailLabelRatiosAsset">${msg['financialRatio.netAsset']}:</td>
	<td class="detailLabelRatiosAsset">
	
         	       <h:outputText value="#{financialRatioBean.netAsset}">
         	       <f:convertNumber maxFractionDigits="2" type="currency" currencySymbol="€"/>
         	       </h:outputText>
 	      </td>
    </tr>
    
      <%-- Field: amortizations --%>
    <tr>
    	    		<td class="detailLabelRatiosAsset">*${msg['financialRatio.amortizations']}:</td>
    	      
      <td class="detailLabelRatiosAsset">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="amortizations" />
                			<h:inputText id="amortizations" value="#{financialRatioBean.amortizations}" size="12"  required="true" styleClass="requiredFieldClass">
                			<f:validator validatorId="autentia.genericMoneyValidator" />
	                				<f:attribute name="scale" value="2" />
									<f:attribute name="maxSize" value="10" />								
                			</h:inputText>
    		          </h:panelGroup>

              </td>
    </tr>
                              
    
      <%-- Field: infrastructures --%>
    <tr>
    	    		<td class="detailLabelRatiosAsset">*${msg['financialRatio.infrastructures']}:</td>
    	      
      <td class="detailLabelRatiosAsset">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="infrastructures" />
                			<h:inputText id="infrastructures" value="#{financialRatioBean.infrastructures}" size="12"  required="true" styleClass="requiredFieldClass">
                			<f:validator validatorId="autentia.genericMoneyValidator" />
	                				<f:attribute name="scale" value="2" />
									<f:attribute name="maxSize" value="10" />
                			</h:inputText>
    		          </h:panelGroup>

              </td>
    </tr>
    
    <%-- Field: totalAsset --%>
    <tr>
	<td class="detailLabelRatiosAsset">${msg['financialRatio.totalAsset']}:</td>
	<td class="detailLabelRatiosAsset">
         	       <h:outputText value="#{financialRatioBean.totalAsset}" >
         	        <f:convertNumber maxFractionDigits="2" type="currency" currencySymbol="€"/>
         	       </h:outputText>
         	       
 	      </td>
    </tr>
    </table>
    </td>
    
     <td valign="top">
    <table class="editTable" cellpadding="0" cellspacing="0">    
        
                       
     <tr>
    	    		<td class="detailLabelRatiosTitle" colspan="2">${msg['financialRatio.liability']}</td>
    </tr>
      <%-- Field: shortTermLiability --%>
    <tr>
    	    		<td class="detailLabelRatiosLia">*${msg['financialRatio.shortTermLiability']}:</td>
    	      
      <td class="detailLabelRatiosLia">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="shortTermLiability" />
                			<h:inputText id="shortTermLiability" value="#{financialRatioBean.shortTermLiability}" size="12"  required="true" styleClass="requiredFieldClass">
                			<f:validator validatorId="autentia.genericMoneyValidator" />
	                				<f:attribute name="scale" value="2" />
									<f:attribute name="maxSize" value="10" />
                			</h:inputText>
    		          </h:panelGroup>

              </td>
    </tr>
                              
    
      <%-- Field: obligationBond --%>
    <tr>
    	    		<td class="detailLabelRatiosLia">*${msg['financialRatio.obligationBond']}:</td>
    	      
      <td class="detailLabelRatiosLia">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="obligationBond" />
                			<h:inputText id="obligationBond" value="#{financialRatioBean.obligationBond}" size="12"  required="true" styleClass="requiredFieldClass">
                			<f:validator validatorId="autentia.genericMoneyValidator" />
	                				<f:attribute name="scale" value="2" />
									<f:attribute name="maxSize" value="10" />
                			</h:inputText>
    		          </h:panelGroup>

              </td>
    </tr>
    
     <%-- Field: totalOtherResources --%>
    <tr>
	<td class="detailLabelRatiosLia">${msg['financialRatio.totalOtherResources']}:</td>
	<td class="detailLabelRatiosLia">
         	       <h:outputText value="#{financialRatioBean.totalOtherResources}" >
						<f:convertNumber maxFractionDigits="2" type="currency" currencySymbol="€"/>
         	       </h:outputText>
 	      </td>
    </tr>
                              
    
      <%-- Field: capital --%>
    <tr>
    	    		<td class="detailLabelRatiosLia">*${msg['financialRatio.capital']}:</td>
    	      
      <td class="detailLabelRatiosLia">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="capital" />
                			<h:inputText id="capital" value="#{financialRatioBean.capital}" size="12"  required="true" styleClass="requiredFieldClass">
                			<f:validator validatorId="autentia.genericMoneyValidator" />
	                				<f:attribute name="scale" value="2" />
									<f:attribute name="maxSize" value="10" />
                			</h:inputText>
    		          </h:panelGroup>

              </td>
    </tr>
                              
    
      <%-- Field: reserves --%>
    <tr>
    	    		<td class="detailLabelRatiosLia">*${msg['financialRatio.reserves']}:</td>
    	      
      <td class="detailLabelRatiosLia">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="reserves" />
                			<h:inputText id="reserves" value="#{financialRatioBean.reserves}" size="12"  required="true" styleClass="requiredFieldClass">
                			<f:validator validatorId="autentia.genericMoneyValidator" />
	                				<f:attribute name="scale" value="2" />
									<f:attribute name="maxSize" value="10" />

                			</h:inputText>
    		          </h:panelGroup>

              </td>
    </tr>
    <%-- Field: totalOurResources --%>
    <tr>
	<td class="detailLabelRatiosLia">${msg['financialRatio.totalOurResources']}:</td>
	<td class="detailLabelRatiosLia">
         	       <h:outputText value="#{financialRatioBean.totalOurResources}">
         	       <f:convertNumber maxFractionDigits="2" type="currency" currencySymbol="€"/>
         	       </h:outputText>
 	      </td>
    </tr>
                            
  
      <%-- Field: totalLiability --%>
    <tr>
	<td class="detailLabelRatiosLia">${msg['financialRatio.totalLiability']}:</td>
	<td class="detailLabelRatiosLia">
         	       <h:outputText value="#{financialRatioBean.totalLiability}">
         	      <f:convertNumber maxFractionDigits="2" type="currency" currencySymbol="€"/>
         	       </h:outputText>
 	      </td>
    </tr>
    </table>
    </td>
    </tr>   
                          
    <tr>
    	    		<td class="detailLabelRatiosTitle" colspan="4">${msg['financialRatio.results']}</td>
    </tr>
    <tr>
    <td valign="top">
    <table class="editTable" cellpadding="0" cellspacing="0">   
    
      <%-- Field: incomes --%>
    <tr>
    	    		<td class="detailLabelRatiosRes">*${msg['financialRatio.incomes']}:</td>
    	      
      <td class="detailLabelRatiosRes">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="incomes" />
                			<h:inputText id="incomes" value="#{financialRatioBean.incomes}" size="12"  required="true" styleClass="requiredFieldClass">
                			<f:validator validatorId="autentia.genericMoneyValidator" />
	                				<f:attribute name="scale" value="2" />
									<f:attribute name="maxSize" value="10" />

                			</h:inputText>
    		          </h:panelGroup>

              </td>
    </tr>
                              
    
      <%-- Field: expenses --%>
    <tr>
    	    		<td class="detailLabelRatiosRes">*${msg['financialRatio.expenses']}:</td>
    	      
      <td class="detailLabelRatiosRes">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="expenses" />
                			<h:inputText id="expenses" value="#{financialRatioBean.expenses}" size="12"  required="true" styleClass="requiredFieldClass">
                			<f:validator validatorId="autentia.genericMoneyValidator" />
	                				<f:attribute name="scale" value="2" />
									<f:attribute name="maxSize" value="10" />

                			</h:inputText>
    		          </h:panelGroup>

              </td>
    </tr>
         <%-- Field: margin --%>
    <tr>
	<td class="detailLabelRatiosRes">${msg['financialRatio.margin']}:</td>
	<td class="detailLabelRatiosRes">
         	       <h:outputText value="#{financialRatioBean.margin}">
         	        <f:convertNumber maxFractionDigits="2" type="currency" currencySymbol="€"/>
         	       </h:outputText>
 	      </td>
    </tr>                     
    
      <%-- Field: otherExploitationExpenses --%>
    <tr>
    	    		<td class="detailLabelRatiosRes">*${msg['financialRatio.otherExploitationExpenses']}:</td>
    	      
      <td class="detailLabelRatiosRes">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="otherExploitationExpenses" />
                			<h:inputText id="otherExploitationExpenses" value="#{financialRatioBean.otherExploitationExpenses}" size="12"  required="true" styleClass="requiredFieldClass">
                			<f:validator validatorId="autentia.genericMoneyValidator" />
	                				<f:attribute name="scale" value="2" />
									<f:attribute name="maxSize" value="10" />

                			</h:inputText>
    		          </h:panelGroup>

              </td>
    </tr>
    <%-- Field: bait --%>
    <tr>
	<td class="detailLabelRatiosRes">${msg['financialRatio.bait']}:</td>
	<td class="detailLabelRatiosRes">
         	       <h:outputText value="#{financialRatioBean.bait}">
         	       <f:convertNumber maxFractionDigits="2" type="currency" currencySymbol="€"/>
         	       </h:outputText>
 	      </td>
    </tr>
                              
    
      
    
   </table>
    </td>
    <td valign="top">
    
    <table class="editTable" cellpadding="0" cellspacing="0">                          
    <%-- Field: financialExpenses --%>
    <tr>
    	    		<td class="detailLabelRatiosRes">*${msg['financialRatio.financialExpenses']}:</td>
    	      
      <td class="detailLabelRatiosRes">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="financialExpenses" />
                			<h:inputText id="financialExpenses" value="#{financialRatioBean.financialExpenses}" size="12"  required="true" styleClass="requiredFieldClass">
                			<f:validator validatorId="autentia.genericMoneyValidator" />
	                				<f:attribute name="scale" value="2" />
									<f:attribute name="maxSize" value="10" />
                			</h:inputText>
    		          </h:panelGroup>

              </td>
    </tr>
    
    <tr>
	<td class="detailLabelRatiosRes">${msg['financialRatio.bat']}:</td>
	<td class="detailLabelRatiosRes">
         	       <h:outputText value="#{financialRatioBean.bat}" >
         	       <f:convertNumber maxFractionDigits="2" type="currency" currencySymbol="€"/>
         	       </h:outputText>
 	      </td>
    </tr>
      <%-- Field: taxes --%>
    <tr>
    	    		<td class="detailLabelRatiosRes">*${msg['financialRatio.taxes']}:</td>
    	      
      <td class="detailLabelRatiosRes">

                  <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="taxes" />
                			<h:inputText id="taxes" value="#{financialRatioBean.taxes}" size="12"  required="true" styleClass="requiredFieldClass">
                			<f:validator validatorId="autentia.genericMoneyValidator" />
	                				<f:attribute name="scale" value="2" />
									<f:attribute name="maxSize" value="10" />

                			</h:inputText>
    		          </h:panelGroup>

              </td>
    </tr>
   <%-- Field: bdt --%>
    <tr>
	<td class="detailLabelRatiosRes">${msg['financialRatio.bdt']}:</td>
	<td class="detailLabelRatiosRes">
         	       <h:outputText value="#{financialRatioBean.bdt}" >
         	       <f:convertNumber maxFractionDigits="2" type="currency" currencySymbol="€"/>
         	       </h:outputText>
 	      </td>
    </tr>
         
      <%-- Field: baitd --%>
    <tr>
	<td class="detailLabelRatiosRes">${msg['financialRatio.baitd']}:</td>
	<td class="detailLabelRatiosRes">
         	       <h:outputText value="#{financialRatioBean.baitd}" >
         	       <f:convertNumber maxFractionDigits="2" type="currency" currencySymbol="€"/>
         	       </h:outputText>
 	      </td>
    </tr>        
     </table>
     </td>
     </tr>                         
  	
  	<tr>
    <td valign="top">
    <table class="editTable" cellpadding="0" cellspacing="0"> 
    	<%@include file="inlineLiquidity.jsp"%>
    </table>
    </td>
    <td valign="top">
    <table class="editTable" cellpadding="0" cellspacing="0"> 
    	<%@include file="inlineSolvency.jsp"%>
    </table>
    </td>
    </tr>
    
    <tr>
    <td valign="top">
    <table class="editTable" cellpadding="0" cellspacing="0"> 
    	<%@include file="inlineEfficiency.jsp"%>
    </table>
    </td>
    <td valign="top">
    <table class="editTable" cellpadding="0" cellspacing="0"> 
    	<%@include file="inlineProfitability.jsp"%>
    </table>
    </td>
    </tr>  
  	
  	
  	
      <%-- Ignored field: netAsset --%>
  
                              
  
      <%-- Ignored field: ownerId --%>
  
                              
  
      <%-- Ignored field: departmentId --%>
  
                              
  
      <%-- Ignored field: insertDate --%>
  
                              
  
      <%-- Ignored field: updateDate --%>
  
                                                  

<%-- FinancialRatio - generated by stajanov (do not edit/delete) --%>


</table>                  
        
      </h:form>
    </f:view>
    
  </body>
</html>  	
