<%--

    TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.
    Copyright (C) 2007 Autentia Real Bussiness Solution S.L.

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

--%>

<%-- 
 * TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.  
 *	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.					   
 *	
 * 	This program is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU General Public License
 * 	as published by the Free Software Foundation; either version 2
 * 	of the License, or (at your option) any later version.
 *
 * 	This program is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *
 * 	You should have received a copy of the GNU General Public License
 * 	along with this program; if not, write to the Free Software
 * 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 	Autentia Real Bussiness Solution S.L.
 * 	Tlf: +34 91 675 33 06, +34 655 99 11 72
 * 	Fax: +34 91 656 65 04
 * 	info@autentia.com																
 *
 --%>
<%@page language="java" contentType="text/html; charset=UTF-8"%>

<%@include file="/inc/tlibs.jsp" %>

<html>
  <head>
    <%@include file="/inc/uiCore.jsp" %>
  </head>	
  <body>
    
    <!-- searchCreditTitle.jsp: generated by stajanov code generator -->
    <f:loadBundle basename="com.autentia.tnt.resources.messages" var="msg" />
    <i:location place="searchCreditTitle" msg="${msg}"/> 
    
    <f:view>
      <%@include file="/inc/header.jsp" %>
      <h:form id="search" enctype="multipart/form-data">
        
        <%-- Header --%>
        <i:titleBar msg="${msg}">
          <h:commandLink action="#{creditTitleBean.list}">
            <h:graphicImage title="#{msg.entityActions_run}"  value="/img/run.png" styleClass="titleImg" />
          </h:commandLink>
        </i:titleBar>
        
        <%-- Search form --%>
        <table class="searchTable" cellpadding="0" cellspacing="0">

      <%-- Field: number --%>
    <tr>
      <td class="searchLabel">${msg['creditTitle.number']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="number" />
            <h:selectBooleanCheckbox id="numberValid" value="#{creditTitleBean.searchNumberValid}" 
                                      onclick="setEnabled('search:number',this.checked)"/>
            <h:inputText id="number" value="#{creditTitleBean.searchNumber}" size="70"/>
          </h:panelGroup>
          <script>
            setEnabled( 'search:number', ${creditTitleBean.searchNumberValid} )
          </script>

        
      </td>
    </tr>
    
	<%-- Field: amount --%>
    <tr>
      <td class="searchLabel">${msg['creditTitle.amount']}:</td>
      <td class="searchFieldCell">
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="startAmount" />
            <h:selectBooleanCheckbox id="startAmountValid" value="#{creditTitleBean.searchStartAmountValid}" 
                                      onclick="setEnabled('search:startAmount',this.checked)"/>
            <h:inputText id="startAmount" value="#{creditTitleBean.searchStartAmount}" size="31"/>
          </h:panelGroup>
          -
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="endAmount" />
            <h:selectBooleanCheckbox id="endAmountValid" value="#{creditTitleBean.searchEndAmountValid}" 
                                      onclick="setEnabled('search:endAmount',this.checked)"/>
            <h:inputText id="endAmount" value="#{creditTitleBean.searchEndAmount}" size="31"/>
          </h:panelGroup>
          <script>
            setEnabled( 'search:startAmount', ${creditTitleBean.searchStartAmountValid} )
            setEnabled( 'search:endAmount', ${creditTitleBean.searchEndAmountValid} )
          </script>
      </td>
    </tr>
    
      <%-- Field: concept --%>
    <tr>
      <td class="searchLabel">${msg['creditTitle.concept']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="concept" />
            <h:selectBooleanCheckbox id="conceptValid" value="#{creditTitleBean.searchConceptValid}" 
                                      onclick="setEnabled('search:concept',this.checked)"/>
            <h:inputText id="concept" value="#{creditTitleBean.searchConcept}" size="70"/>
          </h:panelGroup>
          <script>
            setEnabled( 'search:concept', ${creditTitleBean.searchConceptValid} )
          </script>

        
      </td>
    </tr>
                        
      <%-- Field: creditTitleState --%>
    <tr>
      <td class="searchLabel">${msg['creditTitle.state']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="creditTitleState" />
            <h:selectBooleanCheckbox id="creditTitleStateValid" value="#{creditTitleBean.searchCreditTitleStateValid}" 
                                      onclick="setEnabled('search:creditTitleState',this.checked)"/>
            <h:selectOneMenu id="creditTitleState" value="#{creditTitleBean.searchCreditTitleState}" onclick="setEnabled('search:creditTitleState',true)">
              <f:converter converterId="autentia.EnumConverter"/>
              <f:selectItems value="#{creditTitleBean.states}" />
            </h:selectOneMenu>
          </h:panelGroup>
          <script>
            setEnabled( 'search:creditTitleState', ${creditTitleBean.searchCreditTitleStateValid} )
          </script>

        
      </td>
    </tr>
                        
      <%-- Field: creditTitleType --%>
    <tr>
      <td class="searchLabel">${msg['creditTitle.type']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="creditTitleType" />
            <h:selectBooleanCheckbox id="creditTitleTypeValid" value="#{creditTitleBean.searchCreditTitleTypeValid}" 
                                      onclick="setEnabled('search:creditTitleType',this.checked)"/>
            <h:selectOneMenu id="creditTitleType" value="#{creditTitleBean.searchCreditTitleType}" onclick="setEnabled('search:creditTitleType',true)">
              <f:converter converterId="autentia.EnumConverter"/>
              <f:selectItems value="#{creditTitleBean.types}" />
            </h:selectOneMenu>
          </h:panelGroup>
          <script>
            setEnabled( 'search:creditTitleType', ${creditTitleBean.searchCreditTitleTypeValid} )
          </script>

        
      </td>
    </tr>
                        
      <%-- Field: issueDate --%>
    <tr>
      <td class="searchLabel">${msg['creditTitle.issueDate']}:</td>
      <td class="searchFieldCell">

        
                    
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="startIssueDate" />
            <h:selectBooleanCheckbox id="startIssueDateValid" value="#{creditTitleBean.searchStartIssueDateValid}" 
                                      onclick="setEnabled('search:startIssueDate',this.checked)"/>
            <t:inputCalendar id="startIssueDate" value="#{creditTitleBean.searchStartIssueDate}"
                             renderAsPopup="true" popupDateFormat="d/MM/yyyy" renderPopupButtonAsImage="true" 
                             popupTodayString="#{msg['calendar.today']}" popupWeekString="#{msg['calendar.week']}"
                             onchange="setEnabled('search:startIssueDate',true);setChecked('search:startIssueDateValid',true);"
                             >
				<f:validator validatorId="autentia.dateValidator"/>
			</t:inputCalendar>
          </h:panelGroup>
          -
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="endIssueDate" />
            <h:selectBooleanCheckbox id="endIssueDateValid" value="#{creditTitleBean.searchEndIssueDateValid}" 
                                      onclick="setEnabled('search:endIssueDate',this.checked)"/>
            <t:inputCalendar id="endIssueDate" value="#{creditTitleBean.searchEndIssueDate}"
                             renderAsPopup="true" popupDateFormat="d/MM/yyyy" renderPopupButtonAsImage="true" 
                             popupTodayString="#{msg['calendar.today']}" popupWeekString="#{msg['calendar.week']}"
                             onchange="setEnabled('search:endIssueDate',true);setChecked('search:endIssueDateValid',true);"
                             >
				<f:validator validatorId="autentia.dateValidator"/>
			</t:inputCalendar>
          </h:panelGroup>
          <script>
            setEnabled( 'search:startIssueDate', ${creditTitleBean.searchStartIssueDateValid} )
            setEnabled( 'search:endIssueDate', ${creditTitleBean.searchEndIssueDateValid} )
          </script>

        
      </td>
    </tr>
                        
      <%-- Field: expirationDate --%>
    <tr>
      <td class="searchLabel">${msg['creditTitle.expirationDate']}:</td>
      <td class="searchFieldCell">

        
                    
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="startExpirationDate" />
            <h:selectBooleanCheckbox id="startExpirationDateValid" value="#{creditTitleBean.searchStartExpirationDateValid}" 
                                      onclick="setEnabled('search:startExpirationDate',this.checked)"/>
            <t:inputCalendar id="startExpirationDate" value="#{creditTitleBean.searchStartExpirationDate}"
                             renderAsPopup="true" popupDateFormat="d/MM/yyyy" renderPopupButtonAsImage="true" 
                             popupTodayString="#{msg['calendar.today']}" popupWeekString="#{msg['calendar.week']}"
                             onchange="setEnabled('search:startExpirationDate',true);setChecked('search:startExpirationDateValid',true);"
                             >
				<f:validator validatorId="autentia.dateValidator"/>
			</t:inputCalendar>
          </h:panelGroup>
          -
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="endExpirationDate" />
            <h:selectBooleanCheckbox id="endExpirationDateValid" value="#{creditTitleBean.searchEndExpirationDateValid}" 
                                      onclick="setEnabled('search:endExpirationDate',this.checked)"/>
            <t:inputCalendar id="endExpirationDate" value="#{creditTitleBean.searchEndExpirationDate}"
                             renderAsPopup="true" popupDateFormat="d/MM/yyyy" renderPopupButtonAsImage="true" 
                             popupTodayString="#{msg['calendar.today']}" popupWeekString="#{msg['calendar.week']}"
                             onchange="setEnabled('search:endExpirationDate',true);setChecked('search:endExpirationDateValid',true);"
                             >
				<f:validator validatorId="autentia.dateValidator"/>
			</t:inputCalendar>
          </h:panelGroup>
          <script>
            setEnabled( 'search:startExpirationDate', ${creditTitleBean.searchStartExpirationDateValid} )
            setEnabled( 'search:endExpirationDate', ${creditTitleBean.searchEndExpirationDateValid} )
          </script>

        
      </td>
    </tr>
                        
      <%-- Field: observations --%>
    <tr>
      <td class="searchLabel">${msg['creditTitle.observations']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="observations" />
            <h:selectBooleanCheckbox id="observationsValid" value="#{creditTitleBean.searchObservationsValid}" 
                                      onclick="setEnabled('search:observations',this.checked)"/>
            <h:inputText id="observations" value="#{creditTitleBean.searchObservations}" size="70"/>
          </h:panelGroup>
          <script>
            setEnabled( 'search:observations', ${creditTitleBean.searchObservationsValid} )
          </script>

        
      </td>
    </tr>
                                  
      <%-- Field: organization --%>
    <tr>
      <td class="searchLabel">${msg['creditTitle.organization']}:</td>
      <td class="searchFieldCell">

        
          
          <h:panelGroup>
            <h:message styleClass="error" showSummary="true" showDetail="false" for="organization" />
            <h:selectBooleanCheckbox id="organizationValid" value="#{creditTitleBean.searchOrganizationValid}" 
                                      onclick="setEnabled('search:organization',this.checked)"/>
            <h:selectOneMenu id="organization" value="#{creditTitleBean.searchOrganization}" onclick="setEnabled('search:organization',true)">
              <f:selectItems value="#{creditTitleBean.organizations}" />
              <f:converter converterId="autentia.EntityConverter"/>
            </h:selectOneMenu>
          </h:panelGroup>
          <script>
            setEnabled( 'search:organization', ${creditTitleBean.searchOrganizationValid} )
          </script>

        
      </td>
    </tr>
            
        </table>
        
      </h:form>
    </f:view>
    
  </body>
</html>  		
