/**
 * TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.
 * Copyright (C) 2007 Autentia Real Bussiness Solution S.L.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.autentia.tnt.manager.activity;

import java.util.List;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import com.autentia.tnt.businessobject.Activity;
import com.autentia.tnt.dao.SortCriteria;
import com.autentia.tnt.dao.hibernate.ActivityDAO;
import com.autentia.tnt.dao.search.ActivitySearch;
import com.autentia.tnt.util.SpringUtils;

/* Activity - generated by stajanov (do not edit/delete) */


public class GlobalHourReportManager {


  /** Logger */
  private static final Log log = LogFactory.getLog(GlobalHourReportManager.class);

  
  public static GlobalHourReportManager getDefault()
  {
    return (GlobalHourReportManager)SpringUtils.getSpringBean("managerGlobalHoursReport");
  }

  /** 
   * Empty constructor needed by CGLIB (Spring AOP)
   */
  protected GlobalHourReportManager()
  {
  }


}