<%--

    TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.
    Copyright (C) 2007 Autentia Real Bussiness Solution S.L.

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

--%>

<%@page language="java" contentType="text/html; charset=UTF-8"%>

<%@include file="/inc/tlibs.jsp"%>
<html>
<head>
<%@include file="/inc/uiCore.jsp"%>
<script type="text/javascript" src="<%=request.getContextPath() %>/script/prototype.js"></script>
</head>
<body>
<!-- editContact.jsp: generated by stajanov code generator -->
<f:loadBundle basename="com.autentia.tnt.resources.messages" var="msg" />
<i:location place="editCommissioning" msg="${msg}" />

<f:view>
	<h:form id="delay" enctype="multipart/form-data">

		<%-- Header --%>
		<i:titleBar name="${commissioningBean.name}" msg="${msg}">
			<h:commandLink action="#{commissioningBean.delay}">
				<h:graphicImage value="/img/save.gif" styleClass="titleImg" />
			</h:commandLink>
		</i:titleBar>

		<%-- Edition form --%>
		<table class="editTable" cellpadding="0" cellspacing="0">


			<tr>
				<td class="editLabelRW">${msg['commissioningDelay.delayedToDate']}:</td>
				<td class="editFieldCell"><h:panelGroup>
					<h:message styleClass="error" showSummary="true" showDetail="false"
						for="delayedToDate" />
					<t:inputCalendar id="delayedToDate"
						value="#{commissioningBean.commissioningDelay.delayedToDate}"
						renderAsPopup="true" popupDateFormat="d/MM/yyyy"
						renderPopupButtonAsImage="true"
						popupLeft="true"
						popupTodayString="#{msg['calendar.today']}"
						popupWeekString="#{msg['calendar.week']}" required="true"/>
				</h:panelGroup></td>
			</tr>
			<tr>
				<td class="editLabelRW">${msg['commissioningDelay.reason']}:</td>
				<td class="editFieldCell"><h:panelGroup>
					<h:message styleClass="error" showSummary="true" showDetail="false"
						for="delayedToDate" />
					<h:inputTextarea id="reason"
						value="#{commissioningBean.commissioningDelay.reason}" required="true"/>
				</h:panelGroup></td>
			</tr>
		</table>
	</h:form>
</f:view>

</body>
</html>


