<%--

    TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.
    Copyright (C) 2007 Autentia Real Bussiness Solution S.L.

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

--%>

<%@page language="java" contentType="text/html; charset=UTF-8"%>

<%@include file="/inc/tlibs.jsp"%>
<html>
<head>
<%@include file="/inc/uiCore.jsp"%>
<script type="text/javascript"
	src="<%=request.getContextPath()%>/script/prototype.js"></script>
</head>
<body>
<!-- editContact.jsp: generated by stajanov code generator -->
<f:loadBundle basename="com.autentia.tnt.resources.messages" var="msg" />
<i:location place="commissioningChanges" msg="${msg}" />

<f:view>
	<%@include file="/inc/header.jsp"%>
	<h:form id="commissioningChanges" enctype="multipart/form-data">

		<%-- Header --%>
		<i:titleBar msg="${msg}">
			<h:commandLink action="#{commissioningBean.list}" immediate="true">
				<h:graphicImage value="/img/back.gif" styleClass="titleImg" />
			</h:commandLink>
		</i:titleBar>
		
		<t:dataTable id="list" var="change" binding="#{commissioningBean.changesDataTable}"
			value="#{commissioningBean.history}"
			preserveDataModel="false" cellpadding="0" cellspacing="0"
			styleClass="listTable" headerClass="listHeaderCell"
			footerClass="listFooter" rows="#{settingBean.mySettings.listSize}"
			rowClasses="listRowO,listRowE"
			columnClasses="listCmdCell,listCommissioningId,listCommissioningRequestDate,listCommissioningName,listCommissioningScope,listCommissioningContent,listCommissioningProducts,listCommissioningDeliveryDate,listCommissioningBudget,listCommissioningPaymentMode,listCommissioningNotes,listCommissioningAuthorSignature,listCommissioningReviserSignature,listCommissioningAdminSignature,listCommissioningJustifyInformation,listCommissioningDevelopedActivities,listCommissioningDifficultiesAppeared,listCommissioningResults,listCommissioningConclusions,listCommissioningEvaluation,listCommissioningStatus,listCommissioningInsertDate,listCommissioningUpdateDate,listCommissioningReviser,listCommissioningProject"
			rowOnMouseOver="this.savedClassName=this.className;this.className='listRowSel';"
			rowOnMouseOut="this.className=this.savedClassName;">

			<h:column>
				<f:facet name="header">
					<f:verbatim>${msg['commissioningChange.user']}</f:verbatim>
				</f:facet>

				<h:outputText value="#{change.user.name}" />

			</h:column>

			<h:column>
				<f:facet name="header">
					<f:verbatim>${msg['commissioningChange.field']}</f:verbatim>
				</f:facet>


				<h:outputText value="#{msg[change.field]}" />

			</h:column>

			<h:column>
				<f:facet name="header">
					<f:verbatim>${msg['commissioningChange.oldValue']}</f:verbatim>
				</f:facet>
				
				<h:outputText value="#{commissioningBean.changeOldValue}"/>

			</h:column>
			
			<h:column>
				<f:facet name="header">
					<f:verbatim>${msg['commissioningChange.newValue']}</f:verbatim>
				</f:facet>

				<h:outputText value="#{commissioningBean.changeNewValue}"/>
			</h:column>
			
			<h:column>
				<f:facet name="header">
					<f:verbatim>${msg['commissioningChange.status']}</f:verbatim>
				</f:facet>

				<h:outputText value="#{change.status}">
					<f:converter converterId="autentia.EnumTranslator" />
				</h:outputText>
				
			</h:column>
			<h:column>
				<f:facet name="header">
					<f:verbatim>${msg['commissioningChange.insertDate']}</f:verbatim>
				</f:facet>

				<h:outputText value="#{change.insertDate}">
					<f:convertDateTime pattern="dd/MM/yyyy HH:mm:ss"  timeZone="Europe/Madrid"/>
				</h:outputText>	

			</h:column>
		</t:dataTable>

		<%@include file="/inc/paginator.jsp"%>
	</h:form>
</f:view>

</body>
</html>


