<%--

    TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.
    Copyright (C) 2007 Autentia Real Bussiness Solution S.L.

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

--%>

<%@page language="java" contentType="text/html; charset=UTF-8"%>

<%@include file="/inc/tlibs.jsp"%>
<html>
<head>
<%@include file="/inc/uiCore.jsp"%>
<script type="text/javascript"
	src="<%=request.getContextPath()%>/script/prototype.js"></script>
</head>
<body>
<!-- editContact.jsp: generated by stajanov code generator -->
<f:loadBundle basename="com.autentia.tnt.resources.messages" var="msg" />
<i:location place="editCommissioning" msg="${msg}" />

<f:view>
	<h:form id="delays" enctype="multipart/form-data" target="_top">

		<t:dataTable id="list" var="delay"
			value="#{commissioningBean.commissioningDelays}"
			preserveDataModel="false" cellpadding="0" cellspacing="0"
			styleClass="listTable" headerClass="listHeaderCell"
			footerClass="listFooter" rows="#{settingBean.mySettings.listSize}"
			rowClasses="listRowO,listRowE"
			columnClasses="listCmdCell,listCommissioningId,listCommissioningRequestDate,listCommissioningName,listCommissioningScope,listCommissioningContent,listCommissioningProducts,listCommissioningDeliveryDate,listCommissioningBudget,listCommissioningPaymentMode,listCommissioningNotes,listCommissioningAuthorSignature,listCommissioningReviserSignature,listCommissioningAdminSignature,listCommissioningJustifyInformation,listCommissioningDevelopedActivities,listCommissioningDifficultiesAppeared,listCommissioningResults,listCommissioningConclusions,listCommissioningEvaluation,listCommissioningStatus,listCommissioningInsertDate,listCommissioningUpdateDate,listCommissioningReviser,listCommissioningProject"
			rowOnMouseOver="this.savedClassName=this.className;this.className='listRowSel';"
			rowOnMouseOut="this.className=this.savedClassName;">

			<h:column>
				<f:facet name="header">
					<f:verbatim>${msg['commissioningDelay.originalDate']}</f:verbatim>
				</f:facet>

				<h:outputText value="#{delay.originalDate}"
					converter="autentia.dateConverter" />

			</h:column>

			<h:column>
				<f:facet name="header">
					<f:verbatim>${msg['commissioningDelay.delayedToDate']}</f:verbatim>
				</f:facet>

				<h:outputText value="#{delay.delayedToDate}"
					converter="autentia.dateConverter" />

			</h:column>
			
			<h:column>
				<f:facet name="header">
					<f:verbatim>${msg['commissioningDelay.status']}</f:verbatim>
				</f:facet>

				<h:outputText value="#{delay.status}">
					<f:converter converterId="autentia.EnumTranslator" />
				</h:outputText>
				
			</h:column>
			<h:column>
				<f:facet name="header">
					<f:verbatim>${msg['commissioningDelay.reason']}</f:verbatim>
				</f:facet>

				<h:outputText value="#{delay.reason}" />

			</h:column>
		</t:dataTable>

		<%@include file="/inc/paginator.jsp"%>
	</h:form>
</f:view>

</body>
</html>


