<%--

    TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.
    Copyright (C) 2007 Autentia Real Bussiness Solution S.L.

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

--%>

<%@page language="java" contentType="text/html; charset=UTF-8"%>

<%@include file="/inc/tlibs.jsp" %>

<html>
  <head>
    <%@include file="/inc/uiCore.jsp" %>
  </head>	
  <body>
    
    <!-- editCommissioning.jsp: generated by stajanov code generator -->
    <f:loadBundle basename="com.autentia.tnt.resources.messages" var="msg" />
    <i:location place="detailCommissioning" msg="${msg}"/> 
    
    <f:view>
      <%@include file="/inc/header.jsp" %>
      <h:form id="commissioning" enctype="multipart/form-data">
        
        <%-- Header --%>
        <i:titleBar name="${commissioningBean.${desc-props.getProperty("editTitleField")}}" msg="${msg}">
          <t:commandLink action="#{commissioningBean.edit}" immediate="true" rendered="#{commissioningBean.editAvailable}">
            <f:param name="rowid" value="#{commissioningBean.id}" />
            <h:graphicImage title="#{msg.entityActions_edit}"  value="/img/edit.gif" styleClass="cmdImg" />
          </t:commandLink>
          <h:commandLink action="#{commissioningBean.delete}" rendered="#{commissioningBean.deleteAvailable}" onclick="if( !confirm('#{msg['question.confirmDelete']}') ) return false;">
            <h:graphicImage title="#{msg.entityActions_delete}"  value="/img/delete.gif" styleClass="titleImg" />
          </h:commandLink>
          <h:commandLink action="#{commissioningBean.list}" immediate="true">
            <h:graphicImage title="#{msg.entityActions_back}"  value="/img/back.gif" styleClass="titleImg" />
          </h:commandLink>
        </i:titleBar>


        <%-- Detail form --%>
        <table class="detailTable" cellpadding="0" cellspacing="0">

            
    
  
  
      <%-- Field: id --%>
    <tr>
	<td class="detailLabelRW">${msg['commissioning.id']}:</td>
	<td class="detailFieldCell">
         	       <h:outputText value="#{commissioningBean.id}" />
 	      </td>
    </tr>
                            
    
  
  
      <%-- Field: requestDate --%>
    <tr>
	<td class="detailLabelRW">${msg['commissioning.requestDate']}:</td>
	<td class="detailFieldCell">
         	    	<h:outputText value="#{commissioningBean.requestDate}" converter="autentia.dateConverter" />
 	          </td>
    </tr>
                            
    
  
  
      <%-- Field: name --%>
    <tr>
	<td class="detailLabelRW">${msg['commissioning.name']}:</td>
	<td class="detailFieldCell">
         	       <h:outputText value="#{commissioningBean.name}" />
 	      </td>
    </tr>
                            
    
  
  
      <%-- Field: scope --%>
    <tr>
	<td class="detailLabelRW">${msg['commissioning.scope']}:</td>
	<td class="detailFieldCell">
         	       <h:outputText value="#{commissioningBean.scope}" />
 	      </td>
    </tr>
                            
    
  
  
      <%-- Field: content --%>
    <tr>
	<td class="detailLabelRW">${msg['commissioning.content']}:</td>
	<td class="detailFieldCell">
         	       <h:outputText value="#{commissioningBean.content}" />
 	      </td>
    </tr>
                            
    
  
  
      <%-- Field: products --%>
    <tr>
	<td class="detailLabelRW">${msg['commissioning.products']}:</td>
	<td class="detailFieldCell">
         	       <h:outputText value="#{commissioningBean.products}" />
 	      </td>
    </tr>
                            
    
  
  
      <%-- Field: deliveryDate --%>
    <tr>
	<td class="detailLabelRW">${msg['commissioning.deliveryDate']}:</td>
	<td class="detailFieldCell">
         	    	<h:outputText value="#{commissioningBean.deliveryDate}" converter="autentia.dateConverter" />
 	          </td>
    </tr>
                            
    
  
  
      <%-- Field: budget --%>
    <tr>
	<td class="detailLabelRW">${msg['commissioning.budget']}:</td>
	<td class="detailFieldCell">
         	       <h:outputText value="#{commissioningBean.budget}" />
 	      </td>
    </tr>
                            
    
  
  
      <%-- Field: paymentMode --%>
    <tr>
	<td class="detailLabelRW">${msg['commissioning.paymentMode']}:</td>
	<td class="detailFieldCell">
                	<h:outputText value="#{commissioningBean.paymentModeFormatted}" />
              </td>
    </tr>
                            
    
  
  
      <%-- Field: notes --%>
    <tr>
	<td class="detailLabelRW">${msg['commissioning.notes']}:</td>
	<td class="detailFieldCell">
         	       <h:outputText value="#{commissioningBean.notes}" />
 	      </td>
    </tr>
                            
    
  
  
      <%-- Field: authorSignature --%>
    <tr>
	<td class="detailLabelRW">${msg['commissioning.authorSignature']}:</td>
	<td class="detailFieldCell">
        		<h:selectBooleanCheckbox id="authorSignature" value="#{commissioningBean.authorSignature}" disabled="true"/>
              </td>
    </tr>
                            
    
  
  
      <%-- Field: reviserSignature --%>
    <tr>
	<td class="detailLabelRW">${msg['commissioning.reviserSignature']}:</td>
	<td class="detailFieldCell">
        		<h:selectBooleanCheckbox id="reviserSignature" value="#{commissioningBean.reviserSignature}" disabled="true"/>
              </td>
    </tr>
                            
    
  
  
      <%-- Field: adminSignature --%>
    <tr>
	<td class="detailLabelRW">${msg['commissioning.adminSignature']}:</td>
	<td class="detailFieldCell">
        		<h:selectBooleanCheckbox id="adminSignature" value="#{commissioningBean.adminSignature}" disabled="true"/>
              </td>
    </tr>
                            
    
  
  
      <%-- Field: justifyInformation --%>
    <tr>
	<td class="detailLabelRW">${msg['commissioning.justifyInformation']}:</td>
	<td class="detailFieldCell">
        		<h:selectBooleanCheckbox id="justifyInformation" value="#{commissioningBean.justifyInformation}" disabled="true"/>
              </td>
    </tr>
                            
    
  
  
      <%-- Field: developedActivities --%>
    <tr>
	<td class="detailLabelRW">${msg['commissioning.developedActivities']}:</td>
	<td class="detailFieldCell">
         	       <h:outputText value="#{commissioningBean.developedActivities}" />
 	      </td>
    </tr>
                            
    
  
  
      <%-- Field: difficultiesAppeared --%>
    <tr>
	<td class="detailLabelRW">${msg['commissioning.difficultiesAppeared']}:</td>
	<td class="detailFieldCell">
         	       <h:outputText value="#{commissioningBean.difficultiesAppeared}" />
 	      </td>
    </tr>
                            
    
  
  
      <%-- Field: results --%>
    <tr>
	<td class="detailLabelRW">${msg['commissioning.results']}:</td>
	<td class="detailFieldCell">
         	       <h:outputText value="#{commissioningBean.results}" />
 	      </td>
    </tr>
                            
    
  
  
      <%-- Field: conclusions --%>
    <tr>
	<td class="detailLabelRW">${msg['commissioning.conclusions']}:</td>
	<td class="detailFieldCell">
         	       <h:outputText value="#{commissioningBean.conclusions}" />
 	      </td>
    </tr>
                            
    
  
  
      <%-- Field: evaluation --%>
    <tr>
	<td class="detailLabelRW">${msg['commissioning.evaluation']}:</td>
	<td class="detailFieldCell">
         	       <h:outputText value="#{commissioningBean.evaluation}" />
 	      </td>
    </tr>
                            
    
  
  
      <%-- Field: status --%>
    <tr>
	<td class="detailLabelRW">${msg['commissioning.status']}:</td>
	<td class="detailFieldCell">
                	<h:outputText value="#{commissioningBean.statusFormatted}" />
              </td>
    </tr>
                            
    
  
  
      <%-- Field: insertDate --%>
    <tr>
	<td class="detailLabelRW">${msg['commissioning.insertDate']}:</td>
	<td class="detailFieldCell">
         	    	<h:outputText value="#{commissioningBean.insertDate}" converter="autentia.dateConverter" />
 	          </td>
    </tr>
                            
    
  
  
      <%-- Field: updateDate --%>
    <tr>
	<td class="detailLabelRW">${msg['commissioning.updateDate']}:</td>
	<td class="detailFieldCell">
         	    	<h:outputText value="#{commissioningBean.updateDate}" converter="autentia.dateConverter" />
 	          </td>
    </tr>
                                        
    
  
  
      <%-- Field: reviser --%>
    <tr>
	<td class="detailLabelRW">${msg['commissioning.reviser']}:</td>
	<td class="detailFieldCell">
         	    	<h:outputText value="#{commissioningBean.reviser.${df}}"/>
 	          </td>
    </tr>
                            
    
  
  
      <%-- Field: project --%>
    <tr>
	<td class="detailLabelRW">${msg['commissioning.project']}:</td>
	<td class="detailFieldCell">
         	    	<h:outputText value="#{commissioningBean.project.${df}}"/>
 	          </td>
    </tr>
                                      
        </table>

      </h:form>
    </f:view>
    
  </body>
</html>  		

<%-- Commissioning - generated by stajanov (do not edit/delete) --%>
