<%--

    TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.
    Copyright (C) 2007 Autentia Real Bussiness Solution S.L.

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

--%>

<%-- 
 * TNTConcept Easy Enterprise Management by Autentia Real Bussiness Solution S.L.  
 *	Copyright (C) 2007 Autentia Real Bussiness Solution S.L.					   
 *	
 * 	This program is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU General Public License
 * 	as published by the Free Software Foundation; either version 2
 * 	of the License, or (at your option) any later version.
 *
 * 	This program is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *
 * 	You should have received a copy of the GNU General Public License
 * 	along with this program; if not, write to the Free Software
 * 	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 	Autentia Real Bussiness Solution S.L.
 * 	Tlf: +34 91 675 33 06, +34 655 99 11 72
 * 	Fax: +34 91 656 65 04
 * 	info@autentia.com																
 *
 --%>
<%@page language="java" contentType="text/html; charset=UTF-8"%>

<%@include file="/inc/tlibs.jsp"%>

<html>
<head>
<%@include file="/inc/uiCore.jsp"%>
</head>
<body>

<!-- searchCommissioning.jsp: generated by stajanov code generator -->
<f:loadBundle basename="com.autentia.tnt.resources.messages" var="msg" />
<i:location place="searchCommissioning" msg="${msg}" />

<f:view>
	<%@include file="/inc/header.jsp"%>
	<h:form id="search" enctype="multipart/form-data">

		<%-- Header --%>
		<i:titleBar msg="${msg}">
			<h:commandLink action="#{commissioningBean.list}">
				<h:graphicImage title="#{msg.entityActions_run}"
					value="/img/run.png" styleClass="titleImg" />
			</h:commandLink>
		</i:titleBar>

		<%-- Search form --%>
		<table class="searchTable" cellpadding="0" cellspacing="0">

			<%-- Field: status --%>
			<tr>
				<td class="searchLabel">${msg['commissioning.status']}:</td>
				<td class="searchFieldCell"><h:panelGroup>
					<h:message styleClass="error" showSummary="true" showDetail="false"
						for="status" />
					<h:selectBooleanCheckbox id="statusValid"
						value="#{commissioningBean.searchStatusValid}"
						onclick="setEnabled('search:status',this.checked)" />
					<h:selectOneMenu id="status"
						value="#{commissioningBean.searchStatus}"
						onclick="setEnabled('search:status',true)">
						<f:converter converterId="autentia.EnumConverter" />
						<f:selectItems value="#{commissioningBean.statuss}" />
					</h:selectOneMenu>
				</h:panelGroup> <script>
            setEnabled( 'search:status', ${commissioningBean.searchStatusValid} )
          </script></td>
			</tr>

			<%-- Field: requestDate --%>
			<tr>
				<td class="searchLabel">${msg['commissioning.requestDate']}:</td>
				<td class="searchFieldCell"><h:panelGroup>
					<h:message styleClass="error" showSummary="true" showDetail="false"
						for="startRequestDate" />
					<h:selectBooleanCheckbox id="startRequestDateValid"
						value="#{commissioningBean.searchStartRequestDateValid}"
						onclick="setEnabled('search:startRequestDate',this.checked)" />
					<t:inputCalendar id="startRequestDate"
						value="#{commissioningBean.searchStartRequestDate}"
						renderAsPopup="true" popupDateFormat="d/MM/yyyy"
						renderPopupButtonAsImage="true"
						popupTodayString="#{msg['calendar.today']}"
						popupWeekString="#{msg['calendar.week']}"
						onchange="setEnabled('search:startRequestDate',true);setChecked('search:startRequestDateValid',true);" />
				</h:panelGroup> - <h:panelGroup>
					<h:message styleClass="error" showSummary="true" showDetail="false"
						for="endRequestDate" />
					<h:selectBooleanCheckbox id="endRequestDateValid"
						value="#{commissioningBean.searchEndRequestDateValid}"
						onclick="setEnabled('search:endRequestDate',this.checked)" />
					<t:inputCalendar id="endRequestDate"
						value="#{commissioningBean.searchEndRequestDate}"
						renderAsPopup="true" popupDateFormat="d/MM/yyyy"
						renderPopupButtonAsImage="true"
						popupTodayString="#{msg['calendar.today']}"
						popupWeekString="#{msg['calendar.week']}"
						onchange="setEnabled('search:endRequestDate',true);setChecked('search:endRequestDateValid',true);" />
				</h:panelGroup> <script>
            setEnabled( 'search:startRequestDate', ${commissioningBean.searchStartRequestDateValid} )
            setEnabled( 'search:endRequestDate', ${commissioningBean.searchEndRequestDateValid} )
          </script></td>
			</tr>

			<%-- Field: name --%>
			<tr>
				<td class="searchLabel">${msg['commissioning.name']}:</td>
				<td class="searchFieldCell"><h:panelGroup>
					<h:message styleClass="error" showSummary="true" showDetail="false"
						for="name" />
					<h:selectBooleanCheckbox id="nameValid"
						value="#{commissioningBean.searchNameValid}"
						onclick="setEnabled('search:name',this.checked)" />
					<h:inputText id="name" value="#{commissioningBean.searchName}"
						size="70" />
				</h:panelGroup> <script>
            setEnabled( 'search:name', ${commissioningBean.searchNameValid} )
          </script></td>
			</tr>

			<%-- Field: scope --%>
			<tr>
				<td class="searchLabel">${msg['commissioning.scope']}:</td>
				<td class="searchFieldCell"><h:panelGroup>
					<h:message styleClass="error" showSummary="true" showDetail="false"
						for="scope" />
					<h:selectBooleanCheckbox id="scopeValid"
						value="#{commissioningBean.searchScopeValid}"
						onclick="setEnabled('search:scope',this.checked)" />
					<h:inputText id="scope" value="#{commissioningBean.searchScope}"
						size="70" />
				</h:panelGroup> <script>
            setEnabled( 'search:scope', ${commissioningBean.searchScopeValid} )
          </script></td>
			</tr>

			<%-- Field: content --%>
			<tr>
				<td class="searchLabel">${msg['commissioning.content']}:</td>
				<td class="searchFieldCell"><h:panelGroup>
					<h:message styleClass="error" showSummary="true" showDetail="false"
						for="content" />
					<h:selectBooleanCheckbox id="contentValid"
						value="#{commissioningBean.searchContentValid}"
						onclick="setEnabled('search:content',this.checked)" />
					<h:inputText id="content"
						value="#{commissioningBean.searchContent}" size="70" />
				</h:panelGroup> <script>
            setEnabled( 'search:content', ${commissioningBean.searchContentValid} )
          </script></td>
			</tr>

			<%-- Field: products --%>
			<tr>
				<td class="searchLabel">${msg['commissioning.products']}:</td>
				<td class="searchFieldCell"><h:panelGroup>
					<h:message styleClass="error" showSummary="true" showDetail="false"
						for="products" />
					<h:selectBooleanCheckbox id="productsValid"
						value="#{commissioningBean.searchProductsValid}"
						onclick="setEnabled('search:products',this.checked)" />
					<h:inputText id="products"
						value="#{commissioningBean.searchProducts}" size="70" />
				</h:panelGroup> <script>
            setEnabled( 'search:products', ${commissioningBean.searchProductsValid} )
          </script></td>
			</tr>

			<%-- Field: deliveryDate --%>
			<tr>
				<td class="searchLabel">${msg['commissioning.deliveryDate']}:</td>
				<td class="searchFieldCell"><h:panelGroup>
					<h:message styleClass="error" showSummary="true" showDetail="false"
						for="startDeliveryDate" />
					<h:selectBooleanCheckbox id="startDeliveryDateValid"
						value="#{commissioningBean.searchStartDeliveryDateValid}"
						onclick="setEnabled('search:startDeliveryDate',this.checked)" />
					<t:inputCalendar id="startDeliveryDate"
						value="#{commissioningBean.searchStartDeliveryDate}"
						renderAsPopup="true" popupDateFormat="d/MM/yyyy"
						renderPopupButtonAsImage="true"
						popupTodayString="#{msg['calendar.today']}"
						popupWeekString="#{msg['calendar.week']}"
						onchange="setEnabled('search:startDeliveryDate',true);setChecked('search:startDeliveryDateValid',true);" />
				</h:panelGroup> - <h:panelGroup>
					<h:message styleClass="error" showSummary="true" showDetail="false"
						for="endDeliveryDate" />
					<h:selectBooleanCheckbox id="endDeliveryDateValid"
						value="#{commissioningBean.searchEndDeliveryDateValid}"
						onclick="setEnabled('search:endDeliveryDate',this.checked)" />
					<t:inputCalendar id="endDeliveryDate"
						value="#{commissioningBean.searchEndDeliveryDate}"
						renderAsPopup="true" popupDateFormat="d/MM/yyyy"
						renderPopupButtonAsImage="true"
						popupTodayString="#{msg['calendar.today']}"
						popupWeekString="#{msg['calendar.week']}"
						onchange="setEnabled('search:endDeliveryDate',true);setChecked('search:endDeliveryDateValid',true);" />
				</h:panelGroup> <script>
            setEnabled( 'search:startDeliveryDate', ${commissioningBean.searchStartDeliveryDateValid} )
            setEnabled( 'search:endDeliveryDate', ${commissioningBean.searchEndDeliveryDateValid} )
          </script></td>
			</tr>

			<%-- Field: budget --%>
			<tr>
				<td class="searchLabel">${msg['commissioning.budget']}:</td>
				<td class="searchFieldCell"><h:panelGroup>
					<h:message styleClass="error" showSummary="true" showDetail="false"
						for="budget" />
					<h:selectBooleanCheckbox id="budgetValid"
						value="#{commissioningBean.searchBudgetValid}"
						onclick="setEnabled('search:budget',this.checked)" />
					<h:inputText id="budget" value="#{commissioningBean.searchBudget}"
						size="70" />
				</h:panelGroup> <script>
            setEnabled( 'search:budget', ${commissioningBean.searchBudgetValid} )
          </script></td>
			</tr>

			<%-- Field: notes --%>
			<tr>
				<td class="searchLabel">${msg['commissioning.notes']}:</td>
				<td class="searchFieldCell"><h:panelGroup>
					<h:message styleClass="error" showSummary="true" showDetail="false"
						for="notes" />
					<h:selectBooleanCheckbox id="notesValid"
						value="#{commissioningBean.searchNotesValid}"
						onclick="setEnabled('search:notes',this.checked)" />
					<h:inputText id="notes" value="#{commissioningBean.searchNotes}"
						size="70" />
				</h:panelGroup> <script>
            setEnabled( 'search:notes', ${commissioningBean.searchNotesValid} )
          </script></td>
			</tr>

			<%-- Field: authorSignature --%>
			<tr>
				<td class="searchLabel">${msg['commissioning.authorSignature']}:</td>
				<td class="searchFieldCell"><h:panelGroup>
					<h:message styleClass="error" showSummary="true" showDetail="false"
						for="authorSignature" />
					<h:selectBooleanCheckbox id="authorSignatureValid"
						value="#{commissioningBean.searchAuthorSignatureValid}"
						onclick="setEnabledByName('search:authorSignature',this.checked)" />

					<h:outputLabel for="authorSignature" value="#{msg['msg.yesno']}"></h:outputLabel>
					<h:selectBooleanCheckbox id="authorSignature"
						value="#{commissioningBean.searchAuthorSignature}" />


				</h:panelGroup> <script>
            setEnabledByName( 'search:authorSignature', ${commissioningBean.searchAuthorSignatureValid} )
          </script></td>
			</tr>

			<%-- Field: reviserSignature --%>
			<tr>
				<td class="searchLabel">${msg['commissioning.reviserSignature']}:</td>
				<td class="searchFieldCell"><h:panelGroup>
					<h:message styleClass="error" showSummary="true" showDetail="false"
						for="reviserSignature" />
					<h:selectBooleanCheckbox id="reviserSignatureValid"
						value="#{commissioningBean.searchReviserSignatureValid}"
						onclick="setEnabledByName('search:reviserSignature',this.checked)" />

					<h:outputLabel for="reviserSignature" value="#{msg['msg.yesno']}"></h:outputLabel>
					<h:selectBooleanCheckbox id="reviserSignature"
						value="#{commissioningBean.searchReviserSignature}" />


				</h:panelGroup> <script>
            setEnabledByName( 'search:reviserSignature', ${commissioningBean.searchReviserSignatureValid} )
          </script></td>
			</tr>

			<%-- Field: adminSignature --%>
			<tr>
				<td class="searchLabel">${msg['commissioning.adminSignature']}:</td>
				<td class="searchFieldCell"><h:panelGroup>
					<h:message styleClass="error" showSummary="true" showDetail="false"
						for="adminSignature" />
					<h:selectBooleanCheckbox id="adminSignatureValid"
						value="#{commissioningBean.searchAdminSignatureValid}"
						onclick="setEnabledByName('search:adminSignature',this.checked)" />

					<h:outputLabel for="adminSignature" value="#{msg['msg.yesno']}"></h:outputLabel>
					<h:selectBooleanCheckbox id="adminSignature"
						value="#{commissioningBean.searchAdminSignature}" />


				</h:panelGroup> <script>
            setEnabledByName( 'search:adminSignature', ${commissioningBean.searchAdminSignatureValid} )
          </script></td>
			</tr>

			<%-- Field: justifyInformation --%>
			<tr>
				<td class="searchLabel">${msg['commissioning.justifyInformation']}:</td>
				<td class="searchFieldCell"><h:panelGroup>
					<h:message styleClass="error" showSummary="true" showDetail="false"
						for="justifyInformation" />
					<h:selectBooleanCheckbox id="justifyInformationValid"
						value="#{commissioningBean.searchJustifyInformationValid}"
						onclick="setEnabledByName('search:justifyInformation',this.checked)" />

					<h:outputLabel for="justifyInformation" value="#{msg['msg.yesno']}"></h:outputLabel>
					<h:selectBooleanCheckbox id="justifyInformation"
						value="#{commissioningBean.searchJustifyInformation}" />


				</h:panelGroup> <script>
            setEnabledByName( 'search:justifyInformation', ${commissioningBean.searchJustifyInformationValid} )
          </script></td>
			</tr>

			<%-- Field: developedActivities --%>
			<tr>
				<td class="searchLabel">${msg['commissioning.developedActivities']}:</td>
				<td class="searchFieldCell"><h:panelGroup>
					<h:message styleClass="error" showSummary="true" showDetail="false"
						for="developedActivities" />
					<h:selectBooleanCheckbox id="developedActivitiesValid"
						value="#{commissioningBean.searchDevelopedActivitiesValid}"
						onclick="setEnabled('search:developedActivities',this.checked)" />
					<h:inputText id="developedActivities"
						value="#{commissioningBean.searchDevelopedActivities}" size="70" />
				</h:panelGroup> <script>
            setEnabled( 'search:developedActivities', ${commissioningBean.searchDevelopedActivitiesValid} )
          </script></td>
			</tr>

			<%-- Field: difficultiesAppeared --%>
			<tr>
				<td class="searchLabel">${msg['commissioning.difficultiesAppeared']}:</td>
				<td class="searchFieldCell"><h:panelGroup>
					<h:message styleClass="error" showSummary="true" showDetail="false"
						for="difficultiesAppeared" />
					<h:selectBooleanCheckbox id="difficultiesAppearedValid"
						value="#{commissioningBean.searchDifficultiesAppearedValid}"
						onclick="setEnabled('search:difficultiesAppeared',this.checked)" />
					<h:inputText id="difficultiesAppeared"
						value="#{commissioningBean.searchDifficultiesAppeared}" size="70" />
				</h:panelGroup> <script>
            setEnabled( 'search:difficultiesAppeared', ${commissioningBean.searchDifficultiesAppearedValid} )
          </script></td>
			</tr>

			<%-- Field: results --%>
			<tr>
				<td class="searchLabel">${msg['commissioning.results']}:</td>
				<td class="searchFieldCell"><h:panelGroup>
					<h:message styleClass="error" showSummary="true" showDetail="false"
						for="results" />
					<h:selectBooleanCheckbox id="resultsValid"
						value="#{commissioningBean.searchResultsValid}"
						onclick="setEnabled('search:results',this.checked)" />
					<h:inputText id="results"
						value="#{commissioningBean.searchResults}" size="70" />
				</h:panelGroup> <script>
            setEnabled( 'search:results', ${commissioningBean.searchResultsValid} )
          </script></td>
			</tr>

			<%-- Field: conclusions --%>
			<tr>
				<td class="searchLabel">${msg['commissioning.conclusions']}:</td>
				<td class="searchFieldCell"><h:panelGroup>
					<h:message styleClass="error" showSummary="true" showDetail="false"
						for="conclusions" />
					<h:selectBooleanCheckbox id="conclusionsValid"
						value="#{commissioningBean.searchConclusionsValid}"
						onclick="setEnabled('search:conclusions',this.checked)" />
					<h:inputText id="conclusions"
						value="#{commissioningBean.searchConclusions}" size="70" />
				</h:panelGroup> <script>
            setEnabled( 'search:conclusions', ${commissioningBean.searchConclusionsValid} )
          </script></td>
			</tr>

			<%-- Field: evaluation --%>
			<tr>
				<td class="searchLabel">${msg['commissioning.evaluation']}:</td>
				<td class="searchFieldCell"><h:panelGroup>
					<h:message styleClass="error" showSummary="true" showDetail="false"
						for="evaluation" />
					<h:selectBooleanCheckbox id="evaluationValid"
						value="#{commissioningBean.searchEvaluationValid}"
						onclick="setEnabled('search:evaluation',this.checked)" />
					<h:inputText id="evaluation"
						value="#{commissioningBean.searchEvaluation}" size="70" />
				</h:panelGroup> <script>
            setEnabled( 'search:evaluation', ${commissioningBean.searchEvaluationValid} )
          </script></td>
			</tr>

			<%-- Field: project --%>
			<tr>
				<td class="searchLabel">${msg['commissioning.project']}:</td>
				<td class="searchFieldCell"><h:panelGroup>
					<h:message styleClass="error" showSummary="true" showDetail="false"
						for="project" />
					<h:selectBooleanCheckbox id="projectValid"
						value="#{commissioningBean.searchProjectValid}"
						onclick="setEnabled('search:project',this.checked)" />
					<h:selectOneMenu id="project"
						value="#{commissioningBean.searchProject}"
						onclick="setEnabled('search:project',true)">
						<f:selectItems value="#{commissioningBean.projects}" />
						<f:converter converterId="autentia.EntityConverter" />
					</h:selectOneMenu>
				</h:panelGroup> <script>
            setEnabled( 'search:project', ${commissioningBean.searchProjectValid} )
          </script></td>
			</tr>

			<%-- Field: deleted --%>
			<tr>
				<td class="searchLabel">${msg['commissioning.deleted']}:</td>
				<td class="searchFieldCell"><h:panelGroup>
					<h:message styleClass="error" showSummary="true" showDetail="false"
						for="deleted" />
					<h:selectBooleanCheckbox id="deletedValid"
						value="#{commissioningBean.searchDeletedValid}"
						onclick="setEnabledByName('search:deleted',this.checked)" />

					<h:outputLabel for="deleted" value="#{msg['msg.yesno']}"></h:outputLabel>
					<h:selectBooleanCheckbox id="deleted"
						value="#{commissioningBean.searchDeleted}" />

				</h:panelGroup> <script>
            setEnabledByName( 'search:deleted', ${commissioningBean.searchDeletedValid} )
          </script></td>
			</tr>


		</table>

	</h:form>
</f:view>

</body>
</html>
